### ISSUE TITLE
GNOME Version Support

### ISSUE THREAD

**Issue by swinkl3** [jderose9/dash-to-panel#1]
Hi,

I am trying to use your extension on my Ubuntu 16.04 LTS but the GNOME Tweak Tool is telling me that the extension is incompatible with the shell version. My version of GNOME is 3.18.5.

I'm presuming that this is compatible with 3.20, but if it is backwards compatible with 3.18 it would be nice to use. Otherwise perhaps adding a note to the readme with version support would be good.

Cheers.

**Comment by jderose9** [comment]
If the version isn't listed in metadata.json, gnome won't let you enable it by default. I had not tested it in 3.18, so I did not add it.

But, I just installed Ubuntu Gnome 16.04 in a VM and everything seems to be working as expected, so I'm going to add 3.18 now. (In case you aren't sure - to get the latest, you can execute "git pull" in the folder you cloned into, then "make install" to copy the file out to the extensions folder)

Thanks for the feedback!
