### ISSUE TITLE
Icons too small on HiDPI screen

### ISSUE THREAD

**Issue by gnunn1** [jderose9/dash-to-panel#10]
I use a Macbook pro with Window scaling set to 2 in the gnome tweak tool. The icons don't look like they are being scaled like the rest of the Gnome Shell interface. Screenshot as follows:

![screenshot from 2017-01-09 07-28-04](https://cloud.githubusercontent.com/assets/9358238/21766555/34c06c7a-d63d-11e6-947e-f0860171bb16.png)

**Comment by jderose9** [comment]
Nice wallpaper! The icons resize automatically to fit the height of the panel. You can make the panel taller (therefore making the icons larger) in the extension's settings window. Does that do what you want or am I misunderstanding?

**Comment by gnunn1** [comment]
The gnome tweak tool has a feature that allows you to scale windows up or down so HiDPI users can increase the size of the display. I have the panel size set to 48 but expectation is with a window scaling factor of 2 it should increase to 96 based on the scaling factor but it does not, it stays at 48 requiring me to manually increase it.

If I was always using a HiDPI display it wouldn't be an issue, but I flip between HiDPI (When laptop disconnected) and non-HiDPI (external monitor) pretty regularly.

Hope that makes sense.

**Comment by gnunn1** [comment]
BTW I see you are new to Gnome, this scaling factor is in the Gnome tweak tool if you are unfamiliar with it:

![screenshot from 2017-01-09 10-35-51](https://cloud.githubusercontent.com/assets/9358238/21772169/23e13216-d658-11e6-9cf2-01eeae041a01.png)

**Comment by jderose9** [comment]
Yes, it makes sense. Thanks for the screenshot - I was looking at the scaling factor under the Fonts tab. I can get the scaling factor and update the panel height, but it looks like gnome-shell doesn't know about the scaling factor change until it is restarted. (Only the window manager seems to update immediately). Do you already have to restart the gnome shell when you change this, typically?

**Comment by jderose9** [comment]
Also, I'm assuming the window preview is not currently, but should be, resizing?

**Comment by gnunn1** [comment]
Yes, I have re-start gnome shell when I change this scaling factor.

As for the window preview, I'm at the office and don't remember how large it was at home. It looks OK to me at the moment but I'll compare when I get home.

**Comment by jderose9** [comment]
Are you able to get the dev branch and test this? (Commit 40fb563aaea8bf85d7b2ac96674078607bab47bd)

**Comment by gnunn1** [comment]
Just tried the dev branch and it looks fine to me. When i switch the scale from 1 to 2 and restart gnome-shell the icons double their size as expected. Switching back to 1 and re-starting shrinks the icons back to original size. The window preview also adjusts size correctly for the scale factor.
