### ISSUE TITLE
Changing panel size doesn't adjust icon size for running apps until extension restart

### ISSUE THREAD

**Issue by eexpress** [jderose9/dash-to-panel#102]
![-2017-03-03-21 30 18-391x31](https://cloud.githubusercontent.com/assets/700793/24200104/f144034c-0f46-11e7-9779-8bea66ff68b3.png)
![-2017-03-03-21 31 28-336x27](https://cloud.githubusercontent.com/assets/700793/24200109/f430a538-0f46-11e7-895f-4cc8a971994a.png)
![-2017-03-03-21 32 51-563x238](https://cloud.githubusercontent.com/assets/700793/24200159/2669d8d0-0f47-11e7-97b3-eaf03b483145.png)

**Comment by jderose9** [comment]
This is only an issue when you initially adjust the panel size. If you restart the extension or log back in it will be corrected from then on.

**Comment by eexpress** [comment]
Yes, after restart. It goes OK. thanks.

**Comment by lexruee** [comment]
This comment is just for documentation purposes here. It's a copy and paste from the duplicate here: https://github.com/jderose9/dash-to-panel/issues/226

**Problem:** Resizing the Panel does not respect the App Icon Margin.

**Steps to reproduce:**
1. Set Panel Size to 24 px
2. Set App Icon Margin to 0 px
3. Resize the Panel by setting its size to 96 px
4. Resize the Panel again by setting its size to 24 px

**Dash to Panel Version:** master (7bb1cb05c0710aa02c72dc15866316736e623319)

**My System:**
```
Debian GNU/Linux unstable (sid)
GNOME Shell 3.22.3
```

**Video**
I made a short youtube video that demonstrates this bug:
https://youtu.be/dfdwA1gilc8

**Comment by jderose9** [comment]
This should be resolved. If someone could grab newest master and give it a shot, that would be great.
