### ISSUE TITLE
VPN menu won't open with large list

### ISSUE THREAD

**Issue by FOOTCLAN** [jderose9/dash-to-panel#111]
The VPN menu won't open when using a large list of connections.

**Comment by jderose9** [comment]
Hi there.. This was actually fixed recently. Can you make sure you are updated to the latest version (v8 on gnome.org)?

https://github.com/jderose9/dash-to-panel/issues/6

thanks!

**Comment by tleasure** [comment]
I'm experiencing this with version 11.  I have a large list of VPN servers.  When I try to open the list, it just closes out. 

4.13.12-300.fc27.x86_64
