### ISSUE TITLE
Crash on right-clicking application icons

### ISSUE THREAD

**Issue by V3XATI0N** [jderose9/dash-to-panel#118]
The plugin crashes GNOME Shell entirely whenever I right-click any application icon. Additionally, if I try to access the "Fine-Tune/App Icon Secondary (right-click) menu" options in the settings UI, the settings UI window errors and closes with no feedback.

GNOME Shell version is 3.24.0

here's the output of neofetch...
```
OS: Ubuntu Zesty Zapus (development branch) x86_64 
Model: XPS 15 9550 
Kernel: 4.10.0-15-generic 
Uptime: 2 hours, 2 mins 
Packages: 3427 
Shell: fish 2.4.0 
Resolution: 1920x1080 
DE: GNOME 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: VimixDark-Laptop [GTK2/3] 
Icons: EPapirus [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-6700HQ (8) @ 3.5GHz 
GPU: Intel HD Graphics 530 
GPU: NVIDIA GeForce GTX 960M 
Memory: 8472MiB / 15864MiB
```
(Intel driver is active at the moment but the bug occurs either way.)

**Comment by franglais125** [comment]
Are there any errors in the logs?
Something like this might give you a hint: `sudo journalctl /usr/bin/gnome-shell`.

**Comment by V3XATI0N** [comment]
I triggered the crash on purpose and reviewed the log, it seems this is the relevant bit here:

```
Settings schema 'org.gnome.shell.extensions.dash-to-panel' does not contain a key named 'secondarymenu-contains-showdetails'
```

**Comment by V3XATI0N** [comment]
I'm not a dconf pro, so I'm confused. dconf-editor shows /org/gnome/shell/extensions/dash-to-panel (though not the "secondarymeny-contains-showdetails" key mentioned above); but there is no "dash-to-panel" item in extensions as far as gsettings is concerned. So I can't manually create that key with gsettings. I've created it with the dconf command, but it doesn't seem to matter.

**Comment by franglais125** [comment]
I'll have to try a 17.04 install (since you are on Gnome 3.24). But in any case, the user shouldn't need to create keys manually.
The key *is* part of the extension, I don't know why you don't have it.

How did you install the latest version of dash-to-panel?

**Comment by franglais125** [comment]
@V3XATI0N I can't reproduce the issue on Ubuntu GNOME 17.04. Right-click menu is working as expected, with the "Show details" menu item. Also, I could open the settings window and use the "Fine-Tune/App Icon Secondary (right-click) menu" without any trouble.

How did you install/update dash-to-panel?

**Comment by V3XATI0N** [comment]
extensions.gnome.org doesn't work, so I installed manually from git (master branch). I was able to import the schema by copying to /usr/share/glib-2.0/schemas and recompiling, but it has no effect on the issue.

**Comment by franglais125** [comment]
And what about in `.local/share/gnome-shell/extensions/` ?

**Comment by franglais125** [comment]
By the way, from git, you can run `make && make install` and it will install to `.local/share/gnome-shell/extensions/`.

**Comment by V3XATI0N** [comment]
yes, sorry, i mean that is how i installed it. checkout, make, make install.

**Comment by V3XATI0N** [comment]
but redoing that seems to have fixed the issue... nevermind......
