### ISSUE TITLE
Provide translation template (pot file)

### ISSUE THREAD

**Issue by jonnius** [jderose9/dash-to-panel#125]
I would like to provide a German translation, but i couldn't find the translation template file (*.pot). Please add it to the po folder!

**Comment by jderose9** [comment]
Hi @jonnius. Thanks for contributing a translation! You should just be able to go to the folder you cloned into and type:

`make potfile` 

That will generate and updated one for you.

**Comment by jonnius** [comment]
It worked after installing the package **intltool** (Ubuntu 16.04). Thanks!
