### ISSUE TITLE
Ability to move notifications pop-up 

### ISSUE THREAD

**Issue by dosmachko** [jderose9/dash-to-panel#13]
Hi, thanks a lot for your extension.

Is it possible to add functionality to move notification to bottom right corner?
Because as for now it's not convenient to see notification on the top center position.

Thanks.

**Comment by jderose9** [comment]
I think being able to move the notification popup is a very good idea, but wonder if perhaps it isn't best for a separate extension (maybe one exists already?) as you may want to move the popup regardless of whether you are this extension or not.

**Comment by dosmachko** [comment]
I'm not sure if there is any extension that could provide a good behaviour for moving notifications, some of them are already outdated. 

From my point of view it's better to have all in one rather then using separated extensions. 

What do you think ?


Thanks.

**Comment by Ixoos** [comment]
https://extensions.gnome.org/extension/708/panel-osd/

**Comment by jderose9** [comment]
@lxoos Wow, that's a nice extension!

@dosmachko I'm going to close this as this extension seems to be compatible with Panel OSD and I don't think there's reason to spend effort in maintaining a copy of that code in this extension. Thanks for the suggestion!
