### ISSUE TITLE
Feature Request: Notifications follow Clock to Bottom Right

### ISSUE THREAD

**Issue by ElectricPrism** [jderose9/dash-to-panel#132]
Hi, I was wondering if you would be up to add a toggle to move the notifications to the bottom right corner of the screen where the clock is.

**Comment by jderose9** [comment]
Hi there! Is this what you are looking for? https://extensions.gnome.org/extension/708/panel-osd/

**Comment by jderose9** [comment]
I'm going to close this one for now as I believe it is covered by Panel OSD... however, feel free to correct me if you feel otherwise :)
