### ISSUE TITLE
[Question] Maximize effect is very ugly

### ISSUE THREAD

**Issue by ceyhunnabiyev** [jderose9/dash-to-panel#137]
Window controls - Minimize, close  animation working on Gnome,  but maximize effect is very ugly. Can be this related to Dash-to-panel?

**Comment by jderose9** [comment]
Can you try disable all extensions and see if it occurs, and then enable only dash-to-panel and see if it occurs? What do you mean by ugly exactly?

**Comment by jderose9** [comment]
Hi there, I'm going to close this since we don't have enough information to take action, but if you decide to post back with some more detail I will be glad to re-open. Thanks!
