### ISSUE TITLE
Resize Icons

### ISSUE THREAD

**Issue by TechnoSparks** [jderose9/dash-to-panel#139]
Greetings!

I would like to request a new feature to this marvellous extension! It would be quite of a great addition to the extension, if the possibility to customise the size of the icons is introduced.

Resizing the panel height does changes the icons' sizes, however, a finer control would allow somebody to alter the taskbar to a comfortable appearance.

Thank you so much for the extension.

**Comment by jderose9** [comment]
Thanks, nice idea. I'm going to close it as it is pretty much the same as #75. Hop over there for progress updates!

**Comment by TechnoSparks** [comment]
Oh I didn't know that the request referenced is the same as my request. I am very sorry for creating a duplicate issue.

Thank you!

**Comment by jderose9** [comment]
No sweat! The description is different but the result is the same - you can either set the panel height and the padding and have the icon size fill the remainder, or the I on size and have the padding fill the remainder. Thanks again for the feedback.

**Comment by TechnoSparks** [comment]
I managed to dig a part into the extension's source in order to achieve what i intended. Now my taskbar looks cute! 😆

Anyway, for those who wishes to do this, this require editing the extension's file, and of course any updates in the future will put your modifications away!

## As of v11
Edit file `taskbar.js` from `~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com` (assuming standard installation)

Go to line **640**. Notice the code segment:
```
        let newIconSize = this._availableIconSizes[0];
        for (let i = 0; i < iconSizes.length ; i++) {
            if (iconSizes[i] < availSize) {
                newIconSize = this._availableIconSizes[i];
            }
        }
```

Comment the `for` block, thus preventing the extension from calculating an icon size based on your taskbar height.
```
        let newIconSize = this._availableIconSizes[0];
        /*for (let i = 0; i < iconSizes.length ; i++) {
            if (iconSizes[i] < availSize) {
                newIconSize = this._availableIconSizes[i];
            }
        }*/
```

Notice the line `let newIconSize = this._availableIconSizes[0];` . This is there to set the lowest possible size before the commented `for` block find the suitable icon size. The `_availableIconSizes` is an identical array of `baseIconSizes`. Such array initialisation can be seen on line 173.

This is the declaration of `baseIconSizes`
```
const baseIconSizes = [ 16, 22, 24, 32, 48, 64, 96, 128 ];
```
Thus this is the indexes that refers to the sizes:

| Index      | Size      |
| --- | --- |
| 0 | 16 |
| 1 | 22 |
| 2 | 24 |
| 3 | 32 |
| 4 | 48 |
| 5 | 64 |
| 6 | 96 |
| 7 | 128 |

Based on the `index` that reflects the icon size that you want, modify the line 640, change the array index from `0` to something else (if applicable). For example, if I want to have the icon on 24x24 size, I would need to change `0` to `2`. If you want it at 16x16 then you can leave the `0` as is.
```
let newIconSize = this._availableIconSizes[2];
```

Here's the final code segment:
```
        let newIconSize = this._availableIconSizes[2]; // I HAVE MODIFIED THIS
        /*for (let i = 0; i < iconSizes.length ; i++) {
            if (iconSizes[i] < availSize) {
                newIconSize = this._availableIconSizes[i];
            }
        }*/
```

Save the file, and then restart your shell for changes to take affect! Here's my cute 16x16 icons:
![screenshot from 2018-01-22 20-03-26](https://user-images.githubusercontent.com/6072210/35219907-62aef0ec-ffaf-11e7-844a-66226422822b.png)

---

@jderose9 I have an idea for the graphical part of this. A user may able to set a specific size (based on the `baseIconSizes` elements. If set, a boolean var stores that the user have set a specific size, and thus not include the `for` logic in the source.

I really wish I could do this on my own and do a pull request, but Gnome extensions is an area where I have zero expertise.

As always, this is again **just** a request. I will maybe try to understanding the working of the extension, and implement such graphical option, if I have enough free time on my end!
