### ISSUE TITLE
Favorite Icon stops tracking old instances when application is updated

### ISSUE THREAD

**Issue by Despruk** [jderose9/dash-to-panel#140]
**Gnome**: 3.24 (and older)
**Extension**: v8
**OS**: Arch linux

**Description**:
When system updates package of running application, if the Application is "Favorite" the Icon will stop showing running instances/windows of the application.
Clicking on Icon will open a new window/instance, which will be tracked.
Removing "Favorite" from the Icon will start tracking running instances, re-applying "Favorite" will again stop tracking.

Can easy be reproduced at any time by simply downgrading/upgrading anything, such as firefox.

No interesting gnome messages appear in system log.

Restarting shell / reloging fixes the issue, so it's not a major bug, but was still very confuing the first few times I saw it happen.

**Comment by jderose9** [comment]
Would you be able to try this without the extension installed, to see if it occurs in the left-side favorites bar in the Activities Overview?

**Comment by Despruk** [comment]
@jderose9 
Yes, default favorites bar behaves the same way.

**Comment by jderose9** [comment]
@Despruk Unfortunately I think you will have to report it to gnome bugzilla instead. Here is the URL:
https://bugzilla.gnome.org/

Thank you for your time!
