### ISSUE TITLE
Set close button side for window previews

### ISSUE THREAD

**Issue by camwright** [jderose9/dash-to-panel#148]
Currently the close button on window previews is on the right side of the thumbnail. It might be nice to be able to choose which side to place the close button on, or perhaps do it automatically based on the dconf `button-layout` key. This happens automatically in the default Gnome overview screen, for instance.

**Comment by bil-elmoussaoui** [comment]
Duplicate of https://github.com/jderose9/dash-to-panel/issues/90

**Comment by camwright** [comment]
Ah, I searched but didn't see that. Sorry.
