### ISSUE TITLE
Activities button keeps on reappearing

### ISSUE THREAD

**Issue by swarnendubiswas** [jderose9/dash-to-panel#149]
I have disabled "Activities" button through settings. The change is reflected temporarily, but then the button comes back after some time (not sure what triggers it reappearance). Please check the attached screenshot.
![screenshot from 2017-05-09 20-51-01](https://cloud.githubusercontent.com/assets/7343807/25858380/401ce56a-34f9-11e7-96ee-b86ec04ed5ab.png)

This issue happens both with v8 and from Github.

**Comment by jderose9** [comment]
It seems most likely to be caused by another extension. Does it happen when you disable all others?

**Comment by ckrzen** [comment]
Watch-out for one-way(overwrite) sync's while using the Chrome browser "Gnome Shell integration" extension. It bit me when first using dash-to-panel that was installed on one workstation, but not another.

**Comment by swarnendubiswas** [comment]
True, it seems that this extension works fine by itself. I tested that out by disabling other extensions. Thanks.
