### ISSUE TITLE
use the dash-to-dock containers and css classes

### ISSUE THREAD

**Issue by zagortenay333** [jderose9/dash-to-panel#15]
Right now this extension doesn't replicate the exact containers and classes of the dash-to-dock extension and as a result doesn't benefit if a theme has a style for the dash-to-dock extension.

**Comment by jderose9** [comment]
I tried applying and repurposing the dash-to-dock classes before, but it doesn't seem feasible to me.  The container for dash-to-dock is created and css ID assigned within the extension. This extension is using the gnome main panel which is already created when the extension starts.

In many cases the styles don't make sense. For example, many themes style the background of the dash-to-panel scrollview. In dash-to-dock this takes the entire width of the panel, but here it is only one portion of the panel, and styling the scrollview alone makes it look out of place.

Lastly, the the container hierarchy would need to be maintained in sync with dash-to-dock forever despite diverging feature sets, which seems nearly impossible.

I'm definitely open to other ideas to improving the ability to theme this. I do think the id naming could be improved (dashtopanelScrollview instead taskbarScrollview) for themes that wish to specifically target this extension. Do you agree? Do you have any other suggestions?

Thanks for the feedback.

**Comment by zagortenay333** [comment]
You really can't put the app icons into an StBin called `dashtodockContainer` ?

Well, then surely you could add style classes so that a theme developer can support this extension? Also, including a top-level class in place of the `.popup-menu` you removed earlier.

**Comment by jderose9** [comment]
Yes I can, but it won't do what you want - only the segment of the panel containing the app icons would be styled. I can't add a new StBin around the entire contents of the main panel as it would break many of the widgets that add themselves to the panel.

I can add a class to the main panel when this extension is enabled. The rest of the layout containers can be accessed in css with the id selectors named currently "taskbar<ObjectName>" but I will change this to "dashtopanel<ObjectName>" to be more explicit.

I know you mentioned the running indicators in another issue. The currently active window indicator can be styled with css class "app-well-app-running-dot". The circles are drawn in JS using the size and color from that element - it would be good if these were able to be styled with css too. I'll wait until a solution for #12 is decided on to take action on this though as it would likely change.

**Comment by zagortenay333** [comment]
Well that's what I mean. I meant putting only the box with the app icons into the `dashtodockContainer`, not the whole taskbar. Like an embedded dash-to-dock. That would solve #12, right?

**Comment by jderose9** [comment]
It doesn't make sense to me to do that. The appearance would not be seamless across the taskbar. Many themes have a black topbar and transparent dash-to-dock panel - that change would create a transparent hole in the middle of a solid panel. If you need to isolate the app icons in your selector, you could use the scrollview id.

**Comment by zagortenay333** [comment]
How would that make a hole in the panel? It's a box inside the panel box.

**Comment by jderose9** [comment]
Yes exactly. If my #panel background is green and my #dashtodockContainer background is purple, I will have a purple section in the middle of my green taskbar. Theme creators have styled #dashtodockContainer with the intention that they were styling an entire panel, and now you are asking me to apply that style to only a fragment within a panel that has its own separate style.

**Comment by zagortenay333** [comment]
Yeah, that wouldn't work. :disappointed:

**Comment by jderose9** [comment]
Here's an example so you can see what I mean:
![capture](https://cloud.githubusercontent.com/assets/2118702/21828554/104e353e-d75f-11e6-84c8-add8c421ed6b.PNG)

**Comment by jderose9** [comment]
I added the top level class dashtopanelMainPanel to the gnome main panel and renamed the other container IDs to #dashtoPanel<whatever>.

**Comment by zagortenay333** [comment]
Nice :smile:
