### ISSUE TITLE
Trying to extend Dash to Panel - problem with Meta dependency

### ISSUE THREAD

**Issue by muttleyxd** [jderose9/dash-to-panel#154]
Hi there,

First I'll say, I know this is not the best place to ask, but unfortunately documentation on GNOME JS and resources found on the Internet didn't answer my question.

I'm trying to create an enhancement for Dash to Panel - trying to add an option to select which screen should be used.

I got it working with hardcoded monitor selection. So the next step would be adding an option to prefs.js, and here I met a problem, which I can't resolve.

Iterating monitors requires looking into Main.layoutManager.monitors array.
So for that I need to add import:
`const Main = imports.ui.main;`

Unfortunately, when opening Dash to Panel preferences I get this error:

```
Error: Requiring Meta, version none: Typelib file for namespace 'Meta' (any version) not found

Stack trace:
  @resource:///org/gnome/shell/ui/main.js:10:7
  @/home/muttley/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:30:7
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49
  
```

I don't have an idea what could cause this, if someone could maybe take a quick look I'd be very grateful.

I'm using Manjaro Linux with testing repositories enabled and GNOME 3.24.

If adding 'Main' to prefs.js works for you, then please write what distro you use - I'd like to test it and try to find what causes the problem on my side.

**Comment by jderose9** [comment]
Those imports.ui.* libraries aren't available within prefs.js because prefs.js actually runs outside of the context of the extension (whether the extension is enabled or not).

You can use the Gdk library to do similar. Actually this feature is in dash-to-dock so you can probably pretty much just copy all of the relevant code from there.

Here's how it finds the monitors available:

```
let n_monitors = Gdk.Screen.get_default().get_n_monitors();
let primary_monitor = Gdk.Screen.get_default().get_primary_monitor();
```

**Comment by muttleyxd** [comment]
Thanks, now I got it working, when the code gets decent I may send a pull request (don't really know if somebody has such a weird use-case for having it on other monitor).

**Comment by jderose9** [comment]
Since you can assign the primary monitor in gnome, and the main purpose of that seems to be to determine which monitor the bar is displayed on, is there any benefit to having the option within the extension?

**Comment by muttleyxd** [comment]
I have 2 monitors -1680x1050 on the left, 1920x1080 on the right.
I prefer having panel on the left, because I run full screen games on the right monitor, but I want to see running apps, tray and clock.
Some games (especially those ran with Wine) won't see secondary monitor. So when I run the game it'll tell me that max resolution is 1680x1050. Some games support resizing and will scale correctly, but most do not. That'd leave me with game which takes 80% of the screen and doesn't recognize mouse input correctly.

I could send a pull request but I guess I'd have to mimic the code from Dash to Dock, since my own code gets buggy when monitor layout is changed and it requires shell restart.

**Comment by jderose9** [comment]
This feature was requested in #171. If you get the bugs worked out and want to open a pull request, it would be more than appreciated. Thank you!
