### ISSUE TITLE
Panel at the bottom blocks "OK" and "Cancel" buttons of vmware settings window

### ISSUE THREAD

**Issue by mudongliang** [jderose9/dash-to-panel#155]
I install dash-to-panel extension in my gnome 3.22.2. I set the panel to the bottom.
When I try to see the setting of one virtual machine, I find that the panel at the bottom blocks the bottom part of vmware setting window.

**Comment by jderose9** [comment]
Hi @mudongliang! Thanks for reporting this. Would you be able to provide a screenshot? I've used VMWare Player quite a bit and not had any issue altering the settings so I'm curious as to which setting window you are referring to. Thanks!

**Comment by mudongliang** [comment]
![screenshot from 2017-05-12 14-22-33](https://cloud.githubusercontent.com/assets/6214861/26011287/799dd732-371e-11e7-97e1-3a741e87bda3.png)

**Comment by mudongliang** [comment]
![screenshot from 2017-05-12 14-24-04](https://cloud.githubusercontent.com/assets/6214861/26011332/ace57a96-371e-11e7-88ae-793b9c4b613f.png)

**Comment by jderose9** [comment]
So even without the extension it seems like the window is getting chopped off? It seems like vmware just doesn't have a scrollable settings window and it doesn't fit in your display?

**Comment by mudongliang** [comment]
> So even without the extension it seems like the window is getting chopped off?

Yes.

VMware Workstation differs from VMware Player. I tried VMware Player, there is no problem.

Maybe the settings windows does not fit in my display. I don't know.

**Comment by jderose9** [comment]
Yes, I don't think there is anything I can do. If the application windows were stacked over the taskbar, you wouldn't be able to switch windows. When #41 is complete it might help you, but just by coincidence. The window really should be re-sizable on the VMWare side.
