### ISSUE TITLE
Middle-click on preview closes window

### ISSUE THREAD

**Issue by TurkeyMan** [jderose9/dash-to-panel#156]
Please add an option to allow middle-click on the hover preview to close the application.
Windows has always been like this, and it's useful when you have a few instances of an app open, you hover to see previews of each of the windows, and you want to close a couple of them.
Note: it's important that the preview doesn't disappear with each middle-click, since you will often want to close multiple windows at once. The preview should remain visible, but animate such that the remaining windows move to fill the space of the one that was closed, just like when pressing the 'x' at the top right.

**Comment by jderose9** [comment]
Nice idea, thanks!

**Comment by jderose9** [comment]
This has been completed by @jackwickham . Thank you!!

https://github.com/jderose9/dash-to-panel/pull/251
