### ISSUE TITLE
Panel background blur

### ISSUE THREAD

**Issue by Alexander-Wilms** [jderose9/dash-to-panel#157]
It would be nice to have the option to blur everything behind the panel (wallpaper & windows).

Here's how this can be done in pure CSS, not sure if that would work just like that with Gnome's CSS: https://codepen.io/anthonyadamski/pen/yJBpd

Cf. https://github.com/micheleg/dash-to-dock/issues/224

**Comment by jderose9** [comment]
Love it, but I think the implementation belongs in Dynamic Panel Transparency instead. (Here's why - https://github.com/jderose9/dash-to-panel/issues/124#issuecomment-293667877)

Actually there seems to be an existing issue open there: https://github.com/rockon999/dynamic-panel-transparency/issues/57
