### ISSUE TITLE
Upload on GNOME extensions?

### ISSUE THREAD

**Issue by zoutiyx** [jderose9/dash-to-panel#16]
Will you be uploading this awesome extension to https://extensions.gnome.org?

**Comment by cra0zy** [comment]
https://extensions.gnome.org/review/6520

**Comment by jderose9** [comment]
Yep, uploaded last week. Haven't heard anything from their review process yet though. Thanks!

**Comment by jderose9** [comment]
This extension is now available on gnome.org.

https://extensions.gnome.org/extension/1160/dash-to-panel/

If you've installed from github you will need to Remove in Tweak Tool and reinstall from there to get the automated updates. Thanks!
