### ISSUE TITLE
Clock's padding changes when using Notifications Alert extension

### ISSUE THREAD

**Issue by s4bba7** [jderose9/dash-to-panel#160]
There's a weird behaviour when using this extension with Notifications Alert extension.
When you receive any notification and set Dash-to-panel's "fine tuning" -> "tray item padding" to:
1. less than default value (0-11) it increases the size of left and right padding of the clock.
2. greater than default value (>13) it decreases those paddings.
3. equal (12) it stays normal.

Example:
(when you receive notification the clock's font is starting to blink between white and red colour)
https://youtu.be/CpJ2rrA0BLA

//EDIT:
Forget to mention that I already looked into Notifications Alert's code and it looks like their code don't change that behaviour.

**Comment by jderose9** [comment]
This problem needs to be corrected in Notifications Alert extension. When it assigns the color style, it removes the style that this panel has added. It could be updated to append to the existing style instead.

`let userStyle = "color: " + settings.get_string(SETTING_COLOR);`
