### ISSUE TITLE
Arrow to expand extensions on the panel

### ISSUE THREAD

**Issue by tilnic** [jderose9/dash-to-panel#161]
HI. First of all thank you so much for this great extension, I love it. Just a question: is it possible to add an arrow which shows, separately, the extensions on the panel? Something like Windows and KDE taskbar (but with the extensions and not the notification area). Thank you for everything.

![2017-05-14 18_47_13-](https://cloud.githubusercontent.com/assets/28689323/26036555/fb8cc84e-38df-11e7-87f1-061b51703d80.jpg)

**Comment by franglais125** [comment]
Perhaps something like this extension? Unless I'm misunderstanding!

https://extensions.gnome.org/extension/1137/gnome-shell-extension-reloader/

**Comment by tilnic** [comment]
Thanks for your reply. A similar layout but with different purposes: that extension is a reloader, I meant a way to expand active extensions on the panel with an arrow which allows to add extra space. It's useful in those cases where the panel is filled.

**Comment by jderose9** [comment]
I think it's a great idea and one I would love to see implemented. However, this extension doesn't add those tray icons to the panel. It is Top Icons Plus that does so, and I think the work would need to be done in that extension. https://extensions.gnome.org/extension/1031/topicons/
