### ISSUE TITLE
way of triggering desktop overview

### ISSUE THREAD

**Issue by dobkeratops** [jderose9/dash-to-panel#162]
Would it be possible to add an icon for activating the desktop/window overview (like the mission control icon in the MacOSX doc),
maybe even just clicking on the panel outside of application icons could do this

Some people seem to want a 'show-desktop' icon , but showing the overview is superior given a multi-desktop window manager as the starting point (IMO).

EDIT:  Seems there is an option in preferences (behaviour->show activities button) that handles this, thanks!

maybe as a minor aesthetic tweak it could be replaced with an icon of some sort (to make it visually fit with the fact this is an icon bar), and maybe it could be enhanced to show desktop thumbnails just like the window thumbnails, but the actual overview is there already.

**Comment by dobkeratops** [comment]
the hot corner is an ok idea, but for some reason I find it really uncomfortable; I think it's ok when a menu appears, but I don't like the screen corner instigates a whole screen change; I think it's the fact that it can be activated accidentally. (if it makes a menu or panel appear, its easier to move out to cancel it)

if there was an icon representing the overview, maybe it could also show the desktops as thumbnails in a similar manner to the window overviews .. the whole experience would fit together better - navigation all being based on that same panel.

Another idea might be to just have the actual desktop thumbnails as separate icons , like an enhanced version of the classic panel desktop switcher

**Comment by jderose9** [comment]
Hello! You can add the Activities button back to the panel by flipping a switch in the Behavior tab in the extension settings. Is that what you are looking for?

**Comment by dobkeratops** [comment]
+jderose9  ahh , thanks! thats exactly what I was after. Aesthetically replacing that with an icon might be nice but ultimately it fixes my issue.
I was using my setup with synergy so had lost 'top-corner' activation. 

I wonder if the overview mode itself could be tweaked to show the desktop thumbnails on the left side. Then it would be closer to the 'activities' click (i.e. you move the cursor to the bottom left, you see the thumbnails vertically, you move the cursor up, click and you're done.. instead of having to move all the way left, then all the way right.. this is the flaw in the gnome-shell default design, not a problem with this specific extention)

**Comment by dobkeratops** [comment]
(+jderose9  actually, maybe you could offer a binding for left, right,mid clicks on the panel itself, with the option of binding any of those to 'show the overview' - this would reduce the distance you have to move the cursor, e.g. if you want to use the desktop switcher... but having the activities button is a big improvement for me)

**Comment by jderose9** [comment]
You can adjust the icon with the Activities Configurator extension: https://extensions.gnome.org/extension/358/activities-configurator/
