### ISSUE TITLE
Split thumbnail titles over 2 lines?

### ISSUE THREAD

**Issue by dobkeratops** [jderose9/dash-to-panel#163]
Could the window thumbnails be brought closer together by splitting the title text over 2 or more lines, to minimize the gaps between each, see illustration
![gnomeshellpanelthumbnailsuggestion](https://cloud.githubusercontent.com/assets/1120754/26178088/6fdcf996-3b54-11e7-9e4a-c442a6974f9c.gif)

**Comment by jderose9** [comment]
I think this can be folded into with #27 which requests the margin to be configurable. Thanks!
