### ISSUE TITLE
move DesktopOverviewThumbnails to left edge, nearer to 'activities' button

### ISSUE THREAD

**Issue by dobkeratops** [jderose9/dash-to-panel#165]
See illustration;  To drastically reduce the distance you have to move the mouse for switching to specific desktops, could the overview desktop thumbnails be moved to the left side of the screen - closer to the 'activities' button. the illustration shows the mouse distance required for a desktop switch , blue lines for the suggestion, blue+red dashed line for the current behaviour.

(Alternative suggestions with similar goal - see #167 #168 )

Is this possible through the panel ? Does the underlying gnome-shell code have repositioning options that extensions can communicate with (it seems to me each extention might want it's own tweaks to the overview; 'dash-to-panel' eliminates the need for the shell overview to show an application switcher)
![gnomeshellpaneloverviewsuggestion](https://cloud.githubusercontent.com/assets/1120754/26179682/fd79c182-3b5c-11e7-8c97-9bc25278e64f.gif)

As an alternative, if the whole panel could be used to activate the overview, you'd also save on mouse distance (e.g. if clicking in empty panel area activated the overview, you wouldn't need to move to the corner

Seems to me the default "gnome shell overview" display assumes that launching applications is the most common use of that screen, but this panel extention makes launching applications faster already, so the next most likely action can go closer to the button.

**Comment by jderose9** [comment]
Check out workspaces to dock. It will allow you to move the workspace bar over to the left hand side: https://extensions.gnome.org/extension/427/workspaces-to-dock/

Let me know if that doesn't cover what you are looking for and I can re-open.

Regarding your questions about the gnome shell code... The portions of gnome shell implemented in javascript can be completely overridden by any extension. The potential limiting factors are compatibility with other extensions and having to pull/tweak a lot of code from the shell and having it break on a future gnome release.
