### ISSUE TITLE
drag-drop file to application launcher

### ISSUE THREAD

**Issue by dobkeratops** [jderose9/dash-to-panel#166]
Could the panel icons respond to drag-dropping files , i.e. to make an application open the dropped file ? .. I don't seem to see this behaviour active at the minute. This would enhance the utility of the panel

**Comment by jderose9** [comment]
This isn't possible without revision of C code on the gnome side. See this issue: https://github.com/jderose9/dash-to-panel/issues/46

You can keep the mouse depressed, hover over the panel, and it will open the overview, then you can hover over the application you want and it will become focused, and then drop the file. it's cumbersome, but it's about the best that's possible at the moment.
