### ISSUE TITLE
workspace thumbnails, similar to classic gnome-planel workspace switcher

### ISSUE THREAD

**Issue by dobkeratops** [jderose9/dash-to-panel#168]
See illustration, ![workspacethumbnailsuggestion](https://cloud.githubusercontent.com/assets/1120754/26181114/8477a08e-3b65-11e7-96bc-78b513bbbc58.gif)

Would it be possible to make panel icons (rendered the same as desktop overviews) representing each workspace, similar to the panel switcher. This would make the panel itself a more powerful desktop/window navigator. Of course, arguably this wastes effort replicating work that the overview does, but you would still prefer to use the overview to organise windows

This could also be an alternative to showing the 'activities' button.

Workspace icons could be drag-drop targets, e.g. "move this application to this workspace.." ...  some classic panels allow this behaviour, which is very intuitive.

Being able to search both 'by application' and 'by workspace' is useful in different situations

(Alternative suggestions with similar goal: #165 #167 )

**Comment by jderose9** [comment]
Yeah, I miss this from other desktop environments. However, I think it probably belongs in another extension. There's already a few that handle switching workspaces (though they don't currently provide the visual contents as you suggest). For instance: https://extensions.gnome.org/extension/21/workspace-indicator/

I think doing the work in a separate extension is preferrable as it would be a nice feature regardless of whether dash-to-panel is used.

**Comment by dobkeratops** [comment]
> doing the work in a separate extension is preferrable

i've not looked into it in such depth .. but what would be great is if these features were integrated such that you could drag-drop between them - I've seen this on some classic taskbars (e.g. drag the window button onto a desktop, and it moves the window there). this could be really nice with the modern overviews IMO.

still.. I appreciate the fear of introducing too much complexity into one extention.. more to go wrong

**Comment by jderose9** [comment]
Yes, that would be cool. I don't know if it's possible though. The drag and drop programming interface is very limited (thus for example the inability to drag/drop a file onto the panel). Have you seen Workspaces-to-dock though? It lets you drag an icon representation of the window from one workspace to another.
