### ISSUE TITLE
Make dots for background applications bigger

### ISSUE THREAD

**Issue by gnunn1** [jderose9/dash-to-panel#17]
I have a hard time seeing the dots that are used for background applications. Would it be possible to make them a bit wider then they are now? Admittedly part of this is because I use a theme with a darker color for selection color, as a result it doesn't standout well against the black background of the panel.

**Comment by jderose9** [comment]
I agree. It seems the indicators could use some thoughtful design in general. I'm going to close this one for now as it's very similar to the discussion in #12.
