### ISSUE TITLE
Add option to display hotkey numbers permanently

### ISSUE THREAD

**Issue by pofl** [jderose9/dash-to-panel#174]
I'd like to recommend adding an option to display hotkey numbers permanently, so one is saved from having to press Super+q.

**Comment by jderose9** [comment]
Seems reasonable to me.

@franglais125 Do you see any downsides to this?

Thank you!

**Comment by franglais125** [comment]
Well, as long as it's an option, then sure! If someone doesn't like it, they can simply turn it off.

For anyone wanting this, it can clutter the icons. You'd have a number overlay, and then the indicators showing number of windows, etc. But again, it's up to them to turn it on (I'd recommend having it off by default!)

**Comment by franglais125** [comment]
@jderose9 I'm trying to implement this. I haven't used the extension in a while, so I haven't tested it for some time.

I just installed master from git, and it seems I can't change the overlay settings. For instance `<Super>q` seems to be stuck in this value. Can you reproduce this? I just want to make sure what the current status is before changing anything.

I can look into this if this is indeed a bug.

**Comment by franglais125** [comment]
@jderose9 I fixed the problem I had found (in Settings.ui the can_focus property was set to false), and implemented this feature.

Let me know what you think!

https://github.com/franglais125/dash-to-panel/tree/number_overlay

**Comment by franglais125** [comment]
I guess this can be closed now?
