### ISSUE TITLE
Disable F2 Button

### ISSUE THREAD

**Issue by JREAM** [jderose9/dash-to-panel#175]
Hey this is embarassing but I cannot find where to disable the darn F2 button. I use that often for renaming files! Anyone know where this is in the settings? I could have sworn I saw it before too.

**Comment by bil-elmoussaoui** [comment]
@JREAM 
What do you mean by disabling the F2 button?

**Comment by JREAM** [comment]
F2 Hotkey open the Menu at the

**Comment by bil-elmoussaoui** [comment]
It must be another extension that does that.
See https://github.com/jderose9/dash-to-panel/search?utf8=%E2%9C%93&q=F2&type=
There's no F2 on the source code, check  `gnome-shell-extension-prefs` to see which extensions are enabled on your system!
And by the way, your videos on Youtube are awesome!

**Comment by JREAM** [comment]
Oh shoot, Rookie me, thanks! Ha, didn't know anyone knew about me thanks LOL

On Fri, May 26, 2017 at 4:58 PM, Bilal Elmoussaoui <notifications@github.com

**Comment by JREAM** [comment]
Bah, it was Gno-Menu my bad
