### ISSUE TITLE
Hotkey Overlay Scaling

### ISSUE THREAD

**Issue by rhollencamp** [jderose9/dash-to-panel#178]
![dash-to-panel](https://cloud.githubusercontent.com/assets/550626/26591971/50df2888-452d-11e7-9519-5f7704e9d5b5.png)

Screenshot shows issue pretty well - hotkey overlay is way to big and covers up the app icon entirely. Relevant dconf settings:
 - org.gnome.desktop.interface.scaling-factor = 2
 - org.gnome.desktop.interface.text-scaling-factor = 0.9

**Comment by rhollencamp** [comment]
@franglais125 it sounds like you are a good point of contact for this feature?

**Comment by franglais125** [comment]
@rhollencamp I pushed a fix to the PR I had already opened (since it was about number overlays anyway).

https://github.com/jderose9/dash-to-panel/pull/176

Do you mind checking if it fixes the problem for you?

**Comment by franglais125** [comment]
Here is how you can test it:

```
git clone https://github.com/franglais125/dash-to-panel
cd dash-to-panel
git checkout number_overlay
make && make install
```

**Comment by rhollencamp** [comment]
patch looks good, +1

**Comment by jderose9** [comment]
Closing as the fix has been merged. Thanks everyone!
