### ISSUE TITLE
Icons desapear when using hide-top-bar

### ISSUE THREAD

**Issue by alanlivio** [jderose9/dash-to-panel#179]
I tried use dash-to-panel with hide-top-bar[1] gnome extension.
The panel actually hide, but some icons were hided.

[1] https://extensions.gnome.org/extension/545/hide-top-bar/

This screenshot is before enable hide-top-bar..
![screenshot from 2017-05-30 15-29-52](https://cloud.githubusercontent.com/assets/604808/26601470/4d333eee-4556-11e7-8899-e6fad943a821.png)

This screenshot is after enable hide-top-bar..
![screenshot from 2017-05-30 15-29-23](https://cloud.githubusercontent.com/assets/604808/26601466/4a06e7d4-4556-11e7-9c5e-2539877be04a.png)

**Comment by jderose9** [comment]
Hi, thanks so much for reporting this! This extension doesn't currently work very well with Hide Top Bar. There's an open issue (#41) to add the feature within this extension to get around some of the issues. Additionally, I think you are experiencing the graphical issue reported in #92. You might want to subscribe to those two issues for updates. Thanks again.
