### ISSUE TITLE
Scrollable taskbar icon when set Panel size < 48

### ISSUE THREAD

**Issue by xpduyson** [jderose9/dash-to-panel#18]
Icon on taskbar can scroll vertically when using some custom Gnome shell theme (I'm using [Flat-Plat-Blue](https://github.com/peterychuang/Flat-Plat-Blue))

Example: https://gfycat.com/DenseFlawedBangeltiger

**Comment by jderose9** [comment]
I installed the theme from your link and I'm not seeing this behavior. I made a change that may have fixed it a couple of days ago. Could you try pulling the latest from master for both this extension and the theme and try again?

**Comment by xpduyson** [comment]
Sorry for late reply, and I'm sorry because custom shell theme is not the cause of this issue. The vertical scroll icon happen when you set panel size below 48 px.

**Comment by jderose9** [comment]
I'm not seeing this, even with smaller than 48px panel, so we need to figure out what differs with your setup. Are you using an icon theme that doesn't provide scalable or smaller than 32px icons, perhaps?

**Comment by kuba77cz** [comment]
I have this issue too when I'm using custom icon theme (with default adwaita icon theme it is ok)

**Comment by jderose9** [comment]
@kuba77cz Can you link or attach the icon theme so I can try to reproduce?

**Comment by elsieholmes** [comment]
I've got the same issue and it's very annoying. Could you please fix the code?
P.S. I tested an extension with many icon themes including Adwaita and it doesn't seem to change anything. The problem is still here.

**Comment by Ixoos** [comment]
![Preview](https://media.giphy.com/media/d1E2BMkamr3KE9oc/giphy.gif)
I'm using Arc theme with papirus icons and my panel size is 40px

**Comment by jderose9** [comment]
OK - I think I see this issue now with < 48px panel. You have to actually scroll with your mouse wheel correct? It doesn't do it simply by hovering, right?

**Comment by elsieholmes** [comment]
@jderose9 exactly.
