### ISSUE TITLE
Icons disappear sometimes

### ISSUE THREAD

**Issue by Hativ3** [jderose9/dash-to-panel#180]
All icons disappear sometimes. Then I have to disable and re-enable the extension.

journalctl outputs the following error messages until the icons disappear:
> Jun 02 08:31:34 nuc gnome-shell[4091]: _cogl_buffer_fini: assertion '!(buffer->flags & COGL_BUFFER_FLAG_MAPPED)' failed
> Jun 02 08:31:34 nuc gnome-shell[4091]: WARNING: addSignalMethods is replacing existing [0x32bcdd0 Gjs_ShowAppsIcon.dash-item-container] emit method
> Jun 02 08:31:34 nuc gnome-shell[4091]: WARNING: addSignalMethods is replacing existing [0x32bcdd0 Gjs_ShowAppsIcon.dash-item-container] disconnect method
> Jun 02 08:31:34 nuc gnome-shell[4091]: WARNING: addSignalMethods is replacing existing [0x32bcdd0 Gjs_ShowAppsIcon.dash-item-container] connect method
> Jun 02 08:31:30 nuc gnome-shell[4091]: JS WARNING: [resource:///org/gnome/shell/ui/workspace.js 1233]: reference to undefined property this._reservedSlotWindow
> Jun 02 08:22:26 nuc gnome-shell[4091]: JS WARNING: [resource:///org/gnome/shell/ui/popupMenu.js 24]: reference to undefined property child._delegate
> Jun 02 08:22:26 nuc gnome-shell[4091]: JS WARNING: [resource:///org/gnome/shell/ui/popupMenu.js 502]: reference to undefined property child._delegate
> Jun 02 08:22:24 nuc dbus-daemon[4058]: Successfully activated service 'org.gnome.ChromeGnomeShell'
> Jun 02 08:22:24 nuc gnome-shell[4091]: JS WARNING: [resource:///org/gnome/shell/ui/keyboard.js 573]: reference to undefined property actor.extended_key
> Jun 02 08:19:38 nuc gnome-shell[4091]: JS WARNING: [resource:///org/gnome/shell/ui/dash.js 760]: reference to undefined property oldApps[oldIndex]
> Jun 02 08:19:29 nuc gnome-shell[4091]: _cogl_buffer_fini: assertion '!(buffer->flags & COGL_BUFFER_FLAG_MAPPED)' failed
> Jun 02 08:19:27 nuc gnome-shell[4091]: JS WARNING: [resource:///org/gnome/shell/ui/messageList.js 169]: reference to undefined property this._container
> Jun 02 08:19:27 nuc gnome-shell[4091]: JS WARNING: [resource:///org/gnome/shell/ui/messageList.js 392]: reference to undefined property this._useBodyMarkup
> Jun 02 08:19:27 nuc gnome-shell[4091]: JS WARNING: [resource:///org/gnome/shell/ui/notificationDaemon.js 394]: reference to undefined property hints.resident
> Jun 02 08:19:27 nuc gnome-shell[4091]: JS WARNING: [resource:///org/gnome/shell/ui/notificationDaemon.js 189]: reference to undefined property ndata.hints['desktop-entry']
> Jun 02 08:19:27 nuc gnome-shell[4091]: JS WARNING: [/home/username/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/windowPreview.js 616]: reference to undefined property oldWin[oldIndex]
> Jun 02 08:19:19 nuc gnome-shell[4091]: JS WARNING: [/home/username/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js 419]: reference to undefined property dots._tweeningToWidth
> Jun 02 08:19:19 nuc gnome-shell[4091]: JS WARNING: [/home/username/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/windowPreview.js 468]: reference to undefined property this._stateChangedI
> Jun 02 08:19:19 nuc gnome-shell[4091]: JS WARNING: [/home/username/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/taskbar.js 765]: reference to undefined property oldApps[oldIndex]
> Jun 02 08:19:18 nuc gnome-shell[4091]: WARNING: addSignalMethods is replacing existing [0x3a29e00 Gjs_ShowAppsIcon.dash-item-container] emit method
> Jun 02 08:19:18 nuc gnome-shell[4091]: WARNING: addSignalMethods is replacing existing [0x3a29e00 Gjs_ShowAppsIcon.dash-item-container] disconnect method
> Jun 02 08:19:18 nuc gnome-shell[4091]: WARNING: addSignalMethods is replacing existing [0x3a29e00 Gjs_ShowAppsIcon.dash-item-container] connect method

Up-to-date Arch Linux with GNOME 3.24.2 and Dash to panel 8.

**Comment by frandieguez** [comment]
Same here

**Comment by jderose9** [comment]
Thanks so much for the log. This one was already reporting in #92 so if you could subscribe to that thread for updates it would be appreciated. Thanks!
