### ISSUE TITLE
Number Overlays not visible in some themes

### ISSUE THREAD

**Issue by alex285** [jderose9/dash-to-panel#182]
thats on Flat Plat theme, & same behavior with Adapta some Adapta variants, but not all!

![screenshot from 2017-06-04 17-30-51](https://cloud.githubusercontent.com/assets/11244308/26762503/ec975bc0-494b-11e7-9eb3-b581dc28247c.png)

**Comment by bil-elmoussaoui** [comment]
It's due to this line of code https://github.com/jderose9/dash-to-panel/blob/4b7aafe9fb449d8a1d684bcb341d25f7b73b10e5/appIcons.js#L713
The background color is hardcoded. And also, few lines after there's no color attribute for text colors. it should be better to move that CSS stuff to stylesheet.css so themes can style them the way they want :)

**Comment by alex285** [comment]
@bil-elmoussaoui why not use custom colors that will just work? for example black background with white fonts color will work to all themes, or alternatively they can automatically get the background color from color from running indicator color and manipulate the font color -dark or light, depending the bakcground

**Comment by franglais125** [comment]
@alex285 we could have white text on black background by default, but doing it on css give you the chance to make it more customizable :)

I'm travalling now, but I can look at this later this week! Thanks for the feedback @bil-elmoussaoui !

**Comment by franglais125** [comment]
@alex285 I opened a PR to fix this! It would be great to have confirmation that it fixes the issue for you.

**Comment by alex285** [comment]
@franglais125 
>I opened a PR to fix this! It would be great to have confirmation that it fixes the issue for you.

worked! thank you!  

@jderose9 feel free to close it on merge!

**Comment by jderose9** [comment]
thanks y'all..
