### ISSUE TITLE
Locking the screen increases the Icon Margin until shell restart

### ISSUE THREAD

**Issue by TechnoSparks** [jderose9/dash-to-panel#183]
If a user locks the Gnome desktop and then unlocks it, the panel's "Icon margin" is increased (visually, not in the Settings) until a shell restart is triggered, which makes it return to the intended "Icon margin"

*After locking and then unlocking the screen*
![screenshot from 2017-06-06 11-59-15](https://cloud.githubusercontent.com/assets/6072210/26813367/31b066ce-4ab0-11e7-8798-c2b90867fd91.png)

_After shell restart_
![screenshot from 2017-06-06 11-59-50](https://cloud.githubusercontent.com/assets/6072210/26813376/436e8a26-4ab0-11e7-8303-e9510edac3a7.png)

My Icon margin setting is 1px. This also happens on any other settings as well.

**Comment by jderose9** [comment]
@TechnoSparks Thanks for reporting this! This one was actually reported on #85. I haven't been able to reproduce it though so if you have any more info to add to that issue, please do! Thanks.
