### ISSUE TITLE
Panel transparency

### ISSUE THREAD

**Issue by franglais125** [jderose9/dash-to-panel#185]
As you may know, Gnome 3.26 may ship with automatic panel transparency. I've worked on this for dash-to-dock (check the PR), but in a way this is done automatically for dash-to-panel, as it will (I assume) pick up the feature from upstream.

I haven't actually tried it, so I'm not sure... However, there might a be a small compatibility problem, as the transparency implementation upstream assumes the panel is at the top of the screen. Here is the commit:

https://git.gnome.org/browse/gnome-shell/commit/?id=447bf55e45b00426ed908b1b1035f472c2466956

@alex285 is this the case? How does dash-to-panel behave in Gnome 3.25 w.r.t. transparency?

This is not a problem yet, but I'm just trying to preemptively address it.

**Comment by jderose9** [comment]
Interesting. I'd really like to get multi-monitor support in soon, but the panel transparency thing is a concern for sure. I was assuming the best route would be to submit a PR to Dynamic Panel Transparency to include support specifically for Dash-to-Panel-created secondary panels, but native transparency throws another factor into the mix..

**Comment by franglais125** [comment]
Since I'll be stuck with Gnome 3.22 for a while (Debian Stretch here), I went ahead and backported the panel transparency code from upstream into an extension: https://github.com/franglais125/panel-transparency.

I've added a small check for the position of the panel so that it works with dash-to-panel when placed at the bottom. For now it's a workaround.

I'm not really planning on theming the extension (and I don't know if I'll submit it to e.g.o, as it will surely be short-lived), it's really just the upstream code, plus the usual enabling/disabling work. I mention this as the extension won't respect any theme applied to the panel.

**Comment by alex285** [comment]
@franglais125 this affects also themes! check on adwaita CSS

On Shell
https://git.gnome.org/browse/gnome-shell/commit/?id=447bf55e45b00426ed908b1b1035f472c2466956

On Shell CSS
https://git.gnome.org/browse/gnome-shell-sass/commit/?id=4c361179a1d45544dcbfbac209c1842aae171a01

**Comment by jderose9** [comment]
This was fixed by @franglais125 . Thanks!
