### ISSUE TITLE
Fedora: Window previews cause poor performance

### ISSUE THREAD

**Issue by Pointedstick** [jderose9/dash-to-panel#186]
Fedora 25 + GNOME (obviously :-p)

I've noticed that with window previews on, performance in all of GNOME shell perceptibly suffers. Turning off the option restores acceptable performance. This was also noticed and commented on here: http://www.dedoimedo.com/computers/gnome-3-dash-to-panel.html

**Comment by jderose9** [comment]
So you are saying that you are having performance issues even when the preview window is not being displayed, just by having it enabled?

**Comment by Pointedstick** [comment]
Correct.

**Comment by jderose9** [comment]
That's definitely odd.. most of the code to create the window previews actually still executes when they are disabled, they just don't get displayed. What sort of performance issues are you running into?

**Comment by Pointedstick** [comment]
Slow, jerky animations throughout GNOME shell.

**Comment by jderose9** [comment]
Do you mind to try the latest master and let me know if this persists? There have been some improvements to this code by @franglais125 .

**Comment by Pointedstick** [comment]
Sorry, I'm afraid I don't use GNOME anymore so I'm not in a position to test, but I believe you. Thanks for the improvements!

**Comment by vans163** [comment]
This might also be linked to Wayland.
