### ISSUE TITLE
show desktop button

### ISSUE THREAD

**Issue by MetaiR** [jderose9/dash-to-panel#189]
hello,

after suspend and relog in show desktop position back to left (I already set it on right).

I use Gno-Menu extension too. when change its settings, this problem happens again

**Comment by jderose9** [comment]
Could you please add a screenshot so I can better understand the problem? Thank you!

**Comment by yurividal** [comment]
I am having the same problem. Everytime i log out, or come back from sleep, the show desktop button is to the left of the Panel Menu. I use "Extended Panel Menu" extension.  check the screenshots 
![screenshot from 2017-07-06 10-17-34](https://user-images.githubusercontent.com/8555749/27904376-6ced21a0-6234-11e7-88a9-0dc906d0756b.png)
![screenshot from 2017-07-06 09-36-00](https://user-images.githubusercontent.com/8555749/27904378-6cf1090a-6234-11e7-847c-81143d4f14fa.png)
