### ISSUE TITLE
Non-Fullscreen Application Menu

### ISSUE THREAD

**Issue by kamulos** [jderose9/dash-to-panel#191]
Similar to the Windows/Plasma Application menu, I would prefer a small application menu that does not take the entire screen. There are a few extensions that have a popup application menu, but they do not integrate well with dash-to-panel and do not have the search function of modern gnome.

The cherry on top would be if it could be triggered using the super key.

**Comment by jderose9** [comment]
Thanks for the suggestion. I'm sorry but I think this is outside of the scope of this extension.

I would recommend looking at Gno-menu and Arc Menu as they do what you are looking for and should work well with this extension.

Also, I don't believe it is possible to override Super alone in Gnome/Wayland. But, you can bind (at least gno-menu) the menu to open with Super+another key such as Super+m.
