### ISSUE TITLE
Application icons show on the list with huge delay

### ISSUE THREAD

**Issue by darekdeo** [jderose9/dash-to-panel#194]
As described in the title, when opening new application the icon indicating that application is running is not displayed for huge amount of time (15-30 seconds). The issue happens to me always, but after some amount of time when session is running, which I believe will make it hard to reproduce during development/testing.

Steps to reproduce:
1. login to gnome desktop
2. open and close application, icon indicating that application is running shows fine
3. idle around 15-30 minutes or do your usual computer work
4. open new application, the window shows up but application icon isn't for long amount of time
5. when application icon shows up, close the program and see that application icon remains on the list for long time too

Running Ubuntu 16.04.2 LTS
Gnome shell is 3.18.5 (manually installed and replaced Unity, running now on gdm3)
Mesa 17.2.0 (oibaf ppa) on Intel Broadwell GT2 5500

On the side note, there is also issue with highlighting focused app, when running new app the icon is not highlighted until I hover mouse over the icon. (this might need separate issue, but maybe problem is linked?)

I've recorded video showing all above issues, in the video I am not doing anything for few seconds to actually wait through the mentioned delay (the second issue with not highlighting icon is visible in 12 second, sorry for not recording my mouse cursor): https://youtu.be/weeBdKeX93c

**Comment by darekdeo** [comment]
I've noticed the issue happend after less than 5 minutes after I bootem my laptop and edited extensions in gnome-tweak-tool.

I've disabled workspaces to dock extension which was installed after I've spotted the issue, so there is probably no conflict between some extensions, but maybe issue is related to editing extensions overall in gnome-tweak-tool?

I have rebooted my laptop again, did not run gnome-tweak-tool and so far I have no issue with app icons delay (but focused app is still not highlighted until I hover mouse cursor on its icon). I will not open gnome-tweak-tool during few next sessions and see if that's the issue.

Am I the only one affected by this problem?

**Comment by darekdeo** [comment]
gnome-tweak-tool was not the issue this time, but simply going to system settings made the problem. Maybe it was just coincidence, changed only output device and wallpaper. Any clues why this happens?

**Comment by jderose9** [comment]
Thanks so much for the detailed description and video. This one has already been reported in #96. Unfortunately I haven't been able to reproduce it yet, but please subscribe to that issue for updates and any additional info you may be able to add. Thanks!
