### ISSUE TITLE
Fine-Tune settings tab panel missing top margin

### ISSUE THREAD

**Issue by darekdeo** [jderose9/dash-to-panel#196]
This is extremely tiny issue, I've noticed top panel in Fine-Tune tab settings is missing top margin. Other tabs and panels are fine.

bad: ![bad](http://i.imgur.com/KSbonIM.png)
good: ![good](http://i.imgur.com/9mzrOza.png)

**Comment by jderose9** [comment]
Thanks for reporting! This was actually fixed already in #112, but it hasn't been released to extensions.gnome.org quite yet.
