### ISSUE TITLE
Remove clock from panel - feature request

### ISSUE THREAD

**Issue by sudo-gedit** [jderose9/dash-to-panel#199]
Good day,
I would be very happy about two functions.

1. I would be glad if you can remove the clock.
2. Even better I would find that, if one could remove the popup (calendar) from the clock. The watch should not offer any interactions.

Of course these are only options that can be switched on and off in the menu.

Thanks for the development and the effort. This is a very nice extension !!!

I am sorry for my english.

**Comment by bios-ben** [comment]
I've bundled this with "dash to panel" extension and if the clock could be removed from here, these two would just be perfect together.

**Comment by jderose9** [comment]
@sudo-gedit I think having another option in the clock position drop down to hide the clock makes sense. I don't understand the value in making it non-clickable though? Could you just not click it or does it cause some otherproblem?

@bios-ben you've posted in a "dash to panel" issue so I'm not sure which other extension you are referring to?

Thanks!

**Comment by bios-ben** [comment]
@jderose9 I apologize I meant I bundled "dash to panel" with "extend panel menu" which provides a clock already.

**Comment by sudo-gedit** [comment]
Do not click on the clock is a solution. :)
But unfortunately the computer of my parents and grandparents in the employment and these sheep it not always directly the right field to meet.


Please see this picture:
http://imgur.com/a/wNaXB

Furthermore, I would as a last solution synonymous gladly the removal of the clock accept.

Please do not misunderstand. I only want this as an option.
Many Thanks


Image source:
http://www.webupd8.org/2017/01/dash-to-panel-is-cool-icon-taskbar-for.html

**Comment by jderose9** [comment]
I think you won't be able to access your notifications any longer. Is that a concern?

**Comment by bios-ben** [comment]
Nope, the extend to panel makes a standalone notification icon, so maybe it won't break it? Check it out and see what it does as there's some overlap in what you're doing. https://github.com/julio641742/extend-panel-menu

**Comment by jderose9** [comment]
@bios-ben it seems that the author of that extension intends for it to work automatically with dash-to-panel, but it only looks for the clock in the panel _centerBox container. So I think it should work as long as you have the clock in the "Natural" position. The author may wish to update the extension to check the _rightBox container as well.

I don't think @sudo-gedit is using the "extend panel menu" extension. I can understand not wanting the clock to be visible but if it removes access to the notifications then removing seems like it would cause a new problem.

**Comment by jderose9** [comment]
This is going to need to be resolved on the "extend panel menu" side, as there are other extensions which relocate the clock, and it is assuming that the clock is in the _centerBox only. I think it's probably a bad idea to offer a way to hide the clock within this extension as notifications will then be inaccessible.
