### ISSUE TITLE
Integrate AppMenu into launcher

### ISSUE THREAD

**Issue by robrobinbin** [jderose9/dash-to-panel#2]
In my option GNOME 3 had many design flaws, but through the years many of these were solved. However one of the last things still bugging me is the AppMenu. 

I don't like the menu on the panel, but I hate the fall back mode as a colourful, out-of-place icon on the window itself even more. I tweaked your extension to add the menu back to the panel, in the right container where it doesn't bother me too much, and I'm quite happy with that.

![afbeelding](https://cloud.githubusercontent.com/assets/8597693/21741225/9f7bae9a-d4cf-11e6-8114-1cb2a8d4833c.png)

I was wondering however if it is possible to integrate the items of the AppMenu in the right-click menu of the launcher. This would be a more optimal solution, in my opinion.

![afbeelding](https://cloud.githubusercontent.com/assets/8597693/21741266/35f3261e-d4d0-11e6-8d45-ed022149226e.png)

What do you think? Do you think this is possible?

**Comment by jderose9** [comment]
Yes, I find the app menu frustrating too.

I really like the idea to move it to the right side! I had not thought of that, but it looks nice. Do you mind to share your technique or code? I could add it as a new config setting. Did you just remove the element from the _leftBox and add it to the _centerBox/_rightBox? I did notice that, for example, openWeather aggressively tries to set itself make as the leftmost item so it may be hard to position it at the left of the right side items consistently if using another extension that tries to do the same.

I did have the same idea about adding to the secondary menu (right click menu) but hadn't looked into it much yet. My first thought was just to tie into the same event that the gnome shell is using to add it to the top bar. However, that menu is only present for the focused window. I started thinking most people would expect every gnome application to have the menu available on right click whether that application was in the foreground or background - do you agree? I was worried that each instance of an application that was running would have its own instance of the menu and that it would need to be presented multiple times (once for each instance). But, after looking more carefully, I can't seem to find any applications that have menus that are contextual only for the running instance. For example, Cheese has a full screen option, and Calendar has an Add to Calendar button, but gnome will only let you start a single instance of these applications at a time. Files has a checkbox to hide the sidebar, but when you check it in one instance, it hides the sidebar on all other running instances too.

I guess this is a lot of rambling to say that I think it is feasible, but I need to look into it more. If you learn anything new, please share.

**Comment by robrobinbin** [comment]
Yup, I just moved the element to the _rightBox. It would be nice if there a config setting to do so.

We seem to be on the same frequency:

>  I started thinking most people would expect every gnome application to have the menu available on right click whether that application was in the foreground or background - do you agree?

I do.

>  But, after looking more carefully, I can't seem to find any applications that have menus that are contextual only for the running instance.

I don't know how the implementation is done, but I think the design idea is indeed that the AppMenu is for the application as a whole, not for a specific instance.

I have limited knowledge about gnome extensions, so I don't think I'll be of much use, but if I do find something interesting, I'll let you know.

**Comment by jderose9** [comment]
> I don't know how the implementation is done, but I think the design idea is indeed that the AppMenu is for the application as a whole, not for a specific instance.

Nice, good to know. I think that makes it more feasible, but I haven't look through the shell code at the implementation yet. I'm new to Gnome.. working on this extension was pretty much a pre-requisite to switching over to using it, haha. The Overview, and the Workspaces-To-Dock extension really sold me on it though. They really make using multiple workspaces painless in a way I haven't seen on any other desktop environment.

**Comment by eldelacajita** [comment]
I totally agree with the suggestion by @robrobinbin of integrating the appmenu in the same right-click menu present in the launcher icons (and working per app, as they are usually general options not affecting a specific window).

**Comment by cra0zy** [comment]
@robrobinbin What shell theme are you using?

**Comment by robrobinbin** [comment]
@cra0zy In the screenshot I was using [Flat-Plat](https://github.com/nana-4/Flat-Plat)-Conpact. Now I'm using [Arc](https://github.com/horst3180/arc-theme) though

**Comment by Pointedstick** [comment]
Another vote for integrating the AppMenu into the running app's own menu.

**Comment by robrobinbin** [comment]
It would definitely be nice, but does anybody have a clue/the ability to do so?

**Comment by 92Julian** [comment]
Add a option to show the AppMenu in the "Click action" preference and set it default behavior for shift+click or middle-click action. Left-click = cycle windows + minimize; right-click = right-click menu; shift+click = AppMenu.

**Comment by heftig** [comment]
Please find some interim solution ASAP (even if it's just restoring the menu in the panel). I'd really consider this a bug and not an enhancement.

Apps depending on the menu being accessible are currently unusable. Attempting to open the menu using Super+F10 pops up an unclickable menu in the top-left corner.

**Comment by jderose9** [comment]
@heftig There is an option to add the menu back to the panel in the current master branch thanks to @robrobinbin. It's awaiting Gnome approval (v4 here: https://extensions.gnome.org/review/6566) to go live but you can grab it from github if you don't want to wait.

The other option is to turn off the menu from Tweak Tool under Top Bar > Show Application Menu. That seems to disable Super+F10 but will give you access to the menu in the top left of each application window.

**Comment by jderose9** [comment]
Ok. I think I got this in pretty good shape. The gnome AppMenu items are now merged into the right click menu.

Couple things to note:
1. The menu items aren't available unless the app is currently running.
2. If you have the AppMenu displayed on the panel, Super+F10 will still open it, but if you don't it will be remapped to open the right click menu from the launcher.
3. I removed Help and About from the AppMenu items and Show Details (which opens the app in Gnome Software) from the launcher items, to try to cut down on the amount of stuff in the popup. Let me know what you think of this.
4. Previously the order was Window List, New Window, Favorite, Quit. Now the order is Window List, New Window, AppMenu items, Favorite Quit. Let me know if this makes sense.

![appmenu](https://cloud.githubusercontent.com/assets/2118702/23327844/b936190a-fae1-11e6-83f2-7dd0a064bbcb.png)

**Comment by robrobinbin** [comment]
You're doing amazing stuff, this looks great! (The changes to the indicators look great to!)

1. No problem, the flow feels natural.

2. Nice

3. I don't like the idea of removing functionality, however it does look neater and more integrated with these items removed, so 👍. For some reason however this doesn't completely work on my machine (with Dutch locale): "New window" and "Quit" are removed, "Help" and "About" are not (all are different words in Dutch)

4. Makes sense!

**Comment by cra0zy** [comment]
> I removed Help and About from the AppMenu items and Show Details (which opens the app in Gnome Software) from the launcher items, to try to cut down on the amount of stuff in the popup. Let me know what you think of this.

Add an option to remove the items, but don't remove them by default.

**Comment by robrobinbin** [comment]
Locking and unlocking GNOME crashes the extension now

**Comment by jderose9** [comment]
@robrobinbin This is fixed now. Let me know if you discover any other issues. Thanks.

> For some reason however this doesn't completely work on my machine (with Dutch locale): "New window" and "Quit" are removed, "Help" and "About" are not (all are different words in Dutch)

It looks like Help and About are not translated in the shell. These menu items are added from each application and I can't access the translations. They are handled individually by the apps on the C side and I can't find any other generic way to identify them.

So I think it makes the most sense just to put them back in the menu. I moved the appMenu items to the top of the right click menu, because I felt that New Window and the window list were probably used more frequently, and because I didn't like that the New Window moved so far north when the application was running versus when it was not. What are your thoughts?

![screenshot from 2017-02-25 20-05-24](https://cloud.githubusercontent.com/assets/2118702/23336194/a0fdeea2-fb96-11e6-8fc2-f394580e0e74.png)

**Comment by Pointedstick** [comment]
I like it.

**Comment by robrobinbin** [comment]
Everything seems to work! Feel free to close this issue. 🎉 

You might consider removing #29 again, since this is a more elegant solution to the appMenu problem.

Cheers

**Comment by jderose9** [comment]
I'll leave #29 as it's a pretty straightforward implementation and gives some additional customization options. Thanks for the input everyone!

**Comment by virtualviolet** [comment]
hey guys, I am finding the quit menu option is not appearing when the app menu is merged with the dock icon
