### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [jderose9/dash-to-panel#204]
As we all know, today more than ever before, it is crucial to be able to trust
our computing environments. One of the main difficulties that package
maintainers of Linux distributions face, is the difficulty to verify the
authenticity and the integrity of the source code.

The Arch Linux team would appreciate it if you would provide us GPG signatures
in order to verify easily and quickly your source code releases.

**Overview of the required tasks:**
* Create and/or use a 4096-bit RSA keypair for the file signing.
* Keep your key secret, use a strong unique passphrase for the key.
* Upload the public key to a key server and publish the full fingerprint.
* Sign every new git commit and tag.
* Create signed compressed (xz --best) release archives
* Upload a strong message digest (sha512) of the archive
* Configure https for your download server

[GPGit](https://github.com/NicoHood/gpgit) is meant to bring GPG to the masses.
It is not only a Pythonl script that automates the process of creating new signed
git releases with GPG but also comes with this step-by-step readme guide for
learning how to use GPG.

**Additional Information:**
* https://github.com/NicoHood/gpgit
* https://help.github.com/categories/gpg/
* https://wiki.archlinux.org/index.php/GnuPG
* https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
* https://www.qubes-os.org/doc/verifying-signatures/
* https://lkml.org/lkml/2016/8/15/445
* https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https
* https://www.enigmail.net/index.php/en/

Thanks in advance.

**Comment by NicoHood** [comment]
@jderose9 Are you serious? This is a real security problem for your users. Please rethink this decision. I assume you accidentally closed this issue.

**Comment by jderose9** [comment]
Sorry, but this sounded like spam advertising your project.

I'm not opposed to signing tags, though I don't think this will help the average user. They install from extensions.gnome.org which alters my submission and doesn't validate keys on submission or sign the results.

I'm not an arch user so you will have to educate me. AFAIK the code in this repository is being re-package before it enters the AUR. How can I deliver a signed release directly to the user via AUR? Is this documented somewhere as I can't find anything about it?

**Comment by NicoHood** [comment]
@jderose9 Sure I will explain to you :)

You are correct that lots of users get your extension from gnome directly. We cannot help those users, sadly. This is something gnome has to do.

However there are other ways to install your extension directly inside the OS for all users. The AUR package can be found here:
https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-panel/

Every user will download the source of your extension from github and build a package from it. However if the download got tampered (because something on the git server side got hacked), the user cannot ensure he gets the right software. And just any piece of software with the correct systemd file in place can hack your system. And thats just an example.

To ensure the security of your users, and also yourself you can digitally sign your software with gpg. This way users can verify the source and be sure it is the exact same software you published. This process is of course automated by archlinux tools.

Furthermore if a package is popular enough, it is possible to move the package from the user repository (AUR) to [community]. Packagers like me can do that. However we are responsible for lots of users, so I personally avoid releasing packages where I cannot verify the authenticity. So if you gpg sign your software you will a) make the package secure for its users and b) also show to others that you care about security, which is important nowadays.

Now if you decide to use gpg signatures, my advertise comes into place. It is just a suggestion, you can learn gpg totally on your own. The goal of the project is to tell peope what is actually required and good to use (because many dont know) and they also want to get started fast. So gpgit ships everything required for a developer to get started with gpg source signing: A Guide and a script. Feel free to use it.

So after all its up to you, but I hope I could give you some more useful details on source code signing. Feel free to ask further questions if you need assistance :)

~Nico

**Comment by jderose9** [comment]
Yes, I understand.. But how does an AUR user validate the release I signed made it to their system when it has been re-packaged?

**Comment by NicoHood** [comment]
How do you mean by "repackage"?

AUR users download the PKGBUILD file. This contains metadata, build instructions and of course the download url. They download the .tar.gz file along with its signature and validate it (makepkg does it automatically).

**Comment by jderose9** [comment]
Ahhhhh ok, so the PKGBUILD is used to build on the users system from the archive I provide? Makes sense now. I assumed arch package manager worked like Fedora, opensuse, debian, etc where the build occurred on a server and the output was delivered to the user.

Out of curioisty, how does an arch user fetch my key? Do they fetch that manually? And if not how do they know that it hasn't been changed during the automated delivery?

**Comment by NicoHood** [comment]
In this case no, as users need to build packages on their own. But in both cases GPG signatures would secure the build process.
