### ISSUE TITLE
Show toppanel on the toppest level

### ISSUE THREAD

**Issue by colben** [jderose9/dash-to-panel#206]
Can the toppanel show on the toppest level like "dash-to-dock" ?
I offen run win7 in vbox with full screen, and the the "dash-to-dock" panel can slide out when I move mouse to the left border of screen.
[here is the picture](http://i4.piimg.com/600088/c6c354773699a058.png)
with "hide-top-bar", the top panel can not show out when I move mouse to the top border of screen, can you fix this issue of "hide-top-bar" ?

**Comment by jderose9** [comment]
Hi. I'm a little unclear as to what the problem is. Did you mean to post this on the issues for Hide-Top-Bar? This extension (dash-to-panel) doesn't currently provide any autohiding capability, though it is proposed in #41.

**Comment by SolarLiner** [comment]
Fullscreen covers the panel regardless of any intellihide option. The feature request here is to be able to put Dash to Panel on top of those fullscreen applications.
