### ISSUE TITLE
Lag with icons and disappearing favourites with latest version

### ISSUE THREAD

**Issue by IsaakGroepT** [jderose9/dash-to-panel#207]
There are two things with the favourites on the panel, which both have the same root casue I think.

First of all, when my monitor is powered off (energy saving setting in GDM) and back on, the icons disappear from the panel. Clicking on the spots were they were doesn't do anything, so it's not like they are just now shown but are active. They will reappear again after soem time (10+ seconds?)

Another thing is that there is a lag with the icons of running applications overall. It takes over ten seconds for the icons to appear and disappear after closing the application.

**Comment by jderose9** [comment]
Thanks for reporting this. Was this working prior to updating to v9?

**Comment by IsaakGroepT** [comment]
It's was working flawless before the last update. I have to add that the lag only happens to new icons that appear on the panel. The When I open a favourite application, the extra visual is added directly to the icon

**Comment by JoeHonk** [comment]
I noticed this problem. After disabling Gno-menu and Kstatusnotifieritem/appindicator support and logging out/in, the lag is resolved, though I don't know if/which extension may have been contributing to the issue.

**Comment by T-ii** [comment]
I'm not sure if I'm having the same issues, but I've only had this happen once to me.

Any apps I had assigned to favorites randomly vanish and rotate around. Even if I have for example Firefox running, it won't show in the panel. Going into tweak tool and turning Dash to Panel off and on solved the problem.

**Comment by nooryani84** [comment]
**Ubuntu Gnome 17.04 in VMware Workstation 12 Player**
I'm able to reproduce it quickly if change the "App Icon Margin" back and forth.

**Fedora Workstation 26 in VMware Workstation 12 Player**
Issue is not present in either Xorg or Wayland sessions.

**Comment by nicholashoule** [comment]
I'm experiencing this issue.

```
Fedora release 26 (Twenty Six)
VERSION="26 (Workstation Edition)"
```

```
gnome-shell-extension-apps-menu-3.24.3-1.fc26.noarch
gnome-clocks-3.24.0-1.fc26.x86_64
gnome-screenshot-3.22.0-2.fc26.x86_64
gnome-online-miners-3.22.0-2.fc26.x86_64
gnome-user-docs-3.24.2-1.fc26.noarch
gnome-boxes-3.24.0-3.fc26.x86_64
gnome-keyring-pam-3.20.1-1.fc26.x86_64
gnome-menus-3.13.3-6.fc26.x86_64
gnome-bluetooth-libs-3.20.1-1.fc26.x86_64
gnome-tweak-tool-3.24.1-2.fc26.noarch
gnome-online-accounts-3.24.1-1.fc26.x86_64
libgnome-games-support-1.2.2-1.fc26.x86_64
gnome-shell-theme-selene-3.4.0-12.fc26.noarch
gnome-color-manager-3.24.0-1.fc26.x86_64
gnome-shell-extension-background-logo-3.24.0-1.fc26.noarch
gnome-settings-daemon-3.24.3-2.fc26.x86_64
gnome-terminal-3.24.2-1.fc26.x86_64
gnome-desktop3-3.24.2-1.fc26.x86_64
gnome-calculator-3.24.0-1.fc26.x86_64
gnome-getting-started-docs-3.24.1-1.fc26.noarch
gnome-battery-bench-3.15.4-5.fc26.x86_64
gnome-abrt-1.2.5-4.fc26.x86_64
gnome-disk-utility-3.24.1-1.fc26.x86_64
qgnomeplatform-0.3-1.fc26.x86_64
gnome-shell-extension-launch-new-instance-3.24.3-1.fc26.noarch
gnome-keyring-3.20.1-1.fc26.x86_64
gnome-screensaver-3.6.1-16.fc26.x86_64
gnome-weather-3.24.0-1.fc26.noarch
gnome-backgrounds-extras-3.24.0-3.fc26.noarch
gnome-2048-3.22.0-2.fc26.x86_64
gnome-shell-extension-user-theme-3.24.3-1.fc26.noarch
gnome-font-viewer-3.24.0-2.fc26.x86_64
gnome-themes-standard-3.22.3-2.fc26.x86_64
gnome-characters-3.24.0-1.fc26.x86_64
gnome-video-effects-0.4.3-1.fc26.noarch
gnome-shell-extension-alternate-tab-3.24.3-1.fc26.noarch
gnome-initial-setup-3.24.2-1.fc26.x86_64
gnome-system-monitor-3.24.0-1.fc26.x86_64
gnome-shell-3.24.3-1.fc26.x86_64
gnome-shell-extension-places-menu-3.24.3-1.fc26.noarch
gnome-logs-3.24.2-1.fc26.x86_64
gnome-software-3.24.3-1.fc26.x86_64
gnome-bluetooth-3.20.1-1.fc26.x86_64
NetworkManager-openvpn-gnome-1.2.10-1.fc26.x86_64
gnome-session-xsession-3.24.1-2.fc26.x86_64
gnome-contacts-3.22.1-4.fc26.x86_64
gnome-session-3.24.1-2.fc26.x86_64
gnome-calendar-3.24.3-1.fc26.x86_64
polkit-gnome-0.105-11.fc26.x86_64
gnome-maps-3.24.3-1.fc26.x86_64
gnome-autoar-0.2.2-1.fc26.x86_64
gnome-shell-extension-window-list-3.24.3-1.fc26.noarch
gnome-backgrounds-3.24.0-3.fc26.noarch
fros-gnome-1.1-12.fc26.noarch
gnome-documents-3.24.3-1.fc26.x86_64
gnome-classic-session-3.24.3-1.fc26.noarch
gnome-user-share-3.18.3-2.fc26.x86_64
gnome-session-wayland-session-3.24.1-2.fc26.x86_64
pinentry-gnome3-0.9.7-3.fc26.x86_64
gnome-shell-extension-common-3.24.3-1.fc26.noarch
libgnomekbd-3.22.0.1-2.fc26.x86_64
```

**Comment by jderose9** [comment]
Do you mind to try latest `master`? Thanks!

**Comment by minyc510** [comment]
I also have this issue, if I installed dash-to-panel through [this link](https://extensions.gnome.org/extension/1160/dash-to-panel/) is that trying the latest master? If not how do I go about installing the master?

Thanks!

**Comment by jderose9** [comment]
@minyc510 No, you will need to download the latest from github and then run `make install`. Here's some instructions: https://github.com/jderose9/dash-to-panel/wiki/Installation#installation-from-github

Thanks!

**Comment by minyc510** [comment]
**Installing from master has seemed to fix the issue!**

The only icon-lag I have noticed: if Atom (the text editor) is not a favorite, and I open it, it will take a while to show up on the dash. However I think this has to do with the fact Atom has such a slow boot-up time, not an issue with this extension. Thanks for the quick response @jderose9

**Comment by charlesg99** [comment]
@minyc510 Normally, the icon should appear on the taskbar at the same time as the application window appears on screen. Is this what you're seeing with Atom?

**Comment by jderose9** [comment]
Glad this is resolved! Thanks everyone for your help.
