### ISSUE TITLE
Ungroup Applications on TaskBar Panel?

### ISSUE THREAD

**Issue by Bindea** [jderose9/dash-to-panel#208]
github.com/zpydr/gnome-shell-extension-taskbar

Like the taskbar addon above would it be possible to ungroup applications so they have a separate individual icons showing on the panel like a classic taskbar instead of having a single icon with everything grouped together?

For example the default gnome setting for having all Firefox windows in one tab and having to scroll through them is highly annoying and would make life a lot easier if you could just run across the bottom panel with your mouse and preview each one like Windows or Mint?

Then your extension would be 100% perfect for me. :)  

Thanks

**Comment by jderose9** [comment]
Just to make sure I understand- this isn't specific to Firefox, right? You just want to be able to have multiple instances of an application have separate icons on the taskbar? Thanks!

**Comment by Bindea** [comment]
Thanks  jderose9 you are correct , Multiple instances of an application to have separate icons on the taskbar instead of being grouped together.

Sorry to confuse things , lucky you understood what i meant so i've changed the topic. :)

**Comment by Bindea** [comment]
Any thoughts on this jderose9 ?

**Comment by jderose9** [comment]
I think that sounds like a good idea..

**Comment by skullscream** [comment]
Don't make it a default thing please. I ran across this in budgie's taskbar and it was awful for me.

**Comment by Bindea** [comment]
@jderose9  , Thank you for the consideration.

@skullscream , Yeah optional just for those that don't like the default grouping.

**Comment by voidray** [comment]
If this would be implemented it would remove one of the last points that keeps me from switching to linux. In Windows you can set the taskbar so it doesn't group. All the windows of an application are beside each other. In Windows the taskbar also has the title of the Window which is really helpful if you have multiple Writer documents open for example. 
Speaking of Writer: When I open multiple Writer windows it doesn't get stacked but there are separate icons in the taskbar. Since they have no title it is not helpful that way however. Another difference to Windows is that the Icons are separate from the application icon (they are on the right if the favorites bar)

**Comment by Bindea** [comment]
@jderose9

Did you look into this at all to see if it can be done?

Thanks

**Comment by btm6084** [comment]
This enhancement would make me soooo happy.

**Comment by jderose9** [comment]
I'm not clear how multiple icons for the same application are differentiated? Is the expectation that the open windows will be labeled? (As requested in #115)

Are icons displayed in the order they were launched or grouped together with other instances of the same application?

If I open two instances of an application that exists in my favorites, does one of them go after the favorites and the other re-uses the pinned favorite icon?

**Comment by MacHouw** [comment]
HUH! - headscratch

The same as Bindea requested of having a classic task bar like the gnome shell extension he/she posted , The same as Windows or Linux Mint task bar when ungrouped.

Open 10 Firefox windows and then you get 10 separate firefox icons on the task bar panel or the same with anything else , open 10 command prompts or terminals and get 10 separate icons along the task bar with hover preview for only the icon you select.

Having a single Firefox icon on the task bar with every firefox grouped inside is a pain in the ass for stock brokers as we like to have our stock and web tools separated with quick click select or hover preview on the taskbar for charts when the market moves.

Mint doesn't group and windows 8/10 has an ungroup option so it would be nice if we could have the same with the best gnome addons dash to panel and arc menu. :)

**Comment by Bindea** [comment]
Mint taskbar

linuxmint.com/tmp/blog/1851/linuxmint12-preview.png

You can see just right of centre that Clem the developer has 2 terminal windows open and they are separate on the panel rather than being grouped together into a single panel icon.

You can see what every application is doing by hovering your mouse across the task bar with a single preview for each rather than a preview of all in a group.

Maybe you could load up Linux Mint in a Virtual Box and open loads of FireFox windows so you can see how it looks when they are not grouped together.

**Comment by lexruee** [comment]
@Bindea 
I guess what you want is something that behaves like the window-list extension:
https://extensions.gnome.org/extension/25/window-list/

**Comment by Bindea** [comment]
@lexruee 

I've not tried that extension and the user comments says errors so the code must be out of date , so i don't know if it acts like a normal task bar.

This extension called TaskBar acts like a normal task bar without groups
https://extensions.gnome.org/extension/584/taskbar/

So for example If click the Firefox launch icon 3 times then you will be shown 3 separate firefox icons for each website on the taskbar.

**Comment by Bindea** [comment]
Can anyone else that is interested in this do a better job of explaining a standard panel taskbar without grouping as i'm not technically minded and i might be making this more confusing than it needs to be plus i have a lot going on here that i might not be active for a couple of weeks.

Thanks

**Comment by jderose9** [comment]
Ok, for now let's assume this work order is for allowing multiple instances of icons and is a pre-requisite for #115 to allow titles to be added to those ungrouped icons.

**Comment by Bindea** [comment]
Don't know about anyone else but i'm equally happy with either Icons or Windows on the taskbar to separate applications  , apart from the visual aspect does it make any difference to how it might function that i might not be understanding correctly?

As long things are not grouped together i think i can live whatever you think is best  , i trust your judgement as everything else about dash to panel looks great.  😃 👍 

Thank you kindly for tagging this as approved.

**Comment by Bindea** [comment]
Come to think of it square window type indicators along the taskbar would be better to differentiate running applications from the favourites on the left otherwise it would need a defined gap or separator bar which could look ugly.

**Comment by mateusclopes** [comment]
That would be very good

**Comment by Tkachov** [comment]
I kinda moved to Ubuntu on my laptop recently and spend a lot of time customizing it so it would be as comfortable for me as Windows. This extension was very helpful, but the described feature is the last missing piece.

To answer jderose9's questions about how exactly that works with multiple instances of the same application, I've decided to look how it works in Windows. First of all, yes, "Never combine" mode automatically leads to showing labels.

No applications launched, only favorites shown:
![0_closed](https://user-images.githubusercontent.com/1948111/32493308-8e6050ae-c3e7-11e7-8831-5f7a59a287c1.png)

Two Firefox windows launched and one non-favorite application:
![1_open](https://user-images.githubusercontent.com/1948111/32493309-8e86d1fc-c3e7-11e7-9564-037c58cf548f.png)

Lots of applications launched:
![2_lots](https://user-images.githubusercontent.com/1948111/32493310-8eaa75c6-c3e7-11e7-8c38-cae55f82b740.png)

So, non-favorite application icons are shown in order they were launched (though still grouped by application, like if you launch Paint-VirtualBox-Paint, they would be grouped as Paint-Paint, then VirtualBox).

Launched favorite applications reuse pinned icon and then other instances go right near it (not after all the favorites).

Finally, if there are a lot of applications launched, labels widths are automatically decreased to fit all. When there are too much applications running, it just shows multiple icons to indicate multiple instances, but does not show label near it. If even icons do not fit in one line, it shows a small up and down buttons.

Icons+labels:
![0_apps](https://user-images.githubusercontent.com/1948111/32493317-94e8927e-c3e7-11e7-9475-54541db3a9d3.png)

Too much Firefox:
![1_lots](https://user-images.githubusercontent.com/1948111/32493318-950d0582-c3e7-11e7-99f9-ee052ba4380a.png)

Up/down buttons (1):
![2_arrows_1](https://user-images.githubusercontent.com/1948111/32493319-9533569c-c3e7-11e7-80aa-c5091d86f09d.png)

Up/down buttons (2):
![3_arrows_2](https://user-images.githubusercontent.com/1948111/32493320-955b55e8-c3e7-11e7-8df9-ef4632160273.png)

I think that the last two cases are quite rare, and I personally would be glad to have at least multiple icons (and then, icons + labels with autodecreasing width).

**Comment by btm6084** [comment]
Yessss. This is what I'd like.

**Comment by voidray** [comment]
@Tkachov thanks for the screenshots. Just to clarify, you have multiple instances of firefox open in those examples, not one firefox instance with multiple tabs, correct? That's how I know it from Windows 7 to 8.1

**Comment by Tkachov** [comment]
@voidray, yes, those are different windows, and each of them could contain a lot of tabs. As a matter of fact, I've never seen a browser which shows its tabs as separate panel items (and I hope I never will).

**Comment by voidray** [comment]
@Tkachov, yes, I just wanted to make it 100% clear to everyone who sees the screenshots, because in the discussions here I got the impression that for some it was not clear how the result should look like.

**Comment by charlesg99** [comment]
New year's resolution! I started working on this issue because, since I moved to Linux a year ago, I still shamelessly miss some of the windows 7 taskbar features. 

Stuff in the oven (while trying not to break the existing):

1. Ungrouping the application instances, keeping them grouped by application.
2. Setting to merge application launchers with the running applications, or keep them separate.
3. Setting to customise the font size of the application titles.
4. Setting to customise the width of the application titles.
5. Setting to customise if the application titles should all have the same width or not (if some application titles are smaller than the defined width, they wouldn't extend and waste space).
6. Shrinking the application titles when many instances are running. If too many icons need to be displayed, use the current extension's scrollview.

Anyone's wishlist not met? Any unneeded features in my list?

**Comment by Bindea** [comment]
@charlesg99 

WOW , this is amazing as i was starting to think it would never happen or wasn't possible. :)

This will make Dash to Panel the number one addon as loads of people have swapped Ubuntu over to Cinnamon but there will be no need now with this.

Thanks ever so much.

**Comment by IKrupaUA** [comment]
@charlesg99
Is it possible to add settings for: when ungrouped, do not display the window titles?

Grate work, thank you.

**Comment by charlesg99** [comment]
@IKrupaUA

I don't think I would add a dedicated setting to hide the window titles, but you could get the desired result with the current settings:

Setting the titles maximum width to 0:

![image](https://user-images.githubusercontent.com/33044886/35188211-84384184-fdff-11e7-8dc8-568e727547d7.png)



Which would result in this visual:

![image](https://user-images.githubusercontent.com/33044886/35188164-f4742e78-fdfe-11e7-87f1-98fc5e7c14ac.png)


Is this what you want? If so I'll just add this to the pull request.

**Comment by IKrupaUA** [comment]
@charlesg99 

Yes, that's exactly what i want, thank you!

**Comment by jderose9** [comment]
Thanks so much to @charlesg99 for completing this!

**Comment by spantaleev** [comment]
Great work!
Any chance this would soon make it into a new release available on GNOME Extensions?

**Comment by Bindea** [comment]
@jderose9 

@charlesg99 

It's been working great , thanks ever so much again as even the elders in my family now find it easy to use gnome without the confusion of groups.

I'm surprised this update hasn't been mentioned websites such as omgubuntu or phoronix. :)

**Comment by jderose9** [comment]
I'd like to add a screenshot to the README with this feature enabled. @LinxGem33 would you mind to take a quick one, or send me the vector mountain background you used for the other? I was thinking it could fit somewhere under the window previews gif.. Thanks!!

**Comment by LinxGem33** [comment]
@jderose9 
yeah sure just send me a screen shot of the dash to panel with the before and after,  with this feature enabled and ill make a nice screen with the background you requested.

p.s just the dash **dock** in png format.  👍

**Comment by V0idk** [comment]
well done

**Comment by thedonquixotic** [comment]
Hey designer here (not a full dev yet, so please bear with me). Just wanted to check and see if I understood a couple of things correctly. I'm coming to this from a google search. 

This extension is only for Gnome correct? I can not use this on Ubuntu correct? I have Ubuntu 16. I do remember hearing that Ubuntu is moving to Gnome Shell for 18 though so that means this extension might work for Ubuntu in the future?

**Comment by thedonquixotic** [comment]
@Tkachov Excellent. And installing the Gnome Shell won't like totally screw up my neural networks or anything right? It's just effecting the frontend of the OS right? Sorry if that's a silly question but I just want to make sure. One reason I'm not upgrading to 17 is because of the limited compatibility of the neural networks etc.

**Comment by Tkachov** [comment]
@thedonquixotic well, yeah, that's effecting the frontend. It changes not only look though, but also a feel part of it: IIRC, Gnome handles user input differently, has other keyboard shortcuts, etc.

You can install Gnome alongside Unity and switch between them through login screen, so if you won't like Gnome, you can just get back to Unity. Just make sure not to remove it while installing Gnome (I guess some instructions may include such step as cleaning up).

**Comment by thedonquixotic** [comment]
Thanks!  








On Tue, Mar 20, 2018 4:25 AM, Alexander notifications@github.com  wrote:
@thedonquixotic  well, yeah, that's effecting the frontend. It changes not only
look though, but also a feel part of it: IIRC, Gnome handles user input
differently, has other keyboard shortcuts, etc.

You can install Gnome alongside Unity and switch between them through login
screen, so if you won't like Gnome, you can just get back to Unity. Just make
sure not to remove it while installing Gnome (I guess some instructions may
include such step as cleaning up).

**Comment by fvrlak** [comment]
Had the same issue. Found a workaround and turned it into a small CLI tool:                                                                                                                                                                 
                                                                                                                                                                                                                                              
  https://github.com/fvrlak/gnome-taskbar-separator
                                                                                                                                                                                                                                              
  Creates vertical line separators between pinned app groups. Works on GNOME 46+, Zorin OS, Ubuntu.
