### ISSUE TITLE
Allow configuring icon size

### ISSUE THREAD

**Issue by marcoms** [jderose9/dash-to-panel#210]
Something that I miss from dash-to-dock is the option to change the application icon size, as personally the default size is quite big compared to the status icons to the right.

**Comment by kolyshkin** [comment]
Icon size is configurable, the option is called "panel size". I set it to 32 (default is 48) and the app icons look the same size as the the ones at the right side.

**Comment by marcoms** [comment]
I mean to have it independent of the panel size, so that there is more vertical padding

**Comment by jderose9** [comment]
Thanks for this! It was actually requested in #75 so you might want to jump over there and subscribe for updates.
