### ISSUE TITLE
Applications menu margin is not consistent

### ISSUE THREAD

**Issue by marcoms** [jderose9/dash-to-panel#211]
![screenshot from 2017-07-14 10-42-46](https://user-images.githubusercontent.com/4211302/28207356-53bfa77c-6881-11e7-8d94-02a665344542.png)

In the picture the margin has more horizontal padding than vertical padding, which makes it appear unbalanced.

**Comment by jderose9** [comment]
You can adjust the padding on this button by setting the padding style on the button in your theme's gnome shell CSS. Something like this:

```
#dashtopanelMainPanel .show-apps {
    padding: 2px;
}
```

One issue with the padding is that if it follows the app icon margin that in gets pushed too far from the screen edge unless the margin is very small. If the margin is removed and the Activities button or something is turned on to the left of it, it will get too cramped. I'm not totally opposed to having a user interface slider for this, though my initial thought is that it might be a little overboard and would prefer to find some way for it to "just work" in a natural way. Any ideas?
