### ISSUE TITLE
[Feature request] New functions and settings Ideas.. Hope you like!

### ISSUE THREAD

**Issue by Warmuser** [jderose9/dash-to-panel#214]
Hello, I want to request and give ideas to some new useful functions and settings for these fantastic extension. I hope some of these will be considered. :)

- Settings to positionate the Panel on left/right of the screen.
- Settings to adjust the dimension of the thumbnail previews.
- Setting to change the default App Button (ORB) Icon.
- Setting to add a Tray Icons menu (similar ms windows).
- Setting to auto hide the panel or become bottom of the active windows (maxized/half-maximized)
- Setting to hide the panel when the GNOME App Launcher is opened.
- Setting to add a Search panel built in the Horizontal bar.
- Possibility to add the AppFolders to the Panel as a dock.
- Function to automatically positionate a Window when the cursor is on the preview thumbnail.

**Comment by jderose9** [comment]
Thanks so much for the feedback! You have a lot of great ideas, but indeed many of them have been submitted already.

> Settings to positionate the Panel on left/right of the screen.
This isn't possible, AFAIK..
https://github.com/jderose9/dash-to-panel/issues/3#issuecomment-271155455

> Settings to adjust the dimension of the thumbnail previews.
#27 

> Setting to change the default App Button (ORB) Icon.
#43

> Setting to add a Tray Icons menu (similar ms windows).
#161 

> Setting to auto hide the panel or become bottom of the active windows (maxized/half-maximized)
#41

> Setting to hide the panel when the GNOME App Launcher is opened.
I'm on the fence about this one. I think this has a lot of downstream side effects. There will be no way to close the app launcher or pin an application to the bar from the application list. The drag-and-drop currently depends on hovering over the panel.

> Setting to add a Search panel built in the Horizontal bar.
Love it, but I think this needs to go in its own extension as it useful without dash-to-panel. There's a few extensions already in the store that do this though I haven't gone through to see if they are all still supported on the latest gnome versions. Are you looking to search the web or the local device?

> Possibility to add the AppFolders to the Panel as a dock.
#117

> Function to automatically positionate a Window when the cursor is on the preview thumbnail.
I don't think I understand what you mean by this.

Thanks again.

**Comment by Warmuser** [comment]
I'm sorry, for the duplicate requests. Damn, anyway the "Function to automatically positionate a Window when the cursor is on the preview thumbnail. " Is intended like in these picture: https://i.imgbox.com/l9iZ4OE5.png

**Comment by jderose9** [comment]
No problem!

I'm sorry but I still don't understand. You want the window to move if the thumbnail is covering your view of it?

**Comment by Warmuser** [comment]
Nope, I mean to preview and expose the window when the mouse hover the thumbnail/favourite icon on the panel. :)

**Comment by jderose9** [comment]
Oh, yes this should be available already in the most recent version (v9) released a couple of weeks ago. Make sure "Window Peeking" is on in the settings.
