### ISSUE TITLE
Animation when launching an application from panel.

### ISSUE THREAD

**Issue by skullscream** [jderose9/dash-to-panel#217]
It would be nice to add a simple animation when you click on an icon to launch the application. Like plank has for example. Just a suggestion.

**Comment by Bindea** [comment]
> Startup notification
https://developer.gnome.org/integration-guide/stable/startup-notification.html.en

Do you mean like a tiny spinning disk to let you know it's loading?

**Comment by jderose9** [comment]
There's an exploding launch animation already coming from the icon (it is default behavior of Gnome).
