### ISSUE TITLE
VirtualBox window preview code causing errors in Gnome Shell 3.18

### ISSUE THREAD

**Issue by thomasstevenson** [jderose9/dash-to-panel#224]
When using the newest version of Dash to Panel (at commit 7bb1cb05c0710aa02c72dc15866316736e623319) I get the following error message every time I hover over an app icon to open the window preview. I ran `gnome-shell --replace` to see this message in the debug logs:

```
(gnome-shell:16766): Gjs-WARNING **: JS ERROR: TypeError: Shell.WindowTracker.get_default(...).focus_app is null
thumbnailPreviewMenu<.hoverOpen@/home/thomasstevenson/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/windowPreview.js:199
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
```

After looking through the code, it looks like the new VirtualBox handling code is causing this issue. Perhaps the version of Gnome Shell in Ubuntu 16.04 (version 3.18) isn't compatible with this line of code in the windowPreview.js > hoverOpen() function?
`let focusedApp = Shell.WindowTracker.get_default().focus_app.get_name();`

**Comment by jderose9** [comment]
I couldn't reproduce, but did check for null before trying to get the app name. Can you give the latest master a shot and let me know if it's not resolved? Thank you!
