### ISSUE TITLE
Resizing the Panel does not respect the App Icon Margin

### ISSUE THREAD

**Issue by lexruee** [jderose9/dash-to-panel#226]
Hi thanks for this awesome extension. I use it as a pure taskbar along with dash-to-dock :smile:.
I guess a problem that some users might have encountered as well is the Panel-Resize-Bug.

**Problem:** Resizing the Panel does not respect the App Icon Margin.

**Steps to reproduce:**
1. Set Panel Size to 24 px
2. Set App Icon Margin to 0 px
3. Resize the Panel by setting its size to 96 px
4. Resize the Panel again by setting its size to 24 px

**Dash to Panel Version:** master (7bb1cb05c0710aa02c72dc15866316736e623319)

**My System:**
```
Debian GNU/Linux unstable (sid)
GNOME Shell 3.22.3
```

**Video**
I made a short youtube video that demonstrates this bug:
https://youtu.be/dfdwA1gilc8

**Comment by jderose9** [comment]
Thanks for reporting this and the detailed video. I think it was already reported as #102. Is that the same issue?

**Comment by lexruee** [comment]
@jderose9 
You are right :-). This is the same issue. Shall I comment the information here on the issue #102?

**Comment by jderose9** [comment]
Yes, if you can add the comments to the other issue that would be great. Yes, I agree it should be fixed. Feel free to take a shot at it and I will be happy to help if you need it. The margin gets assigned here: https://github.com/jderose9/dash-to-panel/blob/master/appIcons.js#L336
