### ISSUE TITLE
Request: Change Default: Clock Location > Left of Status Window

### ISSUE THREAD

**Issue by pantar85** [jderose9/dash-to-panel#227]
Would like to make a request for one small change in default.

Clock location is default to right of status menu.

Request to move it to the left, so as more similar to KDE/Windows 7+ as the extension introduction says.

Thank you for wonderful extension.

**Comment by jderose9** [comment]
Hi there! If I understand correctly, this is already the default (clock is left of status menu):

https://github.com/jderose9/dash-to-panel/blob/master/schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml#L131

Perhaps you just had an old setting cached? (They stick around even after uninstalling the extension, unless you wipe the key from dconf) Or am I misunderstanding?
