### ISSUE TITLE
App icons respond inconsistently to touches when "Show window previews on hover" is on

### ISSUE THREAD

**Issue by Pointedstick** [jderose9/dash-to-panel#23]
I'm really loving this extension on my convertible laptop (Late 2016 Kaby Lake HP Spectre x360, Fedora 25, GNOME 3.22) because the double-height bottom bar provides much bigger touch targets when using the machine in tablet mode.

However, touch behavior on app icons is inconsistent: sometimes simple touches are interpreted as a left-click (good), sometimes as a click-and-hold. Seems like the threshold for interpreting something as a click-and-hold is too low.

Actual tap-and-hold (touch and hold finger there for a full second or longer) is correctly interpreted as a click-abd-hold/right-click 100% of the time.

Everything on the right-side of the panel responds to touches perfectly, including extensions that put things there (OpenWeather, Topicons Plus).

I really love this extension and would be happy to work with you to debug the issue.

**Comment by Pointedstick** [comment]
Update: turning off "Show window previews on hover" resolves the issue. So there may be some bug in the hover code.

**Comment by jderose9** [comment]
Glad you found a workaround! It will probably require outside help to resolve this one as I don't have a touch device and realistically won't get around to figuring out how to emulate touch events anytime soon..

**Comment by Pointedstick** [comment]
Resolved in version 6.
