### ISSUE TITLE
Dash to Panel plugin should disable / have option to disable default Ubuntu 17.10 Dash to Dock launcher.

### ISSUE THREAD

**Issue by JQADEV** [jderose9/dash-to-panel#231]
**Preconditions:**
1. Installed Ubuntu 17.10 with the latest changes adding Dash to Dock as a default launcher described [here](https://didrocks.fr/2017/08/18/ubuntu-gnome-shell-in-artful-day-5/).
2. Installed and enabled Dash to Panel plugin.

**Obtained results:**
There is no option to disable new default Ubuntu 17.10 Dash to Dock launcher both in Ubuntu and Dash to Panel plugin. 
Currently after addition Dash to Panel there are two simultaneously existing launchers.  

**Expected results:**
Dash to Panel plugin should disable / have option to disable default Ubuntu 17.10 Dash to Dock launcher.

**Comment by SolarLiner** [comment]
I think that's more an issue on the Ubuntu dock than anything. In the other hand there was no option to disable the dock in Unity either and that may just be them replicating initial behavior.

**Comment by Programming4life** [comment]
Does anyone know of a way to hide/disable the dock on the desktop? In default gnome it only shows if you press the windows key, and that is what I want.

**Comment by fastrizwaan** [comment]
Yes, remove the ubuntu dock gnome extension using apt. Seems like ubuntu guys are forcing their dock in gnome users' throat.

in 17.10

`sudo apt remove gnome-shell-extension-ubuntu-dock `

**Comment by SolarLiner** [comment]
Ubuntu 17.10 will provide two GNOME sessions: A "Ubuntu" session with predefined extensions such as the Ubuntu Dock, and another "Vanilla" one which will be pure GNOME without anything added.

Just FYI; also GNOME users in Ubuntu will see no change in their session (just the "Ubuntu" session being added) while migrating.

**Comment by JQADEV** [comment]
I have found the solution for this issue. There is already available extension to disable default Ubuntu Dock here: https://extensions.gnome.org/extension/1290/disable-ubuntu-dock/
I have tested it and it's working.

**Comment by Programming4life** [comment]
@SolarLiner Do you know if the option has already been added in?

**Comment by jderose9** [comment]
I would like to incorporate this into the extension so the Ubuntu dock is disabled automatically when Dash-to-Panel is installed. Does this need to be able to be turned back on in the settings? Or is the Ubuntu dock completely useless with dash-to-panel? (It seems redundant to me, but I am curious what everyone else thinks)

**Comment by JQADEV** [comment]
In my opinion the Ubuntu dock is completely useless with dash-to-panel enabled. @jderose9, please use in your plugin ready implementation from https://extensions.gnome.org/extension/1290/disable-ubuntu-dock/

**Comment by jderose9** [comment]
Ok, I've made a commit to disable the dock when this extension is enabled. I don't use Ubuntu on a daily basis so please post back if it's not working as expected. Thanks everyone!

**Comment by adred** [comment]
If there's an option so it wouldn't extend to the screen edge, maybe I wouldn't install Dash-To-Dock extension.
