### ISSUE TITLE
Cycle through windows by scrolling over the application icon

### ISSUE THREAD

**Issue by BeayemX** [jderose9/dash-to-panel#233]
At the moment it is only possible to cycle through open windows when clicking on the icon.
Being able to do this instead by scrolling would be a nice addition.

This would make the experience more consistent because it would always show/hide the application when clicking the icon and the behavior would not change depending on if there is only one or if there are multiple windows per application.

**Comment by jderose9** [comment]
Hello! Thanks for this. I believe it is a duplicate of #30 though. You can comment there or subscribe to that one for updates.
