### ISSUE TITLE
Autohiding problem

### ISSUE THREAD

**Issue by ostrol** [jderose9/dash-to-panel#238]
Dash to Panel opens on the bottom, and has autohiding enabled. It won't come out of hiding, when the bottom edge is pushed/touched with the cursor, but when cursor touches the top screen edge. Can you do something about this?

**Comment by jderose9** [comment]
Hi.. Are you sure you don't have an extension installed causing this behavior? Dash-to-Panel doesn't currently have auto-hiding built in.

**Comment by vivaeltopo** [comment]
This is indeed a problem with the hidetopbar extension, which, as the name suggests, only works with panels at the top.
Auto/Inteli hide for this extension would be great!

**Comment by jderose9** [comment]
Ok, I'll close this one out. There is an item to add intellihide. Feel free to subscribe for updates - #41

Thank you!
