### ISSUE TITLE
Get this thing listed on extensions.gnome.org

### ISSUE THREAD

**Issue by Pointedstick** [jderose9/dash-to-panel#24]
It's too awesome to have it stuck here on github with a limited audience and no automatic updates.

You can do it here: https://extensions.gnome.org/accounts/login/?next=/upload/

**Comment by jderose9** [comment]
Thanks! I submitted but they haven't reviewed it yet.. https://extensions.gnome.org/review/6520

**Comment by Pointedstick** [comment]
Awesome!

**Comment by jderose9** [comment]
This extension is now available on gnome.org.

https://extensions.gnome.org/extension/1160/dash-to-panel/

If you've installed from github you will need to Remove in Tweak Tool and reinstall from there to get the automated updates. Thanks!
