### ISSUE TITLE
NetSpeed applet vertical aligment

### ISSUE THREAD

**Issue by granjerox** [jderose9/dash-to-panel#243]
Wrong vertical aligment of netspeed values when dash-to-panel active

With Dash-to-Panel
![image](https://user-images.githubusercontent.com/2721558/30501871-5b4c2e2e-9a64-11e7-91a0-4fb2d528f0cd.png)

Without Dash-to-Panel
![netspeed-vertical-aligment](https://user-images.githubusercontent.com/2721558/30501903-771f6db4-9a64-11e7-97c4-0227ab6ad6b0.png)

Issue also opened [@netspeed](https://extensions.gnome.org/extension/104/netspeed/) [#28](https://github.com/hedayaty/NetSpeed/issues/28)

**Comment by jderose9** [comment]
I'm not sure, but it appears to me that the text is vertically aligned on your screenshot without dash-to-panel as well - it's just that the panel height is larger on your first screenshot so it is a lot more obvious. So, I think this may have to get resolved on the netspeed side.
