### ISSUE TITLE
crashing in gnome 3.26

### ISSUE THREAD

**Issue by briandconnolly** [jderose9/dash-to-panel#245]
I think the extension is crashing in gnome 3.26.0, i.e. I frequently lose the panel icons (favories, dash). If I reboot the extension, all is good again.
Just a thought. FYI.
Brian

**Comment by jderose9** [comment]
Which distro are you using?

**Comment by briandconnolly** [comment]
Fedora Rawhide.

**Comment by vans163** [comment]
journalctl -b   output?

**Comment by vans163** [comment]
@jderose9 You need to move the extensions out manually, i just make a extensions_disabled folder along side extensions in both the local and global dirs.  Yea its a bug somewhere, im not sure if its a gnome bug or a fedora bug.

**Comment by jderose9** [comment]
Is this still occurring? It seems like 3.26 was pretty unstable on initial release.

**Comment by ivek1312** [comment]
I get this on gentoo:
'JS WARNING: [resource:///org/gnome/shell/ui/main.js 315]: reference to undefined property "MetaStage"
JS WARNING: [resource:///org/gnome/shell/ui/layout.js 221]: reference to undefined property "MetaWindowGroup"
JS WARNING: [resource:///org/gnome/shell/ui/osdMonitorLabeler.js 59]: reference to undefined property "MetaDBusDisplayConfigSkeleton"
JS WARNING: [resource:///org/gnome/shell/ui/slider.js 38]: reference to undefined property "CallyActor"
JS WARNING: [resource:///org/gnome/gjs/modules/tweener/tweener.js 540]: reference to undefined property "isSpecialProperty"
No permission to trigger offline updates: Polkit.Error: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.packagekit.trigger-offline-update is not registered
JS WARNING: [/home/ivik/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js 43]: reference to undefined property "dtpPanel"
Extension "dash-to-panel@jderose9.github.com" had error: TypeError: Panel.dtpPanel is not a constructor
JS WARNING: [resource:///org/gnome/shell/ui/workspaceThumbnail.js 892]: reference to undefined property "_switchWorkspaceNotifyId"
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Window manager warning: Invalid WM_TRANSIENT_FOR window 0x260000d specified for 0x2600010 (KGpg Assis).
GNOME Shell started at Thu Oct 12 2017 22:44:06 GMT+0200 (CEST)
'

**Comment by ivek1312** [comment]
I got it working. Replaced all let statements to var in class definitions.

**Comment by jderose9** [comment]
@ivek1312 Odd, this was supposed to continue to work for the time being. Regardless, It should be fixed by #260.
