### ISSUE TITLE
Feature Request: use mouse wheel on the panel to control volume

### ISSUE THREAD

**Issue by mispp** [jderose9/dash-to-panel#247]
just move mouse over the panel and use wheel to increase/decrease volume.

idea comes from this https://irzyxa.wordpress.com/

**Comment by jderose9** [comment]
Thanks for the idea, but my thought at this time is that this would be better to belong in its own extension as I don't think anything within the implementation of this would be specific to or required by dash-to-panel (In other words, users may want this feature even if they don't have dash-to-panel installed)
