### ISSUE TITLE
Double icons issue

### ISSUE THREAD

**Issue by marko-lazic** [jderose9/dash-to-panel#249]
Some applications when launched appear double in panel. Difference between them is that they are installed in ```/home/user/.local/``` directory. See [image](https://i.imgur.com/qkK7Q9r.png).

**Comment by jderose9** [comment]
Can you try and see if it happens with dash-to-panel disabled? (Do you see two icons in the left hand dash in the Overview without this extension?)

The common fix for this is to set the `StartupWMClass` in the `.desktop` file. The desktop file should be located in `~/.local/share/applications` or `/usr/share/applications` Check out this link for more details on how to do that:
https://askubuntu.com/questions/403766/duplicate-icons-for-manually-created-gnome-launcher-items

Let me know what you find!

**Comment by marko-lazic** [comment]
This fixes a problem. Thank you very much.
