### ISSUE TITLE
Dash to panel on Centos 7.4 crashes with virt-manager

### ISSUE THREAD

**Issue by eilgni** [jderose9/dash-to-panel#250]
Hello Dash to Panel Developers 

I want to thank you for this awesome software you have done. I've been enjoying a lot and must say is an excelent Panel.

I am using Centos 7.4 in my Dell Laptop and experiencing crashes only with virt-manager when I do preview on any tab it has open and want to go to other tab, all Gnome-shell breaks and need to do a

$ killall -3 gnome-shell 

to restore the restore the desktop.

With all other software  I have try it is Ok.

gnome is in version 3.22.2

 rpm -qa gnome*
gnome-bluetooth-libs-3.20.1-1.el7.x86_64
gnome-abrt-0.3.4-8.el7.x86_64
gnome-color-manager-3.22.2-1.el7.x86_64
gnome-clocks-3.22.1-1.el7.x86_64
gnome-themes-standard-3.22.2-1.el7.x86_64
gnome-shell-extension-alternate-tab-3.22.2-10.el7.noarch
gnome-weather-3.20.2-1.el7.noarch
gnome-online-accounts-3.22.5-1.el7.x86_64
gnome-shell-extension-apps-menu-3.22.2-10.el7.noarch
gnome-getting-started-docs-es-3.22.0-1.el7.noarch
gnome-system-log-3.9.90-3.el7.x86_64
gnome-packagekit-3.22.1-2.el7.x86_64
gnome-documents-libs-3.22.2-5.el7.x86_64
gnome-system-monitor-3.22.2-2.el7.x86_64
gnome-packagekit-installer-3.22.1-2.el7.x86_64
gnome-classic-session-3.22.2-10.el7.noarch
gnome-getting-started-docs-3.22.0-1.el7.noarch
gnome-shell-browser-plugin-3.22.3-17.el7.x86_64
gnome-keyring-3.20.0-3.el7.x86_64
gnome-python2-gconf-2.28.1-14.el7.x86_64
gnome-settings-daemon-3.22.2-5.el7.x86_64
gnome-contacts-3.22.1-1.el7.x86_64
gnome-screenshot-3.22.0-1.el7.x86_64
gnome-packagekit-common-3.22.1-2.el7.x86_64
gnome-terminal-3.22.1-2.el7.x86_64
gnome-shell-3.22.3-17.el7.x86_64
gnome-user-docs-3.22.0-1.el7.noarch
gnome-initial-setup-3.22.1-4.el7.x86_64
gnome-disk-utility-3.22.1-1.el7.x86_64
gnome-menus-3.13.3-3.el7.x86_64
gnome-icon-theme-symbolic-3.12.0-2.el7.noarch
gnome-bluetooth-3.20.1-1.el7.x86_64
gnome-online-miners-3.22.0-2.el7.x86_64
gnome-shell-extension-common-3.22.2-10.el7.noarch
gnome-video-effects-0.4.3-1.el7.noarch
gnome-backgrounds-3.22.1-1.el7.noarch
gnome-font-viewer-3.22.0-1.el7.x86_64
gnome-desktop3-3.22.2-2.el7.x86_64
gnome-shell-extension-places-menu-3.22.2-10.el7.noarch
gnome-icon-theme-3.12.0-1.el7.noarch
gnome-session-3.22.3-4.el7.x86_64
gnome-shell-extension-launch-new-instance-3.22.2-10.el7.noarch
gnome-python2-canvas-2.28.1-14.el7.x86_64
gnome-python2-bonobo-2.28.1-14.el7.x86_64
gnome-documents-3.22.2-5.el7.x86_64
gnome-dictionary-3.20.0-1.el7.x86_64
gnome-session-xsession-3.22.3-4.el7.x86_64
gnome-packagekit-updater-3.22.1-2.el7.x86_64
gnome-icon-theme-legacy-3.12.0-1.el7.noarch
gnome-vfs2-2.24.4-14.el7.x86_64
gnome-dictionary-libs-3.20.0-1.el7.x86_64
gnome-terminal-nautilus-3.22.1-2.el7.x86_64
gnome-tweak-tool-3.22.0-1.el7.noarch
gnome-calculator-3.22.3-1.el7.x86_64
gnome-keyring-pam-3.20.0-3.el7.x86_64
gnome-icon-theme-extras-3.12.0-1.el7.noarch
gnome-python2-2.28.1-14.el7.x86_64
gnome-boxes-3.22.4-4.el7.x86_64
gnome-vfs2-devel-2.24.4-14.el7.x86_64
gnome-shell-extension-user-theme-3.22.2-10.el7.noarch
gnome-python2-gnome-2.28.1-14.el7.x86_64
gnome-shell-extension-window-list-3.22.2-10.el7.noarch
gnome-python2-gnomevfs-2.28.1-14.el7.x86_64

The problem seem to occur when I pess click on a Virt_manger tab and it stay Blue and never changes to the window I have pressed. Mouse is completly unresponsive. After kill gnome-shell abrt say virt-manager has a problem and closes all the windows. If I Change to a new terminal with CTRL+ALT+F2 and return and press ALT + TAB, I can again move the mouse and all seen OK.

I Attach some screen captures
![captura de pantalla de 2017-09-24 13-25-23](https://user-images.githubusercontent.com/32246872/30786164-7ef9b240-a137-11e7-81fd-4edf2b52b985.png)
![captura de pantalla de 2017-09-24 13-38-09](https://user-images.githubusercontent.com/32246872/30786163-7ef9db80-a137-11e7-9402-b4a6b354841d.png)
![captura de pantalla de 2017-09-24 13-43-28](https://user-images.githubusercontent.com/32246872/30786165-7efd21fa-a137-11e7-8707-528485e5126d.png)
![captura de pantalla de 2017-09-24 13-45-11](https://user-images.githubusercontent.com/32246872/30786166-7f001662-a137-11e7-8d51-b38eb0c83d8b.png)

**Comment by jderose9** [comment]
Looks like this was the same issue basically as VirtualBox, where the VM is stealing focus. Give the latest in master branch a try now. Thanks for reporting this!
