### ISSUE TITLE
Icon padding increasing when ACPI sleep/wake

### ISSUE THREAD

**Issue by cmivxx** [jderose9/dash-to-panel#254]
Love the tool.  Have it set to "App Icon Margin" to 0:

![Panel Settings](http://api.cmivxx.com/cmimg/panel_settings.png)

And it looks great when I first boot before sleeping: (notice active icon with background)

![Good Panel Layout](http://api.cmivxx.com/cmimg/bar_shot_without_padding-cropped.jpg)

However once I sleep the laptop and wake it back up, padding appears:  (notice the active icon background with extra bars on r & l)

![Bad Panel Layout](http://api.cmivxx.com/cmimg/bar_shot_with_padding-cropped.jpg)

Is this a known issue?  Is there a prefs file that contains the settings that I can monitor to see if it changes somewhere?  I love the layout and would love to keep it working properly.  

Thanks!

**Comment by SolarLiner** [comment]
This is indeed a known issue, and one that sticks around unfortunately.

**Comment by cmivxx** [comment]
ok...  sorry for being redundant then.  FYI, restarting gnome-shell resets it to normal.  Appears to be a difference between what the plugin does on activate and on resume.  I'll go poke around and see if I can contribute anything then.

**Comment by hubslave** [comment]
hello @cmivxx https://github.com/jderose9/dash-to-panel/issues/85 - here you can find some info we collected regarding this issue, maybe it will be helpful. Unfortunately we did not find clear pattern when does this happen so many people cannot reproduce this bug

**Comment by cmivxx** [comment]
ohhh neat.  Ok, thanks.  I'll update if I find anything.

If it helps, I'm running Ubuntu 17.04 + Gnome 3.24.2 on a Lenovo X240.

**Comment by jderose9** [comment]
Thank you for reporting this. I'm going to close since #85 is open, but please feel free to add any relevant info and subscribe there for updates.
