### ISSUE TITLE
dynamic transparency  for not-maximized windows like gnome 3.26

### ISSUE THREAD

**Issue by fastrizwaan** [jderose9/dash-to-panel#255]
In Fedora 27 and gnome 3.27; the panel has dynamic  transparency support. And dash to panel looks great with transparency:
![screenshot from 2017-10-08 19-15-18](https://user-images.githubusercontent.com/1161682/31318309-b01520f4-ac3f-11e7-86f7-41f3cf641fc4.png)

But with any active window, which is not touching the panel, dash-to-panel becomes opaque (non-transparent)
![screenshot from 2017-10-08 19-15-42](https://user-images.githubusercontent.com/1161682/31318319-d3360ecc-ac3f-11e7-9416-d9563e1cb6d4.png)

Could you please consider dynamic transparency support in dash-to-panel?

**Comment by fastrizwaan** [comment]
Here's a youtube video
https://www.youtube.com/watch?v=7IUOF_bMROA

and the article:
http://www.omgubuntu.co.uk/2017/06/gnome-3-26-translucent-topbar-video

**Comment by franglais125** [comment]
Would you mind testing this https://github.com/jderose9/dash-to-panel/pull/256?

**Comment by fastrizwaan** [comment]
@franglais125 Thank you, after replacing the panel.js https://raw.githubusercontent.com/franglais125/dash-to-panel/d6d139d4d9968d07ea5ffaa12a3908d4a950ba85/panel.js in extensions directory, dynamic transparency is working for bottom panel.

**Comment by jderose9** [comment]
Thanks so much @franglais125 . This has been merged.
