### ISSUE TITLE
Merge when full

### ISSUE THREAD

**Issue by 0matgal0** [jderose9/dash-to-panel#257]
Would be nice to have this feature. Basically behave like a taskbar, but switch to dock when space is wholly occupied.

**Comment by jderose9** [comment]
When the panel is full, moving the mouse towards the edge of the icon section of the panel will scroll the icons. Is this what you mean?

**Comment by jderose9** [comment]
I'm going to close this as I believe what you are asking for has already been implemented. However, feel free to post back if I misunderstood what you are asking for.
