### ISSUE TITLE
can you center the clock?

### ISSUE THREAD

**Issue by Pshemas** [jderose9/dash-to-panel#258]
I love the functionality this panel provides , but I wonder - is it possible to center clock "applet" for example? I quite like how it is arranged in default Gnome setup (but I severly miss taskbar).

**Comment by Swedneck** [comment]
I solved it by setting the clock position to "natural" and having enough spacing between stuff to push the clock to the middle. 
![image](https://user-images.githubusercontent.com/31285258/31897322-46c96b7c-b816-11e7-83e3-7af2c4a2a2ee.png)
Would be nice to have a proper way of doing it though.

**Comment by jderose9** [comment]
It's not currently possible, but there is an item #60 to address this. You can subscribe to that item to get notifications about it. Thanks!
