### ISSUE TITLE
Delay before appearance of window preview

### ISSUE THREAD

**Issue by TheInitializer** [jderose9/dash-to-panel#26]
When I'm running my cursor along my window icons, the window previews appear very quickly which is unnecessary and doesn't look very nice. I'd like if there was a ~0.5s delay before activating the window preview.

A simple fade-in transition would go well too.

**Comment by jhasse** [comment]
I actually like this :) A config option would be nice though.

**Comment by jderose9** [comment]
I agree with you guys but haven't yet come up with a working solution. There's some bug or quirk with the gnome shell. The problem occurs if you move over the icon and click before the popup appears, and the popup start rendering as the mouse exits the icon region, which will trigger it to close again. The focus gets stuck on the now-dead popup preview window and gnome shell appears to be frozen. Most of the events get swallowed by the event handler until the popup is closed, so it's hard to hook in to workaround and re-focus the correct window.

I tried a bunch of stuff to get around it, but when I get some time I'll take another stab at it now that I have more familiarity with the underlying gnome-shell code.
