### ISSUE TITLE
Frequent crashes in windowPreview.js

### ISSUE THREAD

**Issue by juergh** [jderose9/dash-to-panel#261]
Not sure if this has been reported already but I see frequent (like once an hour or so) gnome-shell crashes due to dash-to-panel. It seems to happen most frequently when an application terminates.

Dash-to-panel is current from the master branch as of today Oct 19.
Distro is Ubuntu 17.10, Xorg 1:7.7+19ubuntu3, gnome-shell, 3.26.1-0ubuntu4.
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1714989

gjs_dumpstack():
Oct 19 10:24:34 org.gnome.Shell.desktop[11871]: == Stack trace for context 0x55c0da49d170 ==
Oct 19 10:24:34 org.gnome.Shell.desktop[11871]: #0 0x7ffc82d045f0 b   /home/juergh/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/windowPreview.js:538 (0x7fea61665bc0 @ 36)
Oct 19 10:24:34 org.gnome.Shell.desktop[11871]: #1 0x7ffc82d04690 I   self-hosted:917 (0x7feaac4ee4d8 @ 394)

Not sure if that's related but I also see lost of the following (log grep'ed for windowPreview):
Oct 17 13:33:28 gnome-shell[19104]: JS WARNING: [/home/juergh/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/windowPreview.js 786]: reference to undefined property "_stateChangedId"
Oct 17 13:33:47 gnome-shell[19104]: JS WARNING: [/home/juergh/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/windowPreview.js 934]: reference to undefined property 0
Oct 17 13:48:46 gnome-shell[30048]: Some code accessed the property 'thumbnailPreviewMenu' on the module 'windowPreview'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

**Comment by lexruee** [comment]
Some of the JS warnings are fixed in the open pull requests: #260 and #259. Maybe they help to fix some of the gnome-shell crashes.

**Comment by juergh** [comment]
Fixed by PR #263. Thanks!
