### ISSUE TITLE
Dynamic Transparency 

### ISSUE THREAD

**Issue by deepakSP** [jderose9/dash-to-panel#262]
Really Like Dynamic Transparency Feature but is thr any way we can make it dark solid color ?
right now it look gradient !! which is little uneasy (i don't know if screenshot can justify my claim :P).

![](https://s1.postimg.org/1m3oqcf2ml/Screenshot_from_2017-10-20_01-09-28.png)

**Comment by jderose9** [comment]
Is this coming from your wallpaper?

**Comment by deepakSP** [comment]
@jderose9 might be ! but thr is bottom white shadow or something, like to set solid color

**Comment by deepakSP** [comment]
In gnome session i am getting solid black so i think it just Ubuntu default session issue.

**Comment by jderose9** [comment]
It's not clear to me if any action needs to be taken on this item? I don't see the same gradient in 17.10 final release if I use the default theme and wallpaper and enable dash-to-panel only.

**Comment by jderose9** [comment]
I'm going to close for now as I don't think this is coming from the panel.. Thanks!
