### ISSUE TITLE
Old dash didn't disappear

### ISSUE THREAD

**Issue by rthg** [jderose9/dash-to-panel#265]
I installed the extension, but the old dash did not disappear.
![screenshot from 2017-10-21 03-35-27](https://user-images.githubusercontent.com/21966871/31845389-2a39b7d4-b611-11e7-8373-375234e47d4f.png)

Ubuntu 17.10

**Comment by jderose9** [comment]
Where did you install the extension from? The change to disable the Ubuntu dock hasn't been accepted by extensions.gnome.org yet so you will have to install the latest from GitHub. (Or remove the ubuntu dock package  )

**Comment by rthg** [comment]
Yes, I just installed gnome-session package and everything works fine. Thanks!
