### ISSUE TITLE
Crash randomly gnome-shell on intensive task

### ISSUE THREAD

**Issue by nathanielsimard** [jderose9/dash-to-panel#267]
Gnome-shell was crashing a lot when using Google Chrome, Firefox, Vs-Code etc. I didn't know where it came from, I removed all extensions and added them back one by one to discover it was from dash-to-panel.

Those were the errors I got from syslog :
```
Window manager warning: "XF86RFKill" is not a valid accelerator
Error looking up permission: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.impl.portal.PermissionStore was not provided by any .service files
```
My laptop has hybrid graphics, the crashes occurred on X with intel or nvidia and also on Wayland with intel.

OS: Ubuntu 17.10

**Comment by jderose9** [comment]
Can you try installing from github using the newest code from the `master` branch?

**Comment by nathanielsimard** [comment]
It seems that the version from the `master` branch don't have that bug. It doesn't crash anymore !

**Comment by jderose9** [comment]
Great to hear! It is awaiting release on extensions.gnome.org so you can install from there once v11 is approved (if you want to keep receiving updates). Thanks for testing.
