### ISSUE TITLE
Dash entries to not adapt properly to changing highDPI scaling

### ISSUE THREAD

**Issue by RalfJung** [jderose9/dash-to-panel#271]
## Steps to reproduce

* On a 4K laptop, have no external screen connected and log in to Gnome with this (awesome :D ) extension installed. Gnome is using high DPI scaling.
* Plug in an external full-HD (low-DPI) screen, with things set up such that the internal screen gets diabled.

## Actual behavior

The top bar now looks like this:
![bad](https://user-images.githubusercontent.com/330628/31991071-277c763a-b977-11e7-9eb2-4a100b13daad.png)
As you can see, the application icons are spaced way too far apart.

# Expected behavior

The top bar should look like this:
![good](https://user-images.githubusercontent.com/330628/31991065-24dc0aa8-b977-11e7-8a7f-3739d716a990.png)
This is what I get after restarting gnome shell, once there is just the low-DPI screen.

My guess is that the extension does not adapt its spacing (in pixels) when the DPI scaling factor changes.

**Comment by lexruee** [comment]
I think this issue is probably related to the following issue: https://github.com/jderose9/dash-to-panel/issues/102

**Comment by jderose9** [comment]
The fix for #85 may have resolved it. Can you give the latest `master` a shot? Thanks!

**Comment by jderose9** [comment]
Can you give the latest `master` branch a shot? Thanks!

**Comment by RalfJung** [comment]
That seems to have fixed it, thanks :)
