### ISSUE TITLE
(enhancement) Scroll on favourite applications icons to switch active windows

### ISSUE THREAD

**Issue by friimaind** [jderose9/dash-to-panel#273]
It might be useful to use the mouse wheel on the icons to change the active application window.

For example: scrolling on firefox should change the active window 

![image](https://user-images.githubusercontent.com/16322003/32046374-3254b690-ba43-11e7-9fa9-c8c20eb70b42.png)

If I'm not wrong dash-to-dock has this functionality and it's great: https://micheleg.github.io/dash-to-dock/news/page2/

Cycle though windows by mouse scroll

> The ability to cycle through open windows on mouse scroll has been asked for a long time. This behaviour is now available in the settings.

**Comment by jderose9** [comment]
Yup! There is an open item #30 to address this. Feel free to subscribe to the issue for updates!

**Comment by friimaind** [comment]
Ops! Thank you and sorry for the duplicate ;)
