### ISSUE TITLE
Gnome 3.26 support in extension.gnome.org

### ISSUE THREAD

**Issue by ceyhunnabiyev** [jderose9/dash-to-panel#274]
I see, dash-to-dock has gnome 3.26 support in extension.gnome.org. but dash-to-panel doesn't, even you released dash-to-panel v.11 out. Please add support for this.

**Comment by jderose9** [comment]
They have to review it before v11 will be live. The version in e.g.o. is still v9. You can see the status here:

https://extensions.gnome.org/review/

**Comment by lexruee** [comment]
I just ping the GNOME dev @maweki. Maybe it helps to speed up the review process for dash-to-panel :-).

**Comment by maweki** [comment]
You think this gives you special treatment? :D

I think I have a few hours today to do reviews. The queue is always quite long.

**Comment by ceyhunnabiyev** [comment]
@maweki ,  Please add  latest version or v.10 of this, I love this extension :wink:

**Comment by jderose9** [comment]
Thanks guys :)

**Comment by lexruee** [comment]
I think @maweki deserves a big thanks :smile: for the fast response and review.

**Comment by ceyhunnabiyev** [comment]
@maweki , thanks for fast review.
@lexruee , thanks for help.
@jderose9 , thanks for great extension.
