### ISSUE TITLE
[Feature Request] Option to show legacy trays in Gnome 3.26

### ISSUE THREAD

**Issue by ceyhunnabiyev** [jderose9/dash-to-panel#280]

**Comment by jderose9** [comment]
The legacy tray API is going away.

I recommend this extension to add status indicators to your panel: https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by ceyhunnabiyev** [comment]
But this doesn't work on me. Can you please give example for this on dash-to-panel?
