### ISSUE TITLE
Feature Request: extending Taskbar preview technology to enhance default Alt-Tab

### ISSUE THREAD

**Issue by nick-walt** [jderose9/dash-to-panel#282]
Hi DTP!

A great extension that enables much better management of our running apps. Thank you!

I am surprised that you guys didn't use your established preview technology to create an enhanced Alt-Tab experience. I currently use Alternatetab, but I feel that the previews are too small.

Would be great to see your technology improving the default Alt-Tab experience on Gnome.

I'm using Ubuntu 17.10 with Wayland.

Cheers,
Nick

**Comment by jderose9** [comment]
Hi! Thanks for the positive feedback. I am not sure I understand the request though - the thumbnail preview you see is actually the same as the thumbnail preview from gnome-shell that Alternate-Tab uses. AlternateTab is actually an official/1st party gnome extension.. you can open a work order on the gnome bugzilla or ask on the gnome mailing list to see if anyone has a tip for adjusting the size.
