### ISSUE TITLE
Gnome-shell says dash-to-panel could be updated

### ISSUE THREAD

**Issue by RalfJung** [jderose9/dash-to-panel#286]
I am running the latest git version of dash-to-panel. Still, once a week, gnome shell tells me that my extension is outdated and could be updated.

There should be no such message when I am in fact running git master.

**Comment by jderose9** [comment]
Thanks! This is annoying me too. Certainly it shouldn't notify you continually, as it does now. But I'm unsure, if I have installed from git, whether there should be a notification when extensions.gnome.org legitimately has a newer version? Or do we assume that once installed from git, you are basically off the grid at that point?

**Comment by jderose9** [comment]
I've adjusted this so the most recent version is written to the metadata from the git repo when installing locally. So, if you install the latest from master, you shouldn't get an update notification any longer, unless an actual newer release is on extensions.gnome.org. Let me know if you don't think this is the correct behavior! thanks!

**Comment by RalfJung** [comment]
That sounds exactly right, thanks a lot!
