### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Miguel-Dorta** [jderose9/dash-to-panel#287]
Hi,
I've been using dash-to-panel for a long time, and I recently have experience a extremely high use of CPU, which I concluded that is created by dash-to-panel, or something related to it's integration with gnome-shell (because is this process the one who use the CPU a lot, but this disapear when I disable dash-to-panel).

I'll help providing information about the problem.

CPU: Intel Core i7 6500U - 2.5Ghz (2 cores, 4 threads)
Memory: 4 GiB RAM, 2 GiB SWAP
Disk: SSD 240Gb
Linux Distribution: ArchLinux (x86_64)
Kernel Version: 4.13.11
Gnome Shell Version: 3.26.2
Dash-to-Panel Version: 11

Thank you.

**Comment by Miguel-Dorta** [comment]
After testing several things, I concluded that it was [TopIcons Plus](https://github.com/phocean/TopIcons-plus), not dash-to-panel. I'm sorry.

**Comment by jderose9** [comment]
Glad to hear that you got it figured out!
