### ISSUE TITLE
Feature Request: Auto Hide

### ISSUE THREAD

**Issue by zachThePerson** [jderose9/dash-to-panel#294]
I love this extension, however the one thing that I really feel is missing is an "Auto-Hide" option.

**Comment by Nebrit** [comment]
@jderose9 Please develop Autohide. You can start with this code of https://github.com/mlutfy/hidetopbar are the same architecture and you can add to test at the base code. 

[hidetopbar-master.zip](https://github.com/jderose9/dash-to-panel/files/1515714/hidetopbar-master.zip)

To begins is a perfect way this code, I think.

**Comment by PrimarchAlpharius** [comment]
Agreed, it's a great extension I've been waiting for years, the autohide would help a lot with loss of vertical space. Keep up the good work!

**Comment by jderose9** [comment]
Thanks for requesting this! However, please jump over to #41 for updates. Thanks!
