### ISSUE TITLE
Cannot add Dolphin to Favorites

### ISSUE THREAD

**Issue by BenniG82** [jderose9/dash-to-panel#296]
I'm coming from KDE and would like to use Dolphin because Nautilus is very limited :(
But dash-to-panel does not allow me to set Dolphin as a favorite. It just does not show this option. Also "New Window" is missing (what is less important but would also be nice).
![image](https://user-images.githubusercontent.com/6051664/33346727-fd390ce6-d490-11e7-9ff5-0e4cfa9c30cb.png)

Some info about my environment:
Fresh install of Ubuntu 17.10 with very few applications installed.

**Comment by bil-elmoussaoui** [comment]
The same thing as i said in https://github.com/jderose9/dash-to-panel/issues/303#issuecomment-352721808

**Comment by jderose9** [comment]
Yes, this is related to the .desktop file included with the dolphin package for your distro and would behave similarly without this extension. Thanks for fix, @bil-elmoussaoui .
