### ISSUE TITLE
No icons on panel after suspend

### ISSUE THREAD

**Issue by bryce-lynch** [jderose9/dash-to-panel#299]
Today I noticed - for the first time since I installed this extension - that after resuming from suspend-to-ram there are no icons on the panel. I tried disabling and re-enabling it via tweak tool, but the only way to restore its functionality is either logging out and in, or rebooting. There were a js52 and a gjs update in arch today, don't know if this is relevant. Any idea how I can debug this issue?

**Comment by martinm1000** [comment]
Yep, this happen since that gnome update, and it does this after the screen lock itself.

You can alt-f2 and enter "r" to restart gnome-shell in the mean time.

**Comment by morealaz** [comment]
same problem for me.

**Comment by xerpi** [comment]
Same here. Sometimes it also gets buggy after a while without even needing to suspend.
Also, my logs are spammed with those messages:
`des 09 08:24:18 sergi-x230 gnome-shell[709]: JS ERROR: Error: Object Gio.Settings (0x55f1f11e3080), has been already deallocated - impossible to acces
                                             taskbarAppIcon<._setIconStyle@/home/xerpi/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.gith
                                             wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                             taskbarAppIcon<._displayProperIndicator@/home/xerpi/.local/share/gnome-shell/extensions/dash-to-panel@jde
                                             wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                             taskbarAppIcon<._onFocusAppChanged@/home/xerpi/.local/share/gnome-shell/extensions/dash-to-panel@jderose9
                                             wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
`
Which make the battery drain very fast.
I wish they rewrote GNOME Shell and all the extensions in C instead of using the shitty Javascript.

**Comment by trougnouf** [comment]
Same, I get

`[836]: JS ERROR: Error: Object Gio.Setti
                                               taskbarAppIcon<._setIconStyle@/us
                                               wrapper@resource:///org/gnome/gjs
                                               taskbarAppIcon<._displayProperInd
                                               wrapper@resource:///org/gnome/gjs
                                               taskbarAppIcon<._onFocusAppChange
                                               wrapper@resource:///org/gnome/gjs
`

**Comment by bryce-lynch** [comment]
Same... a series of:
```
gnome-shell[679]: JS ERROR: Error: Object Gio.Settings (0x559c7ff7d4d0), has been already deallocated - impossible to access to it. This might be cause
                                        taskbarAppIcon<._displayProperIndicator@/home/system/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.j
                                        wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                        taskbarAppIcon<._onFocusAppChanged@/home/system/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:403
                                        wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                        activateWindow@resource:///org/gnome/shell/ui/main.js:544:9
                                        WindowSwitcherPopup<._finish@resource:///org/gnome/shell/ui/altTab.js:556:9
                                        wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                        SwitcherPopup<._keyReleaseEvent@resource:///org/gnome/shell/ui/switcherPopup.js:206:17
                                        wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
```

and also:
```
gnome-shell[679]: JS ERROR: Error calling onComplete: Error: Object Shell.GenericContainer (0x559c824f17e0), has been already finalized. Impossible to 
                                        _resetTweenState@resource:///org/gnome/shell/ui/tweener.js:73:9
                                        _tweenCompleted@resource:///org/gnome/shell/ui/tweener.js:105:9
                                        _addHandler/params[name]@resource:///org/gnome/shell/ui/tweener.js:92:13
                                        _callOnFunction@resource:///org/gnome/gjs/modules/tweener/tweener.js:203:13
                                        _updateTweenByIndex@resource:///org/gnome/gjs/modules/tweener/tweener.js:332:9
                                        _updateTweens@resource:///org/gnome/gjs/modules/tweener/tweener.js:345:18
                                        _onEnterFrame@resource:///org/gnome/gjs/modules/tweener/tweener.js:360:10
                                        _emit@resource:///org/gnome/gjs/modules/signals.js:126:27
                                        ClutterFrameTicker<._onNewFrame@resource:///org/gnome/shell/ui/tweener.js:208:9
                                        wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                        ClutterFrameTicker<._init/<@resource:///org/gnome/shell/ui/tweener.js:183:17
```

**Comment by morealaz** [comment]
It was due to a bug in gjs which are fixed in a recent commit. it is already fixed in Arch. just need to update your system.

**Comment by sam3d** [comment]
Originally downgraded a few hours ago using the fantastic downgrade [<sup>`aur`</sup>](https://aur.archlinux.org/packages/downgrade/) package to `gjs 1.50` from `gjs 1.51` (the erroneous package).

God I love Arch.

**Comment by bryce-lynch** [comment]
Confirmed. Upgraded to gjs 1.50.2-1, stable panel and no more errors in journalctl.
