### ISSUE TITLE
[Feature Request] Bottom/Top Right Notifications

### ISSUE THREAD

**Issue by alex285** [jderose9/dash-to-panel#301]
when you have the panel in bottom, the notifications area (inside Calendar) are on the **bottom right**, when you set panel in top, the notification area is on **top right**

however the Shell notification popup still comes out from center top. i dont really mind the inconsistency issue (specially when we have a bottom panel, so the popup comes out from nowhere!), but this centered popup is really annoying

is it possible to force it, on top or bottom right, depending Dash to Panel position?

**Comment by bil-elmoussaoui** [comment]
You can use https://extensions.gnome.org/extension/708/panel-osd/ which does exactly the thing you want

**Comment by alex285** [comment]
@bil-elmoussaoui thank you! i will try that! however i prefer to leave this report open, because perhaps that option should be integrated in Dash To Panel extension?

**Comment by greatquux** [comment]
Actually it would be best to leave it as a separate extension since the code that does this in panel-osd (which is a good extension I use all the time) is already written and debugged - and unfortunately due to the way GNOME extensions work, sometimes bugs can crash the entire X session and cause lost work!

**Comment by alex285** [comment]
@greatquux if left as separated extension, another solution could be to add a reference to it inside the "About"? 

i use Dash to Panel since day one, and i find the center top notifications very annoying, but i didnt know about Panel-OSD extension! which i havent tried yet, but i hope it will work nice!

**Comment by bil-elmoussaoui** [comment]
It's already mentioned on the readme, FAQ section.

**Comment by alex285** [comment]
@bil-elmoussaoui oh, right! well, in this case it is fine by me, so i close that!
