### ISSUE TITLE
Some applications cause icon delay

### ISSUE THREAD

**Issue by Richy91** [jderose9/dash-to-panel#302]
Some applications can cause icon delay when opening/closing applications. I have noticed that if you open code::blocks IDE then icons start to delay for all applications and this is log output. Happens every time.

_queueBeforeRedraw/<@resource:///org/gnome/shell/ui/main.js:579
_runBeforeRedrawQueue@resource:///org/gnome/shell/ui/main.js:570
_runDeferredWork@resource:///org/gnome/shell/ui/main.js:555
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
taskbar<._redisplay@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/taskbar.js:691
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
taskbar<.sortAppsCompareFunction@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/taskbar.js:685
(gnome-shell:1569): Gjs-WARNING **: JS ERROR: TypeError: windowA is undefined

The same happens if you have nautilus added to favourites(panel) if you open any application and then open nautilus from favourites(panel), then icons start to delay for every application which leads to issue where there is no icons showing up after supend. 
If you open nautilus from menu(i am using arc-menu) or just nautilus from favourites, then everything is OK.

There seems to be no connection between themes. It happens with default themes and with other themes ( in my case arc-themes)

I must say that this is very good extension for gnome and it would be nice to see thiss issue fixed. 

Using ubuntu gnome 16.04
dash-to-panel version v11

**Comment by Nobelix** [comment]
Same problem.
Ubuntu 16.04

**Comment by jderose9** [comment]
Do you mind to try latest `master`? Thanks!

**Comment by Richy91** [comment]
I tried on 16.04 and i could not get it to work. Panel shows, but there is no favourite icons and if i open any application it doesn't show it either.

I tried it on ubuntu 18.04 and everything seems to work good and there is no icon delaying at least for me.

**Comment by jderose9** [comment]
@charlesg99 Fixed the regression for 16.04. Do you mind to pull the newest commits and give it a shot again? Thanks!

**Comment by Richy91** [comment]
@jderose9 It works now and there is no icon delay! Thank you!
But i noticed that with master version Arc-Menu search doesn't work anymore! It works with v11.

**Comment by jderose9** [comment]
@Richy91 What issue are you having? I installed Arc Menu and can open the menu and use the search box at the bottom left to filter the results. Is this what you mean?

**Comment by Richy91** [comment]
@jderose9 Yes that is what i mean! Arc-menu works for 16.04, but only search doesn't.
On 18.04 (GNOME 3.26.2) everything works great!

**Comment by jderose9** [comment]
This should be resolved, now.. closing. Thanks guys!
