### ISSUE TITLE
Show Desktop button too narrow

### ISSUE THREAD

**Issue by leebickmtu** [jderose9/dash-to-panel#305]
On a dual monitor setup the Show Desktop button is quite hard to hit because it is so narrow (4px) and the mouse can cross to the second monitor while trying to get on it. Single monitor you get the help of the screen edge.

Please add a configuration on the Show Desktop button to set it's width. Or at least make the button wider. I think double (8px) would appropriate even for single monitor setups. Would be about the width of the Windows 10 equivalent button.

**Comment by jderose9** [comment]
Thanks to @charlesg99 for adding this configuration option!
