### ISSUE TITLE
Collaborative Work ! 

### ISSUE THREAD

**Issue by LinxGem33** [jderose9/dash-to-panel#31]
### Hi jderose9

I recently came across your extension dash-to-panel, fantastic job by the way.
I’m the developer of OSX-Arc collection and I’m currently working on a menu for Gnome 3 based on the zorinOS menu I was wondering if you would be interested in collaborating on this project I’ve made a small start so far but would be nice to have an extra pair of eyes on this as JavaScript is not my native programming language I’m doing OK but slower than what Id like :) (I’m from a computer science background).

**Link to the project -**[OSX-Arc Menu](https://github.com/LinxGem33/OSX-Arc-Menu)

Kind Regards - _LinxGem33_

**Comment by Ixoos** [comment]
Hi, im using Zorin menu now but I don't like few things about it, so i'm intrested in your extension, im not very good at javascript but i can help and I can give you a few ideas and test the extension.

**Comment by LinxGem33** [comment]
@Ixoos 

Thank you that would be appreciated I will almost certainly need testers, just add yourself to the project and let me know what you think ideas etc.

Kind regards LinxGem33

**Comment by jderose9** [comment]
@LinxGem33 I'm pretty happy with Gno-menu (Zorin menu is a stripped down for of Gno-menu), so I probably won't squeeze out time to contribute code for another menu. But, I'll be happy to take a look and review when you are ready. Good luck and thanks!

**Comment by LinxGem33** [comment]
@jderose9 

appreciate the feed back Ive set a date for February 25th for the 1st alpha release so if you don't mind having look at the code just before release it would be much appreciated and thank you for taking the time.

regards LinxGem33

**Comment by jderose9** [comment]
Hi, I'm going to close this just not to muddy by todo list but feel free to post back your progress. Thanks!

**Comment by LinxGem33** [comment]
@jderose9 

I’m pleased to announce that Arc Menu is now at version 1 and awaiting code review on extensions.gnome.org i would really appreciate it if you could take a quick look at the code and let me know if I’ve missed anything or overlooked something.

kind regards

**Comment by jderose9** [comment]
Looks awesome! Good work. The only issue I found was that when using the Arc theme, the buttons are rendered outside of the menu. If I switch to the Default theme, that doesn't happen though.

![screenshot from 2017-05-21 13-51-47](https://cloud.githubusercontent.com/assets/2118702/26337646/18e8f3fe-3f48-11e7-8b37-6edfb78e0407.png)

**Comment by LinxGem33** [comment]
@jderose9 

appreciate the feed back, the extension is now on extensions.gnome.org and people have commented already how this works well with your extension, regarding the arc theme i think its a css styling issue as my own themes i develop (OSX Arc Collection) which are based on arc work fine but that’s because i have re-designed the shell theme from the ground up, anyway thank you so much for taking the time to review my code its much appreciated.

kind regards
