### ISSUE TITLE
Lag after moving mouse rapidly over app icons on v10+

### ISSUE THREAD

**Issue by lckjosh** [jderose9/dash-to-panel#310]
Ubuntu 17.10, Gnome 3.26.2

After hovering and rapidly moving my mouse side to side over favourite apps icons, over time gnome-shell animations (e.g. moving of windows, opening apps menu) start to drop frames. Issue is only present on v10 and above. Gnome shell reload with ALT+F2+r+ENTER makes the lag go away temporarily, only for it to come back again. Currently using v9 with no such issue. 

System specs: 
CPU: i3-4170
RAM: 8gb DDR3
GPU: Radeon R7 250

**Comment by lckjosh** [comment]
Update: Issue seems to be gone with latest master.

**Comment by jderose9** [comment]
Glad to hear! I'll close this one, but feel free to report back if it re-appears.
