### ISSUE TITLE
show notification count or a red dot for the running apps

### ISSUE THREAD

**Issue by krasi-georgiev** [jderose9/dash-to-panel#311]
probably has already been asked,but couldn't  find any existing issue.

moving form OSX I thing the notification  count or at just a visual icon change (red dot) .
Skype - messages count
Email - unread emails
Riot - new message

Would you consider adding this in your road-map?

**Comment by NecroMortis** [comment]
It would be nice. Also, telegram, pidgin, transmission and other notifications.

**Comment by jderose9** [comment]
Thanks! This will be pulled in whenever #98 is completed. Thanks!

**Comment by krasi-georgiev** [comment]
@jderose9 aren't these different? 
one is for notification count and the other is for download progress.

**Comment by jderose9** [comment]
The launcherAPI.js added to dash-to-dock handles both progress and counts.

**Comment by krasi-georgiev** [comment]
ooh , that is amazing ,thanks
 really exited to give it a try.

**Comment by NecroMortis** [comment]
I do not need progress or quantity. I need the very fact of the message. When I went to make coffee, coming back I do not see the notification. I want it to look like in Windows (2 pictures) or at least repaint the point (3 picture).
![image](https://user-images.githubusercontent.com/20347108/35393400-89519016-01ed-11e8-9ca2-fd72f9119a01.png)

**Comment by jderose9** [comment]
@NecroMortis Could you open a separate issue for this? Thanks.

**Comment by NecroMortis** [comment]
It's not a issue. This is a wish for future development :)

**Comment by jderose9** [comment]
@NecroMortis I understand. Github calls them all "issues" but I will tag as an Enhancement.
