### ISSUE TITLE
windows preview (and peek) on hover

### ISSUE THREAD

**Issue by dln949** [jderose9/dash-to-panel#318]
Is there a way to enable just that feature (in addition to keeping the "All Windows" context menu item), and not the rest of Dash to Panel?  I am looking for a way to have this feature work on the icons in the standard dock in Ubuntu 17.10 (xorg), gnome 3.26.2.

**Comment by franglais125** [comment]
The "standard" Ubuntu dock is a slightly modified dash-to-dock. Perhaps you can have a look at this PR: https://github.com/micheleg/dash-to-dock/pull/574

Testing and feedback are appreciated!

**Comment by dln949** [comment]
Thank you, I will look into that.
