### ISSUE TITLE
Updated translations for v12

### ISSUE THREAD

**Issue by jderose9** [jderose9/dash-to-panel#323]
If anyone cares to submit updated translations, I'm planning to release v12 in a about a week. Otherwise, they will get picked up next time. Thank you very much for the effort.

@frnogueira @zeten30 @franglais125 @LaurentTreguier @SolarLiner @elsieholmes @hosiet @jonnius  @urbalazs @pappfer @crayxt @pkomur @AlexGluck

**Comment by AlexGluck** [comment]
Where is pot file?

**Comment by hosiet** [comment]
@AlexGluck Consider utilizing the Makefile. `make potfile` will regenerate the pot file and a following `make mergepo` will help you with `msgmerge` task.

**Comment by AlexGluck** [comment]
@hosiet thx, all work.

**Comment by zeten30** [comment]
@jderose9 I'll take care of cs_CZ. Thx for notice 👍

**Comment by AlexGluck** [comment]
#326 new translation

**Comment by urbalazs** [comment]
Hungarian is also updated: https://github.com/jderose9/dash-to-panel/pull/325

**Comment by SolarLiner** [comment]
I'm working on the French one.

**Comment by crayxt** [comment]
Thanks for heads up,
Kazakh translation submitted https://github.com/jderose9/dash-to-panel/pull/330

**Comment by franglais125** [comment]
Done Spanish! https://github.com/jderose9/dash-to-panel/pull/332

**Comment by pkomur** [comment]
Polish translation also done! #333

**Comment by jonnius** [comment]
German translation here #337

**Comment by AlexGluck** [comment]
Week ago  i see v12 release and it's rollback, anybody knows about release?

**Comment by jderose9** [comment]
Thanks all! v12 has been tagged and uploaded to extensions.gnome.org.
