### ISSUE TITLE
Problem in Fedora 25

### ISSUE THREAD

**Issue by andresFR94** [jderose9/dash-to-panel#33]
After installing the extension, in tweak tools, the extension tells me, "Error loading the extension". I have uninstalled it several times. Then, he tells me the following error:

  ReferenceError: Config is not defined

Stack trace:
  InitTranslations @ / home / killer / .local / share / gnome-shell / extensions / dash-to-panel @ jderose9.github.com / convenience.js: 50
  Init @ / home / killer / .local / share / gnome-shell / extensions / dash-to-panel @ jderose9.github.com / prefs.js: 401
  Application <._ getExtensionPrefsModule @ resource: ///org/gnome/shell/extensionPrefs/main.js: 75
  Wrapper @ resource: ///org/gnome/gjs/modules/lang.js: 178
  Application <._ selectExtension @ resource: ///org/gnome/shell/extensionPrefs/main.js: 89
  Wrapper @ resource: ///org/gnome/gjs/modules/lang.js: 178
  Application <._ onCommandLine @ resource: ///org/gnome/shell/extensionPrefs/main.js: 239
  Wrapper @ resource: ///org/gnome/gjs/modules/lang.js: 178
  Main @ resource: ///org/gnome/shell/extensionPrefs/main.js: 377
  @ <Main>: 1

**Comment by sbungert** [comment]
I get this on UbuntuGnome 16.10 installing via zip file in Tweak Tool

**Comment by andresFR94** [comment]
When I try to install it via ZIP file, Notifications tell me "extension not valid"

**Comment by sbungert** [comment]
I can install the zip with the tweak tool, but when I click settings for the extension on the tweak tool's extensions page the above error appears in a window instead of showing the settings. Also the extension is not working. There is no change to the dash or the panel.

**Comment by jderose9** [comment]
Where are you guys getting a zip file from? If you just download the zip of the the unbuilt code from github you will need to run "make install" in the folder you extract the zip to. That will build the settings schema and copy it to the proper directory.

**Comment by sbungert** [comment]
Yes, from github. Ok I shall try later to run make install. Sorry I overlooked that on the homepage. I didn't think I needed to do that if I was using a zip.

**Comment by andresFR94** [comment]
I followed the steps they recommend (including make and make install), when I reboot the computer I get the error metered at the beginning

**Comment by jderose9** [comment]
I found a missing import statement for Config which is what is complained about in the error message - odd that only some people are observing the issue. Can you grab the newest code and give it a shot again?

**Comment by andresFR94** [comment]
![aa2](https://cloud.githubusercontent.com/assets/25138525/22038319/6880dfe8-dcd9-11e6-9501-05502e353f47.png)
![aa1](https://cloud.githubusercontent.com/assets/25138525/22038320/68863cd6-dcd9-11e6-9170-6e70f88fc200.png)

**Comment by andresFR94** [comment]
I just did the installation again and continued the same problem, it's rare.

**Comment by jderose9** [comment]
@andresFR94 Do you mind to share screenshots of the contents of these folders:
~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com
~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas

And the contents of:
~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/metadata.json (specifically the version string)
~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js (specifically the section of import statements after the licensing comments)

**Comment by andresFR94** [comment]
It's ok the following images?

![bb1](https://cloud.githubusercontent.com/assets/25138525/22039430/0901a796-dcde-11e6-8619-b274aef87411.png)
![bb2](https://cloud.githubusercontent.com/assets/25138525/22039431/09090a7c-dcde-11e6-9dc3-239c6491945b.png)

**Comment by sbungert** [comment]
I could use the latest version via git. Using the zip though didn't work. The out put from the terminal said something about the directory not being a git repository.

**Comment by jderose9** [comment]
@sbungert Awesome! If you download the zip file, you just need to "make install". The "git clone ...." line is the same thing as downloading the zip and extracting it to a folder. So just skip that if you use the zip.

@andresFR94 Ok so I think you didn't install this properly still as you should have gschemas.compiled in schemas folder which is the output from make. Go into the folder that you either git cloned to or unzipped to and type "make install". Then reload the gnome shell with Alt-F2 > Then type "r" and hit enter (Xorg) or log out/back in (Wayland).

I guess the README can use some improvement, but this will all be unnecessary once the extension gets reviewed for gnome.org.

**Comment by andresFR94** [comment]
I did it!!!
First:
1. Download the zip and unzip it
2. I moved to the unzipped folder
3. I only applied "make install"
4. reboot
And .... voilà, looks great. I will prove it to see how

Thank you very much for your help and time, greetings from Chile


![12](https://cloud.githubusercontent.com/assets/25138525/22040932/9951a17a-dce3-11e6-9aa9-72312c9af6d4.png)

**Comment by jderose9** [comment]
@andresFR94 Awesome!! glad you got it. Love the background!

**Comment by andresFR94** [comment]
Thanks, and keep up with your amazing project :)

**Comment by jderose9** [comment]
Anyone still having issues or can I close? If you are stilling having trouble installing it, the extension is now available on gnome.org.

https://extensions.gnome.org/extension/1160/dash-to-panel/

If you've installed from github you will need to Remove in Tweak Tool and reinstall from there to get the automated updates. Thanks!
