### ISSUE TITLE
Lost binding to "Show Applications"

### ISSUE THREAD

**Issue by rypz79** [jderose9/dash-to-panel#334]
Now Left Super/Win Key is binded to "Activities". 
I cannot re-bind it or any other key to "Show Applications".
I tried GNOME tweaks - > Keyboard & Mouse - > Additional Layout Options but didn't find any fix for it.

Thanks

**Comment by jderose9** [comment]
Hi! I may be misunderstanding, but I don't think this question is related to the dash-to-panel extension? As far as I know, you can't rebind the Super key in Gnome. The best you can do is Super+<another key>.
