### ISSUE TITLE
Move lockscreen top panel to bottom

### ISSUE THREAD

**Issue by nexfwall** [jderose9/dash-to-panel#339]
Panel with network status indicators on screensaver and lock screen is on top. While Dash To Panel moves panel to bottom by default.

This makes Dash To Panel look like an unnatural ugly hack, if you are using lockscreens. Maybe there is a some way to move it to bottom? And make it look like it's meant to be there. In sync with panel.

Pictures:
![Screensaver](https://user-images.githubusercontent.com/8678891/36060181-6d92b55c-0e55-11e8-953c-1b800a3a3440.jpg)
![Lockscreen password prompt](https://user-images.githubusercontent.com/8678891/36060183-70ca4e38-0e55-11e8-89f3-e9f060ae4f6d.jpg)
_I can't make screenshots of lockscreen. So I've used my phone to picture that. Sorry._
![Desktop screenshot](https://user-images.githubusercontent.com/8678891/36060184-73f8aa00-0e55-11e8-9977-7dd269b6fcc5.png)

_P.S. Sorry, an accidental Ctrl+Enter was. So instead of composing an issue I needed to fast-OMG-edit it on the fly._

**Comment by jderose9** [comment]
Unfortunately, there isn't anything that can be done to resolve this. Gnome disables all extensions when the lock screen appears, and re-enables them when unlocking.
