### ISSUE TITLE
Reposition exit button on preview

### ISSUE THREAD

**Issue by z0m8i3** [jderose9/dash-to-panel#341]
![dashtopanelprev](https://user-images.githubusercontent.com/33108490/36231826-1c349128-11a5-11e8-8719-efbd67ca234e.png)

This may be related to #156 is there an option I may have overlooked to put the exit/close button back into the upper corner?

**Comment by z0m8i3** [comment]
I suspect this was a session bug; today the close button is back in the upper right corner.

**Comment by jderose9** [comment]
Odd.. glad you got it resolved. It definitely should appear in the corner and not in the center. Thanks for reporting back!
