### ISSUE TITLE
Panel hides from the desktop itself

### ISSUE THREAD

**Issue by nunocastromartins** [jderose9/dash-to-panel#356]
Hi! First of all, thank you for your work!

This issue is related to the new functionality developed as a result of #41 (add intellihide behaviour to panel).
I found a minor issue when the show icons on desktop setting is set (on the tweak tool):

![screenshot from 2018-03-15 11-49-54](https://user-images.githubusercontent.com/8314616/37461696-21e547a8-2847-11e8-80c0-341c3553ca21.png)

The issue is that the desktop itself seems to behave as a window, i.e. if I "focus" it (click on the background, for instance) with the "only hide from focused windows" setting set, the extension hides the panel. I believe this is unintended behaviour.

Once again, thank you all for your work!

**Comment by charlesg99** [comment]
Hey thanks a lot for the report and tests! I could reproduce the issue and this is indeed unintended. Cheers

**Comment by charlesg99** [comment]
Hey nunocastromartins, would you mind updating to the latest master and see if the merged fix resolves the issue on you end? Thanks!

**Comment by nunocastromartins** [comment]
I'll give it a go on Monday; though I trust that you did a wonderful job fixing it, so feel free to close the issue (whoever can do that)!

Otherwise I'll close it as soon as I get to try it. Thank you for the quick fix!

**Comment by nunocastromartins** [comment]
Sorry for the delay, it seems to be fixed!
Once again, thank you for your work!
