### ISSUE TITLE
Question: Show Desktop function

### ISSUE THREAD

**Issue by JollyDevelopment** [jderose9/dash-to-panel#36]
Are there any plans to implement a "Show Desktop" button? I find that a very useful function of the "TaskBar" extension (https://github.com/zpydr/gnome-shell-extension-taskbar), and would love to see that available in dash-to-panel.

**Comment by jderose9** [comment]
Yes, I would like to add this feature. Some input on where/how it should be presented would be welcome. I was personally hoping to see it appear in a more condensed manner than taking up a whole application icon spot.

**Comment by Ixoos** [comment]
For "show desktop" im using custom hot corner extension. https://extensions.gnome.org/extension/1037/customcorner/

**Comment by JollyDevelopment** [comment]
How about as a right-click on the "Show Applications" icon? I know bupkiss about JS, but presumably the icon area is listening for left-clicks. How difficult would it be to have it listen for right-clicks or middle-clicks and then minimize all the active windows to the panel?

**Comment by devfull** [comment]
Since only applications icons are shown, there is enough place for it on the panel and it won't hurt to add "one more" icon. May be right to application launcher.

**Comment by kelunik** [comment]
Maybe Windows can be some inspiration with its hot bottom-left corner, which is also a button at the same time.

**Comment by jderose9** [comment]
Well I implemented the Windows style where there's a very thin button on the right minimizes/restores, I'm not sure I like the button appearance though.

![screenshot from 2017-02-28 20-32-57](https://cloud.githubusercontent.com/assets/2118702/23442204/3097bf24-fdf5-11e6-851d-301b8a960f2b.png)

What do you think?

The other thought I had was to add this icon to the tray area, for instance to the left of the power menu and clock?

![screenshot from 2017-02-28 20-34-41](https://cloud.githubusercontent.com/assets/2118702/23442258/73fc62c4-fdf5-11e6-9d2a-57c81f849157.png)

This would be able to be disabled with a config setting.

.. And if one of those are implemented, does it still make sense to have the Show Apps right click minimize too? Or would that be better used for something like opening the settings?

**Comment by jderose9** [comment]
I ended up going with the windows-style thin button on the right side for now. Down the road we could add different type of styles or icons but the minimize/restore functionality is in there at least. It can be turned on/off in the settings. Here's a pic:

![screenshot from 2017-02-28 20-32-57](https://cloud.githubusercontent.com/assets/2118702/23445413/25fa1e22-fe09-11e6-814d-ef1b9a72d051.png)

**Comment by cra0zy** [comment]
It does hides all the windows and shows desktop... including desktop icons as well :D Yes, that is a bug.

**Comment by jderose9** [comment]
I thought you just wanted to look at your pretty wallpaper :)

Give it a shot now.

**Comment by cra0zy** [comment]
Works \o/
