### ISSUE TITLE
Setting for Preview timeout on icon enter

### ISSUE THREAD

**Issue by AlexWayfer** [jderose9/dash-to-panel#367]
Hello!

I found "Preview timeout on icon leave" in "Fine-tune Advanced", but I didn't found "Preview timeout on icon enter". It appears too fast for me.

Thank you.

**Comment by jderose9** [comment]
On the behavior tab, click the gear next to "Show window previews on hover". Thanks!

![image](https://user-images.githubusercontent.com/2118702/37927057-feeac390-3106-11e8-8d26-7b70e08b6a48.png)

**Comment by AlexWayfer** [comment]
Oh, thank you! I'm sorry.
