### ISSUE TITLE
Switch workspace by scrolling on the panel

### ISSUE THREAD

**Issue by elsieholmes** [jderose9/dash-to-panel#37]
Hello! It'd be great for former dash to dock users, especially paranoid ones if there was an option to switch workspace by scrolling on the panel.

Many thanks.

**Comment by jderose9** [comment]
Does this extension do what you are looking for?
https://extensions.gnome.org/extension/1096/scroll-panel/

**Comment by elsieholmes** [comment]
@jderose9 no cause it just doesn't work.
P.S. I'm running Gnome 3.20.4 on OpenSUSE 42.2

**Comment by benfairless** [comment]
The following extension works for me on Fedora 25 / 3.22.2 perfectly with the same behaviour as in Dash2Dock:

[Top Panel Workspace Scroll](https://extensions.gnome.org/extension/701/top-panel-workspace-scroll/)

**Comment by elsieholmes** [comment]
@benfairless gramercy :) Works just fine.
