### ISSUE TITLE
Ubuntu 18.04, dual monitor(multiple monitor) panel

### ISSUE THREAD

**Issue by khpark0203** [jderose9/dash-to-panel#372]
I use Ubuntu 18.04 and set dual monitor(multiple monitor).
Ubuntu 18.04 have only one top bar.
So, I can show panel only main monitor.
I want to show panel all monitor.
For resolving this problem, I installed "gnome-extension-multi-monitor" but "multi-monitor" show original top bar in secondary monitor.
How I resolve this problem?
Thank you

**Comment by jderose9** [comment]
Unfortunately, you can't right now. However, you can subscribe to #35 for updates on when this gets implemented.

**Comment by wesleytao** [comment]
I met the same problem.

**Comment by p3le** [comment]
Hey, I've installed update from 16.04 to 18.04 and I'm using dual-monitor setup. First of all I had 2nd monitor set as primary, so I've changed that but top bar was still set incorrectly. Then I've changed my setup to use single monitor in Ubuntu settings, top bar switched to correct screen and then I've changed again to use dual-monitor and now everything is ok. Try it in that way, should be good.

**Comment by khbehrens** [comment]
Does not seem to work on mirrored monitors.

73 & Cheers,
Ken Behrens
IBM Certified Advanced Application Developer
MicroBlue Software, LLC 
KB0YLN
E-mail: khbehrens@MicroBlueSoftware.com
Web site:  http://www.MicroBlueSoftware.com

**Comment by jderose9** [comment]
This has now been implemented in dash-to-panel.  Although an official release has not yet been completed, you can install the master branch from GitHub to use it.
