### ISSUE TITLE
Running indicator width isn't wide enough to be realized at a glance but Win10 task bar is!

### ISSUE THREAD

**Issue by Bonsitar** [jderose9/dash-to-panel#373]
Hi guys.
I found a problem with; running indicator applications in dash to panel that isn't as easy as Win10 taskbar and can't be realized at a glance if several windows of an application open in desktop and one of them is focused; this problem get worse when `Running indicator style (focused app)` is setting to `Metro` and `Running indicator style (unfocused app)` is setting to `Dashes` in dash-to-panel extension settings! 
e.g.
In Windows:
![customize-windows-10-taskbar-pic6 1_thumb](https://user-images.githubusercontent.com/35845718/38155714-6ecef958-348e-11e8-8466-8433737e94b0.jpg)
See file-explorer's indicator (sixth icon from left) looks in taskbar that has two opened window and one is focused!
or;
![remove-search-box-from-windows-10-taskbar](https://user-images.githubusercontent.com/35845718/38155904-9dad843c-348f-11e8-9f9c-12a8ec758765.png)
see how file-explorer's indicator (first icon from right) looks when two windows of it is opened and one is focused!

Now see gnome-natilus's indicator in dash-to-panel looks like when two window of gnome-natilus is opened and one is focused (with that configurations I've explained at first),
e.g.
![image](https://user-images.githubusercontent.com/35845718/38156018-56ad2ff0-3490-11e8-9c4e-fc145f3ce30a.png)
Is not as well and easy as Win10 taskbar indicators, right?

On the other hand when **more than two** windows of an app is opened and one is focused, that app's indicator just looks like showing **two** windows of that app is opened!
e.g.
![image](https://user-images.githubusercontent.com/35845718/38156303-30bb5054-3492-11e8-8a3f-c467c3982f46.png)
(Here there are four opened windows of gnome-natilus and one of them is focused)

Feel free to tell me here if problem is not clear yet or more details needed.

So I think this part of the extension should be worked on it for a better look (because it 's an important subject that users can realize opened add focused window of indicators at a glance!)

Thanks!

**Comment by Bonsitar** [comment]
Oops! since [dash-to-dock.v63](https://micheleg.github.io/dash-to-dock/release/2018/04/02/new-release-v63.htmll) fixed this issue, and as far as I know dash-to-panel extension uses the core of dash-to-dock to show a dock in panel so this issue comes from my bad configure in running indicator styles so I'm sorry to open this issue! [Closing the issue]
Thanks.

**Comment by jderose9** [comment]
I don't know that this should be closed. I don't think dash-to-dock even offers this style and the code isn't automatically merged in or anything. I do think recent tweaks have made the Metro multiple indicator more difficult to see so we should probably try to tweak the opacities to improve it.

Regarding the 3+ windows though - windows doesn't let you know that either, and I tried adding the appearance of more items in the stack, but it just gets too busy, so I'd probably vote in favor of leaving it as-is in that regard. In my personal workflow, I find it important to know that multiple windows of an app are exist as I will need to choose between them when focusing the app, but not all that important as to how many windows are open exactly.

**Comment by Bonsitar** [comment]
@jderose9 so should I reopen this issue? 
As I mentioned this matter just comes from my bad configuration and I am agree with you that's not very important how many window of an app are open and yes! I rechecked dash-to-dock; there is no options like these in dash-to-dock extension, now if you set configuration of extension like; "Running indicator style (focused app)" to "Ciliora" and "Running indicator style (unfocused apps)" to "dashes" so your indicator for that matter should look like this:
![image](https://user-images.githubusercontent.com/35845718/39312448-d73c3a36-4984-11e8-9587-574bf4d1be70.png)
_See the indicator for Mozila-Firefox, It's cool!_
