### ISSUE TITLE
Sometimes thumbnails disappear

### ISSUE THREAD

**Issue by glebsam** [jderose9/dash-to-panel#38]
Sometimes when I mousein to app icon and try to move cursor to thumbnails, they disappears. Please check [the video](https://drive.google.com/open?id=0B-lysEnSSgxLOS1pTWJ1US1jSGs). 

Ubuntu 16.10

Package: gnome-shell                     
Version: 3.22.2-1ubuntu1~ubuntu16.10.1

**Comment by jderose9** [comment]
Thanks so much for reporting this. I'm going to close this one as it is a duplicate of #19, so please hop over there for status updates. Also, if you have familiarity with git and could check out the hoverfix branch and give me some feedback, that would be great.
