### ISSUE TITLE
Make compatible with Drop down terminal

### ISSUE THREAD

**Issue by amankhoza** [jderose9/dash-to-panel#39]
This extension seems to work well with other panel extensions such as Dynamic top bar, but doesn't seem to work with Drop down terminal. Not sure if the issue lies in Drop down terminal or Dash to panel.

https://extensions.gnome.org/extension/442/drop-down-terminal/

**Comment by theneedyguy** [comment]
Is the extension working without Dash-to-Panel installed / activated? It is working for me. Try downloading the Git version of the terminal  and move the drop-down-terminal@gs-extensions.zzrough.org folder to ~/.local/share/gnome-shell/extensions. 
Here is the git: https://github.com/zzrough/gs-extensions-drop-down-terminal/

**Comment by amankhoza** [comment]
Ok so it is working but there is a gap where the the panel should be. If I move the terminal to the bottom then the panel overlaps the terminal. See screenshot: https://www.dropbox.com/s/gizlbewktgu62hw/Screenshot%20from%202017-01-23%2008-20-45.png?dl=0

**Comment by theneedyguy** [comment]
I don't know how to fix your problem. I run my panel on top so naturally your problem doesn't occur for me. Might be an issue you need to resolve with the author of the drop-down-terminal.

**Comment by jderose9** [comment]
I looked briefly at the Drop Down Terminal code and I think it would be best resolved in that extension. I assume Drop Down Terminal would have the same issue with other extensions that set the panel anchor point as I don't think it is currently using it to calculate the terminal position.

That said, I'm not seeing any overlap when using both Dash-To-Panel and Drop Down Terminal from the bottom positions. I do see the gap when the panel is at the bottom and the terminal is in top, left or right positions.

**Comment by amankhoza** [comment]
When I put the terminal at the bottom, the bottom of the terminal is cut off by the panel (see screenshot), but I think you're right it would be best resolved in the other extension. I'll contact the dev of the Drop down terminal extension. 

https://www.dropbox.com/s/1lzxskwerw0ea8s/Screenshot%20from%202017-01-23%2017-20-30.png?dl=0

**Comment by amankhoza** [comment]
I've fixed my issue by making a small tweak in the Drop down terminal code to remove the height of the panel which is added on the top, so all is working well now.

**Comment by brandleesee** [comment]
@amankhoza can you please share the code you tweaked for others who may encounter the same problem you had?

**Comment by amankhoza** [comment]
Yep sure so for anyone else who encounters this, just edit extension.js for Drop Down Terminal (located in `~/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extensions.zzrough.org/`), and change the commented out line to the line below:
```
case TOP_EDGE:
    this._windowX = x1;
    //this._windowY = panelBox.y == y1 ? y1 + panelBox.height: y1;
    this._windowY = y1; // hack for dash to panel 
    this._windowWidth = screenWidth;
    this._windowHeight = this._evaluateSizeSpec(sizeSpec, true);
    break;
```

**Comment by brandleesee** [comment]
Cheers, @amankhoza!
