### ISSUE TITLE
High gnome-shell CPU consumption with topicons-plus

### ISSUE THREAD

**Issue by phocean** [jderose9/dash-to-panel#4]
On my environment (Fedora 25/Wayland), the extension causes a high gnome-shell CPU consumption (almost 100% on one core) as long as it is enabled with the Topicons-plus extension (I am the author of this extension).

A quick guess is that it might be competing on a similar setting.

Otherwise: very nice extension, I would love to use it. Thank you ;-)

**Comment by diazbastian** [comment]
@phocean Maybe integrate this functionality (top icons plus) to this extension? 
I mean that because of the workflow style that presents this extension, the system tray that brings gnome-shell by default is inappropriate and therefore a functionality like the one offered by topicons can come by default in this extension.

**Comment by jderose9** [comment]
> On my environment (Fedora 25/Wayland), the extension causes a high gnome-shell CPU consumption (almost 100% on one core) as long as it is enabled with the Topicons-plus extension (I am the author of this extension).

@phocean Do you mind to test this? I believe I fixed in 40fb563 in the dev branch. Thank you for bringing it to my attention! BTW Top Icons Plus is a must-have... thank you for your work.

**Comment by phocean** [comment]
Yes, it is fixed. :-)
At least, partially: if I set TopIcons-plus to the center position, it happens again, but it is fine with left and right positions.
Thanks!

**Comment by jderose9** [comment]
Could you test again in the dev branch? Thanks! 40fb563aaea8bf85d7b2ac96674078607bab47bd

**Comment by rhabbachi** [comment]
Hey, I noticed the high CPU usage too. Updating to the latest master seems to have fixed the issue.

**Comment by phocean** [comment]
Yes, problem solved. Thank you!
