### ISSUE TITLE
Bug: Applications not scrollable if "Animate Show Applications" is disabled

### ISSUE THREAD

**Issue by cra0zy** [jderose9/dash-to-panel#40]
Applications not scrollable if "Animate Show Applications" is disabled.

Way to reproduce:
 - go with the mouse to the top left corner or press the Windows key
 - search for some application and launch it
 - open applications menu with the "Show Applications" button that dash to panel provides
 - appliactions are not scrollable

Workaround:
 - go with the mouse to the top left corner or press the Windows key
 - a hide applications animation will occur and now applications can be scrolled again

**Comment by jderose9** [comment]
Thanks for reporting.. I was able to reproduce this.
