### ISSUE TITLE
Allow selection of different "Show Apps" icon in settings UI

### ISSUE THREAD

**Issue by matjaz132** [jderose9/dash-to-panel#43]
Is there anyway I can change the icon for show all applications? I'm using Antergos with Numix square icons.

**Comment by jderose9** [comment]
Currently this comes from your icon theme - the icon named "view-app-grid-symbolic". You could swap out that icon with a new one or override the image path in gnome-shell.css probably. For the future, it wouldn't be a bad idea to add as a configuration option of the extension.

**Comment by matjaz132** [comment]
Ok. I've managed to switch icons. Do you know why it renderes this icon white? I want it to render it in colors.

**Comment by jderose9** [comment]
@ matjaz132 I would guess you are using an svg icon or transparent icon and your theme has styled it to be white. This is all really gnome shell behavior and not related to this extension - it just displays the applications icon which is normally represented in the activities overview on the panel instead. The styling all comes from gnome-shell and your theme.

**Comment by bil-elmoussaoui** [comment]
@jderose9 Is this issue should be really addressed ? for me it's up to the shell theme to to do so :)

**Comment by winuxue** [comment]
is there a way to change that icon from the extension setting?

**Comment by jderose9** [comment]
Not currently, but if someone would like to work in this I will be glad to merge a Pull Request.

**Comment by jderose9** [comment]
Completed by @charlesg99 . Thanks!!
