### ISSUE TITLE
Severe Lag on Specific Hardware while also using Dynamic Panel Transparency extension

### ISSUE THREAD

**Issue by moriel5** [jderose9/dash-to-panel#44]
I am experiencing a severe lag in many functions of GNOME Shell while this extension is enabled.
This occurs though, only on my laptop. On my desktop there are no issues whatsoever.
I have nearly the same software setup on both my laptop and desktop (Solus, GNOME 3.22, extensions, etc.), and I had attempted to disable the other extensions, to make sure that the issue is not because of a compatibility issue with one of the extensions.
The lag is present both on X-Server and Wayland, and had also existed on GNOME 3.20.

My laptop is a Lenovo IdeaPad 300 15", running on an Intel Core i5-6200U without any dedicated GPU's, if that helps.

**Comment by hotice** [comment]
I'm having the same issue running this extension on a pretty old Laptop (Intel Sandybridge graphics; Ubuntu 16.10 64bit, GNOME 3.20), but this is fixed when I disable the "Animate Show Applications" option.

**Comment by moriel5** [comment]
I'll try that workaround, although I like that feature.

**Comment by jderose9** [comment]
Thanks for reporting this. I haven't seen the behavior though despite running on a rather resource constrained VM. Can you explain the nature of the laginess? Is it constant or just when you take certain actions (hovering the preview, clicking an icon, etc)? Is the CPU spiking during lag?

Have you tried Dash-to-dock and do you experience the same lag using that extension instead?

Thanks!

**Comment by moriel5** [comment]
I do not believe that this has anything to do with total system resources utilization, as I had checked with System Monitor, and the usage did not go up during the freeze-up (which was for only about a second or two), despite it already being no more than with Dash-to-Dock instead.


And this does not occour, nor ever happened, with Dash-to-Dock.
I had been using Dash-to-Dock, together with Bottom Panel and the extension that moves the legacy status indicators to the panel (I forget what it is called).

**Comment by jderose9** [comment]
@moriel5 Can you explain this lag or freeze-up? Does it happen randomly or when you take certain actions? Or it is always present? Thanks!

**Comment by moriel5** [comment]
I am glad to help.
As I had mentioned in my previous post, it happens only upon certain actions, and it always happens (aside from the app screen, which very rarely occours).
Only the affected actions stall, the rest of the shell remains responsive.
The duration of the lag only lasts for about a second or two, however it is very noticable.

**Comment by moriel5** [comment]
I am sorry for not being clearer, by "list", I had meant dropdown lists.

**Comment by jderose9** [comment]
@moriel5 so you are saying that you are having this lag elsewhere in gnome shell, but only when this extension is installed?

**Comment by moriel5** [comment]
That is correct.
And I have verified that is not due to incompatibilietes with any other extensions, it only happens on specific hardware.

**Comment by jderose9** [comment]
Are you guys using Dynamic Panel Transparency extension? It was reported in #65 that disabling that extension caused the lag to go away.

**Comment by moriel5** [comment]
Interesting, I'll test it out.
Interestingly, when I had installed a wayland compositor (I forget it's name, will update when on either my laptop or desktop), the issue, while not going away, seemed to have been greatly reduced in the wayland session, although that may have been placebo, so I will need to conduct more thorough tests.

**Comment by jderose9** [comment]
I'm speculating that the panel transparency was causing the icon to be repainted several times and re-triggering the animation to be called. I've tried adding some code to ensure it only goes into the animation code once when the indicator needs to change. There's also two new settings to remove animations which you might want to try on the Fine-Tune tab in the settings. You can see these changes in the current `master` branch. Can you give it a shot?

**Comment by jderose9** [comment]
@groudie has reported on #65 that he experienced the lag with Dynamic Panel Transparency, regardless of whether Dash-to-Panel was enabled. Are you guys definitely experiencing this only when both extensions are enabled together?

**Comment by moriel5** [comment]
Sorry for not having been online for someime.
However, I can say that with the last update (which I had installed on monday, after fixing my desktop and ), the problem had also appeared on my desktop.
However yesterday there was a new update to Dynamic Panel Transparency which fixed the issue on my desktop.
When I'll have time to finish setting up my laptop (My hard drive started failing, so I had to format it. I still need to check if it is still failing, before notifying Lenovo's official importer in my country), I'll try it on my laptop afterwards.

**Comment by jderose9** [comment]
@moriel5 Thanks, please let me know!

**Comment by moriel5** [comment]
I'll be glad to, once I have time to work with my laptop.
Perhaps tonight, although that's a low probability.

**Comment by jderose9** [comment]
As I've heard a few times that this was corrected with the latest Dynamic Panel Transparency update, I'm going to close this one for now. Feel free to post back if you find otherwise! Thanks.
