### ISSUE TITLE
left and right positions

### ISSUE THREAD

**Issue by sonnyp** [jderose9/dash-to-panel#47]
I'd love to use this to replace my left panel ([Dash to Panel](https://extensions.gnome.org/extension/307/dash-to-dock/)) and top bar with a unique left panel.

**Comment by robrobinbin** [comment]
Duplicate #3

**Comment by jderose9** [comment]
I'm sorry - know a lot of people would like this feature.. I just don't think it's reasonable to accomplish given the gnome-shell limitations.

Check my explanation here:
https://github.com/jderose9/dash-to-panel/issues/3#issuecomment-271155455
