### ISSUE TITLE
Swarm Animation is partially disabled

### ISSUE THREAD

**Issue by alex285** [jderose9/dash-to-panel#49]
If we unchecked the "Animate Show Applications" swarm animation 
**will be disabled in case** 
A. We click the 9-dot button
B. We <Super>+A

**Swarm animation wont be disabled in case**
A. We click the 9-dot button when we are in windows overview
B. We press <Esc> to leave application overview

Furthermore in a kinda different bug, swarm animation always starts and ends from the left side, when the 9-dot button is on the bottom

**Comment by jderose9** [comment]
Thanks for reporting this! I was able to reproduce it.

**Comment by jderose9** [comment]
Both issues should be resolved. Do you mind to test? Thanks!

**Comment by alex285** [comment]
nice one!
