### ISSUE TITLE
Quick access to options

### ISSUE THREAD

**Issue by alex285** [jderose9/dash-to-panel#50]
Instead of going to Tweak Tool, finding Dash To Panel extension and then open preferences, can be a "Preferences" menu option when we right click the 9-dot button? Or if someone has disabled it, when we right click somewhere in the empty panel space? 

I think though that the best way is just by right click on 9-dots, rather anywhere on the panel. So if someone has disabled that, perhaps not getting that option is okay

**Comment by jderose9** [comment]
I like the right clicking in the open area - that's consistent with the panels on most other operating system. It could open a popup menu with possibly some other choices as well. It was suggested in #36 to right click the app-grid button to show the desktop (minimize all applications) which I thought was pretty intuitive (left click to open all apps list, right click to minimize all apps) and probably would be used more commonly than the settings.

**Comment by franglais125** [comment]
I think this was implemented for dash-to-dock, but never merged (it was a big change set).

Here is the link to it:
https://github.com/micheleg/dash-to-dock/pull/300/commits/96cca197183e3b2a83c03b19048909758da8b751#diff-1e6c203927a86e652ce89b4b341d783fR168

It is only a part of a big commit! So don't look at all of it :)

**Comment by jderose9** [comment]
@franglais125 I tried that code you are referring to but it caused some exceptions in grabHelper when I would click on say the power menu or clock and they popped up while the right click menu was open on the panel.

**Comment by franglais125** [comment]
I didn't test it myself, but yeah, Dash-to-dock doesn't have as many objects as dash-to-panel. I guess it can get more complicated for this extension.
If I have some time in the future I'll try to look at this, but to be  honest that will probably be in a few months, not anytime soon :(

**Comment by jderose9** [comment]
I think its just not supported to have two pop-ups open. Normally only the actor (typically a button) and it's pop-up receive events when the pop-up is open, but with that code the actor is the whole panel and it has child buttons that have their own pop-ups. Since the other buttons are added by different extensions, it will be difficult to synchronize the pop-ups across them. 

So at this point I think the best route is the right click of the Show Apps button.

**Comment by jderose9** [comment]
I ended up adding this to right click of the Show Apps button as I don't think it can be reasonably added to the panel and have the child widgets function properly due to gnome's focus grabbing behavior.
