### ISSUE TITLE
[Feature request] square focus indication

### ISSUE THREAD

**Issue by devfull** [jderose9/dash-to-panel#52]
I would like to request an additional focus indication for open/active/inactive windows. The bar and dots used now are imo not clear enough, especially the dots (where I have to look closer at the panel to see them).
So I think, a square around the icons is comfortable for the eyes and looks good (my opinion). Am not requesting to replace the one used now, but rather an option to choose which one to use, so that people who like 'the bar/dots' can keep using it.
See screenshot for how it could look like ;)
![screenshot_20170128_145224](https://cloud.githubusercontent.com/assets/20864876/22397079/94aa195c-e569-11e6-888e-4487bb96af1f.png)

**Comment by jderose9** [comment]
Hi, thanks for the feedback. I'm adding your comments to #12 as I'd like to keep all feedback about the running indicators there. Please hop over there for status updates. Thanks!
