### ISSUE TITLE
Feature Request: Show the dock on left/right

### ISSUE THREAD

**Issue by tuxste** [jderose9/dash-to-panel#55]
Hi!
Awesome extension!
Question: Are there any plans to add "show dock" on the right or left side of the screen (like Dash-to-Dock) ? Not only top/bottom.

**Comment by jderose9** [comment]
I'm sorry - know a lot of people would like this feature.. I just don't think it's reasonable to accomplish given the gnome-shell limitations.

Check my explanation here:
https://github.com/jderose9/dash-to-panel/issues/3#issuecomment-271155455
