### ISSUE TITLE
Feature Request: Hide/Show favourites

### ISSUE THREAD

**Issue by Luke-Nukem** [jderose9/dash-to-panel#56]
As per title. This would be handy to show only running tasks.

**Comment by jderose9** [comment]
I'm not opposed to adding this, but wouldn't you just remove all of your favorites? They don't appear elsewhere, right?

**Comment by Luke-Nukem** [comment]
Well that's the thing - if a user is using say, dash-to-dock, or another OSX style panel, then having the favourites is handy to have. Those users can then use the dash-to-panel as a way to keep track of only running windows while the dock is hidden beneath windows.

Another example is using an application list menu that supports listing favourites. Using this in conjunction with dash-to-panel would work well for people who want to retain a minimalist sense.

Sort of seems like just doubling up, but i guess it would have its uses.

**Comment by MartinPL** [comment]
Like OP said pretty decent feature, making with Dash to dock very nice combination :+1: 
img. http://i.imgur.com/dZdMbnQ.png

PS. Thanks for this great extension :beer:

**Comment by LeleDev** [comment]
Totally agree, I'm using both dash to dock and dash to panel too and have exactly the same problem...

**Comment by jderose9** [comment]
Completed by @MartinPL . Thanks so much!
