### ISSUE TITLE
dash-to-panel size in 4K resolution with window scaling set to 2

### ISSUE THREAD

**Issue by RomanShumikhin** [jderose9/dash-to-panel#57]
I am running Antergos Linux (64-bit) with Gnome version 3.22.2 at 4K resolution and I have noticed a bug:

The Panel Size in not set properly when loading the extension if Tweaks -> Windows -> HiDPI -> Window Scaling is set to 2.
I assume that the Panel Size is specified in pixels, so when it is set to 48px it looks like this in 4K (very tiny and looks bad, but that's the correct size).
![dash-to-panel-4k-on-start](https://cloud.githubusercontent.com/assets/426992/22502396/c04e3e90-e810-11e6-8cd9-989a5370f751.png)

But if you restart gnome-shell (by typing 'r' in the "Enter a Command" dialog) the size will still be set to 48px in the settings, but the actual panel size will be 96px, i.e. the panel is automatically applying window scaling to this value.
![dash-to-panel-after-restart](https://cloud.githubusercontent.com/assets/426992/22502422/db24f132-e810-11e6-8e31-0d8c07dfc7ea.png)

It looks much better after the restart, but next time I reboot my machine the panel becomes tiny again.
I think the panel should either apply the scaling from the very beginning or do not apply it to the settings at all.
Current behavior is not consistent.

Thank you very much for the great extension!

**Comment by jderose9** [comment]
Thanks for reporting this. The scaling should always be applied to your selected pixel size (2.0 scaling * 48px = 96px tall panel), so the shell restart behavior is the correct one. I'm guessing there some sort of timing issue on boot where the scaling value is assigned after the extension has already loaded.

**Comment by roaldnefs** [comment]
Experienced the same issue; using a windows scaling factor of 2.0. By setting the panel size 2.0 times as big as I wanted it to be, the panel turned out correct after a reboot.

**Comment by RomanShumikhin** [comment]
@roaldnefs , I am using the same workaround ;) The problem starts manifesting itself when I need to re-enable any of the other extensions or change their settings, sometimes that triggers the scaling in dash-to-panel. I have noticed a similar issue with the mouse cursor, I also set it to 2x, but when dash-to-panel loads and I hover the mouse cursor over it I see that it is super tiny (no scaling applied), the issue disappears after I move the cursor around the screen several times and hover it over the panel again.

**Comment by jderose9** [comment]
I believe I have resolved the issue with regards to the panel size on boot. Would you guys mind to test the dev branch and let me know if it works for you?

I'm not sure what to make of the mouse cursor issue... I don't think I'm seeing that on my end. It only happens when hovering over the panel?

**Comment by roaldnefs** [comment]
Just tested the `dev` branch: the issue regarding the panel size on boot seems to be resolved!

Thanks for fixing the issue on such short notice!

**Comment by RomanShumikhin** [comment]
Thank you very much, @jderose9 ! Just tried dev branch, that fixed the problem. Mouse cursor however is still not updated properly, but that could be a core gnome issue.
I can reproduce the mouse cursor bug almost every boot after doing this:
`gsettings set org.gnome.desktop.interface cursor-size 48`
and rebooting, just hover your mouse over the panel as soon as it loads.

**Comment by jderose9** [comment]
@RomanShumikhin Can you try with this extension disabled? Mousing over the top bar instead?

**Comment by RomanShumikhin** [comment]
@jderose9 , just tried and I am seeing the same mouse cursor problem with dash-to-panel disabled, so it is definitely a core gnome issue. Thanks again!

**Comment by jderose9** [comment]
@RomanShumikhin No prob! I think this is the place to submit gnome bugs if you wish to do that: https://bugzilla.gnome.org/

Thanks to both of you for testing!

**Comment by RomanShumikhin** [comment]
I created a bug report here if anybody is interested https://bugzilla.gnome.org/show_bug.cgi?id=778593
Thank you for a good suggestion, @jderose9 !
