### ISSUE TITLE
Preview should stay a little moment after hovering icon

### ISSUE THREAD

**Issue by Teslator** [jderose9/dash-to-panel#59]
For now a preview is shown when hovering the app icon. It disappear instantly after moving the cursor. For best navigation I would suggest to let the preview a little while after the mouse hover (like 25 or 50ms).

**Comment by jderose9** [comment]
Hi! This is actually already done, in the master branch, as part of #19. It will be available on extensions.gnome.org in v4 which I should be submitting soon. There is a new Advanced menu in the options with a configurable timeout. Thanks !
