### ISSUE TITLE
VPN will not expand

### ISSUE THREAD

**Issue by dbasinge** [jderose9/dash-to-panel#6]
In the status area, VPN list will not expand.

**Comment by jderose9** [comment]
Are you sure this is caused by this extension? Which distro and gnome version are you using? I can't reproduce this.

When you say VPN list, you mean when you click the status menu (network/sound/power) and then click on the network connection and the list of connections expands, correct?

Thanks!

**Comment by dbasinge** [comment]
Fedora 25 with Wayland
Gnome 3.22.2

Everything expand as it should only VPN does not work.

I think what is causing it is due to having a very large set of VPN connections, 36 though Private Internet Access.

**Comment by jderose9** [comment]
Ok, I can reproduce it at least. I had to add like 25 VPN connections before it occurred. It happens on the other extensions that move the panel to the bottom too. I think whatever happens to the layout whenever the entire vertical screen space fills with the vpn list must bomb when the panel is no longer in its default location.

**Comment by Ixoos** [comment]
I have this problem with steam, it's very annoyoing :/

**Comment by jderose9** [comment]
@dbasinge There seems to be a calculation issue with the height, maybe a small rounding issue, causing the height of the submenu to be too large to display on the screen. I've put in a hack around it if you want to give it a shot in `master`.

@lxoos What issue are you having specifically with Steam? Do you mean right clicking the games list on the panel? It seems to work ok for me. Can you try it now and give some more info if it is still occurring? Thanks!

**Comment by dbasinge** [comment]
Looks like it is working for my issue.

**Comment by jderose9** [comment]
@dbasinge Nice, thanks for testing!
