### ISSUE TITLE
Can't click on thumbnails

### ISSUE THREAD

**Issue by onbeskarakterli** [jderose9/dash-to-panel#61]
Thanks for the great extension.

With the latest builds, I can't seem to click on thumbnails anymore. When I hover my cursor over a thumbnail, it disappears. I don't know if this is a removed feature or a bug, but it was very useful when I had 2-3 instances of a program running at the same time or multiple Files, Chromium windows, etc.

Tried the v4 build and the current state of the repo and it doesn't work. It works on v3.

**Comment by jderose9** [comment]
Are you able to try the dev branch and tell me if it is any better? I can walk you through it if you aren't very familiar with git.

**Comment by onbeskarakterli** [comment]
Made a quick search. 

git clone -b dev https://github.com/jderose9/dash-to-panel.git
make
make install

Works fine. 

git clone https://github.com/jderose9/dash-to-panel.git

or

release v4 doesn't. 

Thank you for your help.

**Comment by jderose9** [comment]
Great, dev is the newer code. The fix is in 6fe65f64d40ea3a09f0352d0ed51c73c16814078. I'll merge up to master and submit a new build to gnome.org shortly.

Thanks for testing! Let me know if you discover any new issues with it.

**Comment by jderose9** [comment]
v5 tagged and submitted. Thanks for reporting this issue!

**Comment by jderose9** [comment]
@onbeskarakterli Would you mind to try the latest code in the master branch and make sure your issue hasn't re-appeared? I found one more issue with this (a VERY slim chance that window contents could freeze) and have made another change. Thanks!

**Comment by onbeskarakterli** [comment]
@jderose9 It seems to work fine.
