### ISSUE TITLE
Moving between notifications and settings is laggy

### ISSUE THREAD

**Issue by d9h02f** [jderose9/dash-to-panel#62]
If you click on the clock or on the Wi-Fi/sound/battery/... indicators to make the pop up show up and then move to the indicators or clock respectively, there's a lot of lag on the movement of the cursor. You can see it very clearly if you quickly move back and forth.

**Comment by jderose9** [comment]
Hmm. I have never seen this. So this definitely doesn't happen with this extension disabled?

Could it be the same issue described in #44?

Would you be able to make a screen capture video so I can get a better idea of what is going on?

**Comment by d9h02f** [comment]
It isn't the same as #44, but now that you mention it, there seems to be a slight lag when doing this with the extension disabled. It probably just becomes more apparent because they're placed closed together with this extension.

**Comment by jderose9** [comment]
Ok. Is it ok if I close this and you can enter in the gnome bugzilla? (https://bugzilla.gnome.org/)

**Comment by d9h02f** [comment]
Sure, no problem.
