### ISSUE TITLE
Could not enable the first time before toggling the bottom/top switch

### ISSUE THREAD

**Issue by nekohayo** [jderose9/dash-to-panel#64]
On Fedora 25 with GNOME 3.22.2, no matter what I did this extension didn't want to visibly activate (the extension would activate in gnome-tweak-tool, but do nothing)... until I went into the extension's preferences and changed the position setting from "Bottom" to "Top"; setting it to Top finally made it appear, after which even if I set it back to either bottom or top it would continue showing up.

**Comment by jderose9** [comment]
Weird... haven't seen this. How did you install the extension originally (github, gnome.org, a package manager, etc)?

Are you able to reproduce this if you remove the extension and all of the keys in dconf in /org/gnome/shell/extensions/dash-to-panel/, and then re-install?

**Comment by nekohayo** [comment]
I was installing from https://extensions.gnome.org/extension/1160/dash-to-panel/

Oddly enough, I was not able to reproduce this on another computer... maybe because that one didn't have the "dash to dock" extension installed? Either that or it was some sort of a race condition that manifested itself with my radeon driver but not the intel driver on this 2nd computer... Oh, I hate heisenbugs!

**Comment by jderose9** [comment]
I ended up seeing this myself on a completely different extension. I'm guessing that Gnome occasionally gets into a weird state where it won't load any extensions. I'm going to close this for now as I haven't heard any other reports of this, and I don't really think it is internal to this extension. (And if you are running this extension still, the code that runs after download should be identical to the code run everytime during the login process).

I appreciate the time and effort to report this.. Definitely feel free to get back in touch if you experience it again. Thanks!
