### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by frnogueira** [jderose9/dash-to-panel#66]
Is possible able the option to translations the extension?!

**Comment by jderose9** [comment]
Yes, it's possible. But I only know English :( Are you able to provide a translation? You can make a pot file with "make potfile" (it outputs in po folder). If you need more detailed instructions, let me know.

**Comment by frnogueira** [comment]
I can translate to Brazilian Portuguese...

**Comment by frnogueira** [comment]
Ps.: When I try to make one pot file, only five strings are appear

**Comment by jderose9** [comment]
Sounds like Settings.ui.h is not being built or not being scanned. Do you see any errors on "make potfile"? Do you have a Settings.ui.h file in the root afterward? Do you have intltool installed?

**Comment by frnogueira** [comment]
Great! But the js files don't have to be scanned?! I will test...

I run this command:

xgettext -k_ -kN_ -o messages.pot Settings.ui *.js

Found 52 strings to translate.. ;)

**Comment by jderose9** [comment]
Well, there's not many strings (if any) in the .js.

`xgettext `should be executed by `make potfile`. Here's the output of `make potfile` on my machine:

> mkdir -p po
> xgettext -k_ -kN_ -o po/dash-to-panel.pot --package-name "Dash To Panel" prefs.js
> intltool-extract --type=gettext/glade Settings.ui
> Generating C format header file for translation.
> Wrote Settings.ui.h
> xgettext -k_ -kN_ --join-existing -o po/dash-to-panel.pot Settings.ui.h

Anyway, it sounds like you got it and are good to go, right?

Thanks very much for your work on this!

**Comment by frnogueira** [comment]
Well... Soon I'll send the Dash to panel in pt_BR. ;)

**Comment by frnogueira** [comment]
Done! ;)
![captura de tela de 2017-02-13 14-49-54](https://cloud.githubusercontent.com/assets/2768725/22895722/4860fada-f1fc-11e6-9625-609d00815815.png)
I will upload...

**Comment by jderose9** [comment]
Merged in #68. Thanks for your effort!
