### ISSUE TITLE
[feature request] Option preview window

### ISSUE THREAD

**Issue by brandleesee** [jderose9/dash-to-panel#7]
Would you consider having the previews of open windows (minimised/maximised) to be optional? Thanks.

**Comment by jderose9** [comment]
Good idea. I'll add it soon.

**Comment by DeepDlueIV** [comment]
plus

**Comment by brandleesee** [comment]
Thank you, man. 
Works perfectly!
Just one curiosity: what is the extension's name for the little weather applet in your panel's screenshot?

**Comment by Pointedstick** [comment]
@brandleesee Probably OpenWeather: https://extensions.gnome.org/extension/750/openweather/
