### ISSUE TITLE
Option to remove Show Applications button

### ISSUE THREAD

**Issue by iplor** [jderose9/dash-to-panel#71]
Thanks for this great extension. 

I'm using it in conjunction with the [Gno-Menu](https://extensions.gnome.org/extension/608/gnomenu/), which works really well. It makes the Show Applications button redundent though, and I'd like to remove it.

Could this be added as an option, or is there an easy way to tweak this manually?

**Comment by jderose9** [comment]
Yes, it's an option in the settings on the Behavior tab already.

**Comment by iplor** [comment]
Silly me. Yes, found that and it works perfectly. Thank you.
