### ISSUE TITLE
When _checkHotkeyPrefix is enabled, the option for minimize and the option to open new windows does not work. Even KP does not work.

### ISSUE THREAD

**Issue by yuryrodrigues** [jderose9/dash-to-panel#76]
First of all, I want to thank the developers who build this great extension. She is fantastic!

Works perfectly except for keyboard shortcuts.

When **_checkHotkeyPrefix** is enabled, the option for minimize(**app-shift-hotkey-kp-** && **app-shift-hotkey**) and the option to open new windows(**app-ctrl-hotkey-kp-** && **app-ctrl-hotkey-**) does not work. Even KP does not work.

In the dconf-editor it is shown that the shortcuts to these actions are the same. Here's the problem.

The option for change the shortcut(SUPER or SUPER_ALT) is replacing erasing the other shortcuts.

![image](https://cloud.githubusercontent.com/assets/7195945/23349184/9ad6c194-fc8f-11e6-9b03-e214193cfef9.png)

![image](https://cloud.githubusercontent.com/assets/7195945/23349195/b65b8300-fc8f-11e6-9668-1425115a2f90.png)

![image](https://cloud.githubusercontent.com/assets/7195945/23349206/c56310fc-fc8f-11e6-95e5-f27eec2bdf6b.png)

@franglais125

**Comment by yuryrodrigues** [comment]
**Gnome-Shell:** 3.22.2
**OS:** Antergos Linux 64-bit
**Kernel:**  4.9.11-1-ARCH

**Comment by franglais125** [comment]
Thanks for reporting this! I can't test it now, but I'll look into it tomorrow. In any case, what you say makes a lot of sense.

Cheers

**Comment by franglais125** [comment]
Tentative fix: [c8e135c0a4f746e6bb761550c4f0ec2534c356d3].

@yuryrodrigues do you mind testing it? If you know how to install it, here is the branch: https://github.com/franglais125/dash-to-panel/tree/number_overlay

**Comment by yuryrodrigues** [comment]
I tested your code and it fix the problem with the option to minimize(Shift) and open new windows(Ctrl). However, the KP does not work.

@franglais125, I made a modification in your code that fix the KP. Maybe it's useful.
[Pull 1](https://github.com/franglais125/dash-to-panel/pull/1)

**Comment by franglais125** [comment]
Thanks a lot @yuryrodrigues 
I picked your changes and included them here [5f19921c706b91605e9e8e05173e93b0aa06ad77].

@jderose9 both commits are here: https://github.com/franglais125/dash-to-panel/tree/number_overlay
I think that should be enough to fix the issue.

**Comment by jderose9** [comment]
Merged, thanks to you both!
