### ISSUE TITLE
Disabling "Show app menu" option does not trigger app menu fallback

### ISSUE THREAD

**Issue by phw** [jderose9/dash-to-panel#78]
Unlike the option to disable the app menu in Gnome Tweak tools, the "Show app menu" setting of dash to panel is just cosmetic. That also means that applications don't know about it and this will basically disable the app menu completely without any way of accessing it.

Not sure how this can be solved. Is it possible to change the same setting as tweak tools do? At the very least it should honor this setting, because there is no point of showing the app menu in dash to panel if it is globally disabled.

**Comment by jderose9** [comment]
Hi there.. Check out the comments for #2. In short, the appMenu items are now displayed in the right click menu of the application launchers. I'll be releasing to gnome.org soon. The toggle you mention will continue to add/remove the menu from the panel itself but it will always be available from the right click popup. Thanks!

**Comment by phw** [comment]
Yes, I guess this fixes the issue. Tested it here and works fine, no more lost app menus :)
