### ISSUE TITLE
Popups open to the bottom when panel positioned on bottom of top monitor in vertical configuration

### ISSUE THREAD

**Issue by phw** [jderose9/dash-to-panel#79]
I have a dual monitor setup with my large main minitor at the top and my laptop screen as secondary screen on the bottom.

When I configure dash to panel to be shown at the bottom, it is correctly shown on my main screen on the bottom. But all menus (settings, clock, extensions) still open to the bottom, being shown on my secondary screen.

The following recording demonstrates this. It is especially annoying as my bottom screen is smaller, so the gray flickering area on the right is actually off-screen and not visible to me. The menus rendered there are not accessible to me. 

![peek 2017-03-01 12-02](https://cloud.githubusercontent.com/assets/29852/23457167/0e3fa018-fe77-11e6-960d-47f298e65677.gif)

**Comment by jderose9** [comment]
Thanks for reporting this!

I attempted to resolve this but I don't actually have a 2nd monitor at the moment. Can you try the `popuplocation` branch? If you aren't familiar with git, just let me know and I can give you some more instructions. Thanks!

**Comment by phw** [comment]
Yes, that branch fixes the issue. Thanks a lot for the quick response and sorry for me to take a while. I am actually not using your extension (just not my thing, I am happy with Gnome default + Dash to Dock), but Dash to Panel is very well made. Looks already very polished and I think a lot of people will enjoy this user interface.

**Comment by jderose9** [comment]
Thanks for reporting and testing this!
