### ISSUE TITLE
initial release

### ISSUE THREAD

**Issue by carlwgeorge** [jderose9/dash-to-panel#8]
Would you mind creating a tag/release of an initial version?  It would be helpful for those wishing to create system packages.

**Comment by jderose9** [comment]
If I tag "v1", "v2", "v3", etc to match the extensions.gnome.org submissions, does that work?

**Comment by jderose9** [comment]
I've added tags as mentioned in the previous comment (and will continue to do so). Thanks!

**Comment by carlwgeorge** [comment]
Thanks, it's now in the [AUR](https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-panel/).
