### ISSUE TITLE
Integrate Show Apps button into Activities button

### ISSUE THREAD

**Issue by 92Julian** [jderose9/dash-to-panel#82]
Add buttons Windows/Applications to the overview like early Gnome Shell.

![imagen](https://cloud.githubusercontent.com/assets/25293942/23583135/6c8bf284-011a-11e7-82b5-2675e6a99cfd.png)
Others suggestions:

- Add option to show the applications list instead of the windows when Activities button or super key is pressed.
- Add option to change Activities button with Show Apps icon.
- Close  #43 , the user can use [Activities Configurator](https://extensions.gnome.org/extension/358/activities-configurator/) to change the icon.

**Comment by jderose9** [comment]
@92Julian Thanks very much for your time submitting these suggestions. I'm having a little trouble understanding the workflow you are looking for here.

> Add buttons Windows/Applications to the overview like early Gnome Shell.

This is handled by the Show Applications button now. Is there some different behavior you are looking for or just a personal preference to have it rendered as a button group instead?

> Add option to show the applications list instead of the windows when Activities button or super key is pressed.
> Add option to change Activities button with Show Apps icon.

If the Activities button has both the appearance and behavior of the Show Apps button, why not just use the Show Apps button and hide Activities? I think I am misunderstanding.

Are you looking to have the application list open with the Super key and then switch over to the window overview once it has opened?

> Close #43 , the user can use Activities Configurator to change the icon.

I believe Activities Configurator can only change the Activities icon, while #43 is referring to the Show Applications icon.

**Comment by jderose9** [comment]
I really appreciate the feedback, but I'm going to close this for now, as the actionable items from your suggestions seem like they would be appropriate with or without this extension and probably a better fit for their own extension. Thanks again!
