### ISSUE TITLE
Not issue. Question. How does one update?

### ISSUE THREAD

**Issue by dreaddymck** [jderose9/dash-to-panel#86]
Recently getting popups to update "Dash to Panel". How does one accomplish that?

**Comment by franglais125** [comment]
You can visit this website https://extensions.gnome.org/local/ to see the installed extensions, and any upgrades available.

To upgrade, click on the green icons (if you see any).

**Comment by dreaddymck** [comment]
I do not see the option to upgrade. No worries. Thanks for the help.

**Comment by jderose9** [comment]
Try to just remove the extension completely using Tweak Tool (or deleting the directory). Your settings will still be saved in dconf and you can install again.

**Comment by franglais125** [comment]
What I'm thinking is that perhaps @dreaddymck installed the extension from git, using `make install`. IN that case the version string is the latest commit hash.

`chrome-gnome-shell` will think the version number is invalid (or something like that) and notify the user that there is an update. However, then e.g.o/local doesn't act in the same way and shows no update.

**Comment by jderose9** [comment]
@franglais125 I'm not familiar with chrome-gnome-shell or why the popup would be coming up, but gnome.org definitely won't update after installed from github (it has to be completely removed and re-installed). When I upload a new version, it automatically replaces the metadata version with my submission # so I don't think there's anything I can do about that.

**Comment by franglais125** [comment]
Ah yes, don't worry, I wasn't implying that you have a bug or you need to change something :). It was rather a question for @dreaddymck : did you install dash-to-panel manually?

Now, off topic:

- For extension-notifier and apt-update-indicator, I use the same system (version=commit hash) when installing with `make install`, as I think it's better for debugging. This way we can know exactly what version the user is running.
- As for `chrome-gnome-shell`, it's the system users will soon have to install to integrate e.g.o with the local gnome-shell. Firefox deprecated the NPAPI system in v 52 (except ESR), so now they only way to install extensions from Firefox is to install this package and a Firefox add-on. This add-on notifies users when there are extension updates.
- In my own extension-notifier extension, I actually check that the version number is a *number* and not a string, before looking for updates. If it's a string, I assume the user installed this manually, so I won't bother with constant notifications.

**Comment by jderose9** [comment]
I installed `chrome-gnome-shell` and am getting this now. @franglais125 I was curious if you knew what other extensions were doing at this point to deal with this?

**Comment by franglais125** [comment]
@jderose9 Hmm, what do you mean by other extensions? Other Firefox extensions that used to use NPAPI?
