### ISSUE TITLE
Feature request: desktop icon to view Activities Overview

### ISSUE THREAD

**Issue by wolfv6** [jderose9/dash-to-panel#89]
I am too lazy to click Applications > Activities Overview :)

Please place a desktop icon on the top panel, and when mouse hovers over the desktop icon, display Activities Overview.

I love dash-to-panel.

**Comment by jderose9** [comment]
You can enable the activities button on the panel in the Dash-to-panel settings on the Behavior tab.

If you then want to change the icon, check out the extension called [Activities Configurator](https://extensions.gnome.org/extension/358/activities-configurator/).

You can also use Gnome's top left hot corner to open the activities overview without clicking. If you want it in a different corner, try [CustomCorner](https://gitlab.com/eccheng/customcorner).

Does that cover what you are looking for?

**Comment by wolfv6** [comment]
That's what I was looking for, but it didn't word:

    Tweaks tool > Extensions > Dash to panel > Settings > Behavior > Activities Button: ON

What does the Activities Button look like and where is it supposed to appear?

**Comment by jderose9** [comment]
It is the normal Activities button that is on the top bar. It appears all the way at the left of the panel. It's appearance depends on your theme. With the default theme it says "Activities". With Arc it is three dots "...".

**Comment by wolfv6** [comment]
OK, now I see what's going on.
My top panel has an "Applications" button, but not an "Activities" button.  Here is the screen shoot:
![screenshot_dash-to-panel_applications_nobackup](https://cloud.githubusercontent.com/assets/1121166/23835675/3952c43e-0731-11e7-99d4-02d5dd136267.png)

From the Tweak tool:

    Tweak Tool > Extensions > Applications menu: ON

This removes the "Applications" button and adds the "Activities" button:

    Tweak Tool > Extensions > Applications menu: OFF

So my revised feature request is to eat my cake and have it too:

    Place both the "Applications" button and "Activities" button on the panel.

Is there a way to do that?

**Comment by jderose9** [comment]
The Applications menu extension is removing the Activities button. You would have to talk with the author of that extension and ask them to allow you to leave the Activities button.

Or, you could try Gno-menu: https://github.com/The-Panacea-Projects/Gnomenu

**Comment by wolfv6** [comment]
Thank you jderose9.
