### ISSUE TITLE
[feature request] Smart Hiding 

### ISSUE THREAD

**Issue by DeepDlueIV** [jderose9/dash-to-panel#9]
Well that's it. Will be extra sexy
Now it excludes heavyweight dash-to-dock + task-bar. 
FAVORITE EXTENSION. 

maybe option to play with opacity, but not sure.
Love!

**Comment by jderose9** [comment]
Glad you found it useful! Check these out, they will already do what you want:

https://extensions.gnome.org/extension/545/hide-top-bar/
https://extensions.gnome.org/extension/1011/dynamic-panel-transparency/
