### ISSUE TITLE
Missing right-click actions

### ISSUE THREAD

**Issue by LaurentTreguier** [jderose9/dash-to-panel#93]
Since version 7, some specific actions are missing when right-clicking on application icons in the taskbar. There usually a `Show details` action when gnome-software is installed, to show the app in gnome-software. And the other actions are custom ones introduced with an extension I'm maintaining, [gnome-optirun](https://github.com/LaurentTreguier/gnome-optirun), which adds actions to launch applications using the discrete graphics card on optimus-enabled laptops. (EDIT: actually the screenshot I am using for this extension even features dash-to-panel in it)

I think [this commit](https://github.com/jderose9/dash-to-panel/commit/7ae3c4e75c401ce253639c756806cba3e5540997) probably introduced this, at least its title sounds like it could have something to do with it. How exactly do you manage application actions in the extension now ? It looks like it's somehow overriding existing app actions completely.

I'd be willing to patch my extension to fix this if there was a way, but that could still pose a problem if another extension did the same...

**Comment by jderose9** [comment]
It was this commit: b0bf33021918a252ba6dd6783b53d63ad166706a 

I added the items from the application menu of native gnome apps into the menu. I removed Show Details because it seems like a waste of space. I didn't account for other extensions possibly adding new menu items in.

In my override of _redisplay() I can call super method and add/remove/move items afterward so your extension will work again.

**Comment by LaurentTreguier** [comment]
`Show details` didn't seem like a waste of space to me... Would it be possible to add an option to show/hide it ?

**Comment by jderose9** [comment]
@LaurentTreguier It's still available from the full apps list.  It just opens the app in gnome software. Is there any reason to do that after the app is installed?

**Comment by LaurentTreguier** [comment]
@jderose9 I just like having a shortcut to quickly see info about an app. I can totally do without it, but you can't always know when someone wants a feature or not, this is why I thought cutting it out was weird.

**Comment by DreadKnight** [comment]
*Show details* in the menu was a bit silly imho. Better off without it.

**Comment by LaurentTreguier** [comment]
I do use it now and then to see which version of some software I have... A simple switch that is turned off by default would probably do the job

**Comment by DreadKnight** [comment]
I agree, actually tried using it for that purpose myself recently.

**Comment by jderose9** [comment]
@LaurentTreguier I'll add the config option for Show Details soon, but can you see if your extension is working properly now? Thanks!

**Comment by LaurentTreguier** [comment]
@jderose9 just tried out master. I have no idea how you did it exactly, but everything works perfectly regardless of which extension is enabled first, and everything falls back to normal regardless of which extension is disabled first. Great work ! 🎉

**Comment by jderose9** [comment]
The new customization option is there in a submenu under the Fine-tune tab. Do you mind to test? Thanks!

**Comment by LaurentTreguier** [comment]
It's working perfectly. I'll update the French translation for these as well
