### ISSUE TITLE
Extension does not support shell version

### ISSUE THREAD

**Issue by ray81415** [jderose9/dash-to-panel#95]
Hi, I'm Ray. I use debian 8.7 and my gnome version is 3.14.0. When I install dash to panel, the extension list of tweak tool show a message that is "Extension does not support shell version". Could someone help me to fix this problem?

Thank you very much^^

Ray

**Comment by franglais125** [comment]
It's not easy to fix, and probably won't be. Some things this extensions relies on are simply not available on Gnome 3.14 (not sure about 3.16). In any case, Debian Stretch will be released in a few months, and dash-to-panel can be installed on it (Gnome 3.22).

You can perhaps try dash-to-dock https://extensions.gnome.org/extension/307/dash-to-dock/. If you want, you can try this branch: https://github.com/franglais125/dash-to-dock/commits/gnome-3.14-custom

This is what I was using on Debian Jessie myself. It's essentially dash-to-dock with some features I back-ported:
 - window previews
 - workspace isolation
 - hotkeys
 - number overlays

**Comment by jderose9** [comment]
Thanks @franglais125... Yes, this extension only works with gnome shell versions 3.18+.
