### ISSUE TITLE
Auto hide feature request

### ISSUE THREAD

**Issue by alanlivio** [jderose9/dash-to-panel#99]
Before use dash-to-panel, I used the dash-to-dock[1].
I changed to dash-to-panel be cause it can also merge with the top bar, which I prefer.
However, I miss a auto-hide feature of the dash-to-dock, which enable a full screen experience.
Is the auto-hide a future feature?

[1] https://extensions.gnome.org/extension/307/dash-to-dock/

**Comment by jderose9** [comment]
Yup, it's an open request.. Follow #49 for updates. Thanks!
